### ISSUE TITLE
Bot with cognitive services speech services (js) not working when using subscription key instead of a token

### ISSUE THREAD

**Issue by r3dr4gon** [microsoft/BotFramework-WebChat#2405] opened 2019-09-18 14:41 UTC
## Screenshots

![image](https://user-images.githubusercontent.com/14729972/65157971-dac35d80-da31-11e9-9fa8-5ca9e90bf780.png)

## Version

I'm using the template in: "06.c.cognitive-services-speech-services-js", but with hardcoded key for DirectLine and hardcoded subscriptionKey for cognitive services speech.
I did implemented this with electron but the same happen if i use npx serve.

## Describe the bug

I can use the mic button to speak once, then i get: 
"
webchat.js:1 POST https://westeurope.tts.speech.microsoft.com/cognitiveservices/v1 400
webchat.js:1 Error: Failed to syntheis speech, server returned 400
    at VM127 webchat.js:1
Uncaught (in promise) Error: Failed to syntheis speech, server returned 400
Uncaught (in promise) {error: Error: Failed to syntheis speech, server returned 400
    at https://cdn.botframework.com/botframew…, type: "error", target: t}
"
I do get an answer from my bot but without speech and i can not click the mic button again.

## To Reproduce

Use a subscription key instead of tokens.

## Expected behavior

Not breaking :)

## Additional context
The example as is working fine, the problem started when i switched to hardcoded values.
the values are correct though as the bot is functioning and the speech-to-text work one time before crashing (I did try to insert an invaild key to see what happen then i get authentication error as expected.

This is my code:
```
      <script>
	  (async function () {
	    const token =  'XXX';
		
		const region = 'westeurope';
		const subscriptionKey = 'YYY';
		
		const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
	      subscriptionKey,
		  region	   	  
	    });
		
        window.WebChat.renderWebChat({
          directLine: window.WebChat.createDirectLine({ token }),
          webSpeechPonyfillFactory
        }, document.getElementById('webchat'));

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
      </script>
```
[Bug]

PS: if you can point me out to somewhere which explain how to get bit token and cognitive services authorization token with js then i might just skip the hardcoded keys (as this was a first step check).

**Comment by tdurnford** [comment] 2019-09-19 14:25
I wasn't able to reproduce this error, and your Web Chat code seems fine. It appears a 400 error indicates that the language code is not provided or the language isn't supported. If you want to avoid using the subscription key, take a look at the [Speech-to-text REST API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text) Documentation for information issuing a token for Cognitive Speech.

**Comment by r3dr4gon** [comment] 2019-09-19 15:12
Is it possiable the problem is with my chatbot code?
Will it be useful if i provide you with my keys?

**Comment by tdurnford** [comment] 2019-09-19 17:52
I don't think your keys would be helpful. Are you sending any input hints or anything speech related in the bot's response?

**Comment by r3dr4gon** [comment] 2019-09-19 18:17
What I did to convert my Q&A bot to use speech is these steps:
https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0

Which now that I'm saying this seems to actully be the problem(?!)
Were i suppose to do somthing else to add speech? this actully for direct line speech (which is not supported by JS, this also make sense why my bot works with the C# client).

**Comment by tdurnford** [comment] 2019-09-19 19:11
@r3dr4gon Thanks for the additional information.  It looks like Web Chat is nesting the Speech Synthesis Markup Language (SSML) which is causing the Cognitive Speech ponyfil to fail. If you remove the speak and voice tags from the activity's `speak` property, it should work fine. 

This is a known issue in Web Chat. I'm closing this issue as we are already using #1322 to track the bug.

**Closed by tdurnford** 2019-09-19 19:11 UTC
Labels: Bot Services, Bug, Pending, customer-replied-to, customer-reported

**Comment by r3dr4gon** [comment] 2019-09-19 19:35
Awsome... Indeed changing the speak function to:
```
        public IActivity Speak(string message)
        {
            var activity = MessageFactory.Text(message);
            activity.Speak = message;
            return activity;
        }
```

Solved my problems, Thanks a lot for the help.
