### ISSUE TITLE
To display chat date and time for every message in webchat

### ISSUE THREAD

**Issue by Sivapuc** [Microsoft/BotFramework-WebChat#908] opened 2018-03-20 09:25 UTC
Hi,
I am using Microsoft BotFramework.  I have integrated the bot with my website but I am having a use case that needs to show every chat message's date and time for old one's.  Could anyone please guide me a solution for it.

**Comment by Sivapuc** [comment] 2018-03-20 12:44
Please suggest a solution using Node JS.

**Comment by compulim** [comment] 2018-03-20 18:41
I think [this line](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L136) decide whether to show the timestamp. You may want to force it into `true` all the time.

**Comment by compulim** [comment] 2018-06-15 04:48
Dupe of #985. Since there are more traffic on that bug, I will close this one.

The features has been added to our "customizability" project for planning.

**Closed by compulim** 2018-06-15 04:48 UTC

**Comment by venkatx5** [comment] 2020-08-03 16:20
In Webchat StyleOptions, add the below attribute.

`timestampFormat: 'absolute', `

**Explanation**

'absolute' will render exact time like "August 3, 10:30 AM"

'relative' will render as "1 minute ago"

===========================================================

```
var styleOptions = {
        bubbleBackground: 'rgba(196, 196, 205, .3)',
        bubbleFromUserBackground: 'rgba(255, 230, 0, .3)',
        botAvatarImage: ChatImagePath + 'icon_round.png',
        botAvatarInitials: 'CB',
        userAvatarImage: ChatImagePath + 'user_icon.png',
        userAvatarInitials: 'YOU',
        hideUploadButton: true,
        timestampFormat: 'absolute', // 'relative'
        sendBoxButtonColorOnFocus: '#999999',
        sendBoxButtonColorOnHover: '#004E9A',
        sendBoxButtonColor: '#999999'
    };
   window.WebChat.renderWebChat(
    {
        directLine: directLine,
        locale: 'en-US',
        // Passing 'styleOptions' when rendering Web Chat
        styleOptions
    },
    document.getElementById('chatbotdiv')
   );
```
