### ISSUE TITLE
ID from conversationUpdate and other activities are different

### ISSUE THREAD

**Issue by Mikolasek93** [Microsoft/BotFramework-WebChat#867] opened 2018-02-21 18:06 UTC
Hi,
i just tried some default code from sample backchannel:

Client Side
```
const botConnection = new BotChat.DirectLine({secret: 'XXX'});
        
		BotChat.App({
			directLine: botConnection,
			user: { id: 'User' },
			bot: { id: 'cz-gdpr-bot' },
			resize: 'detect'
		}, document.getElementById('botModalBody'));

        function postLanguage(){
            var userLang = navigator.language || navigator.userLanguage; 
            botConnection
            .postActivity({from: {id: botConnection.conversationId },
             type: "chatInit", value: userLang, name: "postLanguage"})
            .subscribe(id => console.log("success"));
    }

postLanguage();
```

Server side

```
bot.on("chatInit", (event) => {
      if (event.name === "postLanguage") {
        console.log(event.address);
   });


    bot.on("conversationUpdate", (data: any) => {
      // detect new user in conversation and start root dialog
      if (data.membersAdded && data.membersAdded.length > 0) {
        /******************/
           data.membersAdded.forEach((identity: any) => {
          if (identity.id === data.address.bot.id) {
            // Bot is joining conversation
            // - For WebChat channel you'll get this on page load.
           /****************************************************************/
           console.log(data.address);
          /*******************************************************************/
          }
        });
      }
    });
```

address object prints 2 different "conversation id" which remains that i cannot start dialog with using the "chatinit" event. Is there any posibility to "share" conversationid within a page? Or is it predicted behavioral that with new "postactivity" bot starts new conversation?

Sorry for my explanation and english im deadly tired.

**Comment by compulim** [comment] 2018-06-15 10:33
@EricDahlvang did you mention something similar in other issue? I remember one talked about user ID was actually a conversation ID or something. Can you look at this one?

**Comment by billba** [comment] 2018-06-16 19:00
This code is not correct:

1. The `from.id` in your backchannel message should match the `user.id` you used when calling `Bot.App`
2. The point of using the backchannel is to work around the failings of `conversationUpdate` so don't put your code there. Instead, use your `bot.on('chatInit', ...)` handler to do something with the user language. You may not need to handle `conversationUpdate` at all.
3. (optional) Instead of creating a new activity type `chatInit` I suggest you just use `event` -- that's what it's for

**Comment by compulim** [comment] 2018-06-18 21:28
Seems dupe of #1013

**Comment by CoHealer** [comment] 2018-11-19 20:38
@billba, apologies this went stale. If this is still an open issue for you, please let me know and we'll get a support engineer to investigate

**Comment by corinagum** [comment] 2018-11-29 22:03
Please refer to https://github.com/Microsoft/BotFramework-WebChat/issues/1371. Closing due to inactivity.

**Closed by corinagum** 2018-11-29 22:03 UTC
Labels: Support, Triaged
