### ISSUE TITLE
Webchat mobile view issues

### ISSUE THREAD

**Issue by raviranjan20** [Microsoft/BotFramework-WebChat#429] opened 2017-04-18 09:12 UTC
Hi,

I am using web chat as channel in this case. When I create a hero control in bot and click the button, it by default opens keyboard on mobile device making bot window size by half. Is there any option to block the keyboard until I specifically click text box to write something ?

**Comment by billba** [comment] 2017-04-18 13:06
Ah, this is because we now set the focus to the edit field after clicking a button. This will be hard to get right.

**Comment by raviranjan20** [comment] 2017-04-19 07:06
Thanks for the quick reply, is there any way to over ride this behavior ?

**Comment by danmarshall** [comment] 2017-04-19 21:22
Hi @raviranjan20 thanks for reporting this issue. It was caused by a feature change in #411 , I am going to close this issue #429 and we can continue tracking in #411.

**Closed by danmarshall** 2017-04-19 21:22 UTC
