### ISSUE TITLE
ReactWebchat is not defined

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#3001] opened 2020-03-11 07:51 UTC
Hi All,

as i am trying to enable the webchat using react but everytime the issue is showing like :- "ReactWebchat is not defined". I also noticed that the github samples are also having same issue.
please check from your end and let me know about the issue.
here is the attached error screenshot:-
![Screenshot (1)](https://user-images.githubusercontent.com/34365788/76394257-30eadb00-639b-11ea-8934-fecf031131b8.png)

**Comment by stevkan** [comment] 2020-03-11 19:23
At this moment, I am unable to repro your issue. Can you check which version of Web Chat you are running? And, can you post the code you are using when you encounter this error? Lastly, which samples did you try (so I can check those)?

**Comment by Bradrajkumar** [comment] 2020-03-12 06:58
i was able to resolve the issue. there are some of the samples not working on git hub, please look into this and update me. Below are the links:-
https://microsoft.github.io/BotFramework-WebChat/05.custom-components/g.activity-status/
https://microsoft.github.io/BotFramework-WebChat/04.api/h.clear-after-idle
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/k.telemetry-google-analytics
https://microsoft.github.io/BotFramework-WebChat/05.custom-components/i.notification/
https://microsoft.github.io/BotFramework-WebChat/05.custom-components/j.typing-indicator/
https://microsoft.github.io/BotFramework-WebChat/05.custom-components/k.per-message-avatar/
https://microsoft.github.io/BotFramework-WebChat/05.custom-components/g.activity-status/

**Comment by stevkan** [comment] 2020-03-16 20:56
Can you elaborate on what was causing the issue and how you resolved it?

**Comment by congysu** [comment] 2020-03-27 18:09
close this since the issue is resolved.

**Closed by congysu** 2020-03-27 18:09 UTC
Labels: Bot Services, customer-replied-to, customer-reported
