### ISSUE TITLE
role property is not set for messages sent by bot

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/BotFramework-WebChat#1886] opened 2019-04-10 11:25 UTC
# Description (Actual behavior)
I noticed that `in the the Web Chat channel`
- the **`role` property is not set** in `from` for messages **sent by the bot**
- the role is set correct for messages **sent by the user** however

This applies both to
- the embed WebChat from the Azure Portal, hosted at `https://webchat.botframework.com/embed/<botId>?s=<secret>`
- self-hosted webchat using the [Full Bundle example](https://github.com/Microsoft/BotFramework-WebChat#full-bundle) from the WebChat readme

Therefore, I cannot search for message sent by the bot by filtering
- by `type == "message"` AND
- by `role == "bot"`

(since `role = bot` is not set, zero messages are found)

The bot emulator correctly fills the role property though.

# Expected behaviour
When a user has a conversation with the bot, I can get messages sent by the bot by filtering
- by `type == "message"` AND
- by `role == "bot"`

# Workaround
To get bot messages: filter activities in the webchat
- by `type == "message"` AND
- by `role != "user"`

# Related PRs
- https://github.com/Microsoft/BotFramework-WebChat/pull/1053
- https://github.com/Microsoft/BotFramework-WebChat/pull/1405

**Comment by hansmbakker** [comment] 2019-04-12 10:58
@corinagum what do you mean with "need more detail"?

**Comment by corinagum** [comment] 2019-04-12 16:10
Hi @hansmbakker, sorry for the confusion - the "Need more detail" label just means that the team hasn't investigated this issue yet. :) In this case, I have read the issue but haven't reproduced it or discussed it with other team members. This is also when we determine the T-Shirt size and how soon we want to implement the feature or fix. Hope that helps!

**Comment by hansmbakker** [comment] 2019-04-13 08:57
Thanks for the clarification!

**Comment by tdurnford** [comment] 2019-04-17 21:08
@hansmbakker Where are you trying to filter the activities?

**Comment by hansmbakker** [comment] 2019-04-18 08:41
First I would like to share that the filtering likely is not the problem here; it works with the bot emulator. I believe the web chat simply does not add the `"role": "bot"` property to the activities sent by the bot.

I do the filtering in the bot's webapp (I'm using the enterprise bot template).

I want to build functionality where the user can download a transcript of his conversation.

So what I do:
- in a conversation I use the bot framework's transcript store (`AzureBlobTranscriptStore`) to fetch conversations as a `List<IActivity>`
- I filter out all message activities
- I process it into my own viewmodel and render it into a template that I offer as a download to the user

**Comment by tdurnford** [comment] 2019-04-18 18:56
I agree that the issue is most likely not with filter the activities. I wanted to be sure I was reproducing the behavior properly. Thank you for clarifying your issue.

**Comment by tdurnford** [comment] 2019-04-19 18:24
Just taking a loot at the ConsoleTranscriptLogger, it looks like you are correct. The from attribute in Activities sent by the bot are being set properly when client is the emulator but not WebChat. Take a look at the screenshots below. 

```js
adapter.use(new TranscriptLoggerMiddleware(new ConsoleTranscriptLogger()));
```

**Emulator**
<img width="500" alt="Untitled" src="https://user-images.githubusercontent.com/17039790/56437566-d46b6280-6294-11e9-9eb7-e2dc6811782f.png">

**WebChat**
<img width="500" alt="Untitled1" src="https://user-images.githubusercontent.com/17039790/56437572-d8978000-6294-11e9-81ca-c49e0c72ffcf.png">

I think it's worth noting that the TranscriptLoggerMiddleware sets the role for Activities sent by the user if it is missing. 

https://github.com/Microsoft/botbuilder-dotnet/blob/a5ba0c40aa962188ce52a8a152af1128dcfa7aa1/libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs#L55

**Comment by hansmbakker** [comment] 2019-04-19 18:39
Nice that you could reproduce it!

**Comment by corinagum** [comment] 2019-04-19 22:36
From the looks of the [Bot Framework schema](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#conversation-account-role), this intentional in the protocol and is a **wontfix**. 

> `A7512`: Senders SHOULD NOT include this field. Receivers SHOULD ignore this field.

I believe expectation is that users of DLJS who want to utilize role must fill it themselves, and `role` is assigned in Emulator because it's functionality of displaying transcripts.
@cwhitten @compulim @tonyanziano is this something we would want to revert in Emulator?

**Comment by corinagum** [comment] 2019-04-26 22:00
Adding @justinwilaby to the list of pings :)

**Comment by justinwilaby** [comment] 2019-04-26 22:55
@corinagum is correct. The required fields for a `ChannelAccount` object are `id` and `name`. The `role` field is used by the Emulator for the purpose of exporting transcripts.

**Comment by corinagum** [comment] 2019-04-29 17:49
I'm going to close this as a won't fix. We can always open this up to further discussion again at a later time. :)

**Closed by corinagum** 2019-04-29 17:49 UTC
Labels: Need more detail, Pending

**Comment by hansmbakker** [comment] 2019-09-04 12:07
My usecase is, simply put:
> I want to display transcripts in a proper way to my editor team who will improve the bot based on conversations that users have.

@corinagum since (per the [Bot Framework schema](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#conversation-account-role) also linked by @corinagum)
>This field is intended for use in the Transcript format [16] to distinguish between activities sent by users and activities sent by bots.

The field supports my usecase, but the field only adds value when it is properly filled. What component should fill the `role` property according to Microsoft?

**Comment by corinagum** [comment] 2019-09-04 17:07
My understanding is that it would be the user's responsibility to write this patch. 

Would you be able to implement something similar to [Web Chat's role patch](https://github.com/microsoft/BotFramework-WebChat/blob/7d813c6ff3eb1c1ac61ecd153671d8ad07f432c5/packages/core/src/sagas/incomingActivitySaga.js#L11)?

**Comment by compulim** [comment] 2019-09-04 17:45
According to the spec [Conversation account role](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#conversation-account-role), it should be filled by the receiver from the Direct Line channel, and removed before sending it back to the channel.

IMO, the ideal case would be DirectLineJS filling it and removing it. So it is most transparent to the user and also most usable.

**Comment by hansmbakker** [comment] 2019-09-05 07:24
@corinagum could you explain where/how that code is used? Is it used by WebChat and does WebChat remove the role again before sending it to the bot?

@compulim I am using the Virtual Assistant C# template --> did you mean DirectLineJS as a WebChat dependency or as a dependency for the bot adapter? In that case it would need to be done by `Microsoft.Bot.Connector.DirectLine` I believe?

@corinagum When implementing it into my project I could implement it as middleware for virtual assistant.

**Comment by corinagum** [comment] 2019-09-06 01:07
Yes, Web Chat routes it through to add the role and it should be removed.

(To answer your question to compulim as well)
Yes, in this case he is referring to DLJS as a dependency on Web Chat.

**Comment by hansmbakker** [comment] 2019-09-11 16:30
Ok, I'll look into writing middleware that does it.

@corinagum @compulim what is the risk of not removing the `bot` role? I don't understand why it needs to be cleared afterwards.
