### ISSUE TITLE
Bump Cognitive Services SDK to 1.9.1 due to a bug in Electron

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2886] opened 2020-02-06 20:54 UTC
## Version

`4.7.1`

## Describe the bug

Direct Line Speech failed to load in Electron due to a bug in Cognitive Services Speech SDK. It is fixed in 1.9.1.

https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/138
https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/126

## Steps to reproduce

1. Put Web Chat inside an Electron app (Chrome 69)
1. Use Direct Line Speech to connect to bot
1. Start recognizing

## Expected behavior

It should start recognizing and sending WAV to the Speech servers. Instead, it just say "Starting..." and hang from there.

## Additional context

Tagging @tonyanziano.

[Bug]

**Comment by corinagum** [comment] 2020-04-06 13:07
Dupe of #3079?

**Closed** 2020-04-22 23:42 UTC
Labels: Bug, R9
