### ISSUE TITLE
Custom voice is not being supported

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2471] opened 2019-10-15 13:44 UTC
## Version
4.5.2

## Describe the bug
i have added all fields defined in the documentation,but the custom voice is not playing.

## To Reproduce

selectVoice: () => ({ voiceURI: 'BlaBla' }),
            webSpeechPonyfillFactory: await this.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
                region: 'westus2',
                speechSynthesisDeploymentId: 'e123sdf3423c',
                subscriptionKey: 'sdf24232dsff'
            })

**Comment by tdurnford** [comment] 2019-10-15 13:47
This looks like a duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/2424 which should be resolved in our next release towards the end of the month.

**Comment by corinagum** [comment] 2019-10-15 16:47
Closing as duplicate.

**Closed by corinagum** 2019-10-15 16:47 UTC
Labels: Bot Services, Duplicate, customer-replied-to, customer-reported
