### ISSUE TITLE
Duplicate of root dialog welcome message if using proactive message node js

### ISSUE THREAD

**Issue by starlord-daniel** [Microsoft/BotFramework-WebChat#534] opened 2017-06-26 15:22 UTC
The behavior occurs when I add a proactive message to the bot which greets the user every time a new user is added:

```js
bot.on('conversationUpdate', function (message) {
    if (message.membersAdded) {
        message.membersAdded.forEach(function (identity) {
            if (identity.id === message.address.bot.id) {
                bot.beginDialog(message.address, '/');
            }
        });
    }
});
```

The emulator works fine, but when I test it in the Web Chat, after I do a choice in the root dialog, the message just reappears. Is there any way to circumvent this behavior? Root code:

```js
bot.dialog('/', [
    function (session, results, next) 
    {
        var choices = ["option 1", "option 2"];
        builder.Prompts.choice(session, "prompt", choices, { listStyle: builder.ListStyle.button });
    },
    function (session, results) 
    {
        if (results.response)
        {
            var selection = results.response.entity;
            
            // route to corresponding dialogs
            switch (selection) 
            {
                case "option 1":
                    session.replaceDialog('/d1');
                    break;
                case "option 2":
                    session.replaceDialog('/d2');
                    break;
                default:
                    session.reset('/');
                    break;
            }
        }
    }
]);
```

Best,
Daniel

**Comment by billba** [comment] 2017-06-26 15:37
This is not a bug in WebChat but instead a difference between Direct Line and the Emulator's emulation of Direct Line. This is a very common report. @eanders-MS maybe we should make the Emulator follow the behavior of Direct Line until @dandriscoll fixes the underlying problem?

**Comment by billba** [comment] 2017-06-26 15:37
Closing as not a bug in WebChat.

**Closed by billba** 2017-06-26 15:37 UTC

**Comment by SilvaLA59** [comment] 2017-10-23 16:27
How is the solution to work with conversation.update in this case?

**Comment by an0o0nym** [comment] 2017-11-25 03:02
@billba Could you please point us out in the right direction of what is causing this behaviour and what is wrong with the code above?

**Comment by billba** [comment] 2017-11-26 00:20
I believe this might be helpful: https://stackoverflow.com/questions/41823446/when-user-sends-message-to-my-bot-he-receives-welcome-message-but-when-user-re

**Comment by an0o0nym** [comment] 2018-01-18 12:10
@starlord-daniel I finally got my answer to a similar problem. Please refer to this GitHub Issue [[Question]Bot displays unnecessary messages? #3901](https://github.com/Microsoft/BotBuilder/issues/3901). Hopefuly it helps!
