### ISSUE TITLE
How to add txt with newlines in webchat

### ISSUE THREAD

**Issue by radennis** [Microsoft/BotFramework-WebChat#439] opened 2017-04-26 16:51 UTC
We are working on a bot that helps users create support tickets, using WebChat channel.
 
In some of the fields **users** would want to add multiple line information, for instance:
“I have problems with the following:
1. Number one
2. number two” 
 
Currently when a user wants to add a text with newlines it just sends the message. Is there some kind of combination such as SHIFT+ENTER that allows adding a newline without sending the message yet, in WebChat channel?

**Comment by danmarshall** [comment] 2017-04-26 17:52
Hi @radennis , this is a duplicate of issue #124

**Closed by danmarshall** 2017-04-26 17:52 UTC
