### ISSUE TITLE
Need to prevent form.submit on click of buttons in the AdaptiveCards in WebChat

### ISSUE THREAD

**Issue by vinod83k** [Microsoft/BotFramework-WebChat#650] opened 2017-08-25 10:34 UTC
We are using WebChat as a control in our website which is a CMS(Kentico), which by-default has Form.Submit functionality on every page. I have included both botchat.js and botchat.css in my project and able to render the control properly by making some changes in the botchat.css file. But, when we click on any of the button of the Adaptive cards being rendered, it takes it as a PostBack and my whole page is refreshed. 
I would request you to please let us know at all the .ts or .tsx files of WebChat, where we can make changes to avoid this postback.

**Comment by danmarshall** [comment] 2017-08-28 17:21
Related to #594

**Comment by danmarshall** [comment] 2017-09-05 19:51
Closing this as a duplicate of #594 , fix is in PR #661  right now

**Closed by danmarshall** 2017-09-05 19:51 UTC
