### ISSUE TITLE
QnAMaker responses are said twice when using webchat

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-WebChat#1863] opened 2019-02-14 07:10 UTC
**Project**
Virtual Assistant

**Description**
When you use speech, QnAMaker responses seem to be read twice when using webchat (this doesn't seem to happen in the emulator)

**To Reproduce**
1. Deploy VA to webchat with speech enabled.
2. Say "What is your name" using speech
3. You'll hear "My name is the Virtual Assistant! Nice to meet you :)" twice.

**Expected behavior**
It should only say the response once.

**Comment by compulim** [comment] 2019-04-04 22:24
## Background

All rich cards, including thumbnail card, is converted to Adaptive Cards on render.

## Investigation steps

1. Launch Narrator
1. Load Web Chat in Edge, thru microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/
1. Type "card bingsports"

If the problem persists, we should fix it. If not, we should try a ThumbnailCard and see if it repro.

### Expected

Narrator should only speak out "The Seattle Seahawks beat the Carolina Panthers 40-7", but not the content.

**Comment by compulim** [comment] 2019-06-18 21:42
@corinagum could you investigate with the repro steps above and see if it repro?

One thing Gabo pointed out "If the qna answer gets deserialized in the thumbnail card and the Speak property is populated, Speech reads the Speak property AND the text on the card."

**Comment by corinagum** [comment] 2019-06-19 22:37
@gabog, are you still having this issue? I am not able to reproduce this on Mock Bot with a Thumbnail card. **Could you clarify whether you are using Narrator, Cognitive Services Speech Services, or both?** If Narrator, I believe this is an Adaptive Cards problem (see below). If Cognitive Services, then I will need more information to reproduce.

Regarding Narrator: I tried the Narrator steps that @compulim applied above, but I think they show a different bug than what @gabog reported. This has to do with how Adaptive Cards handles `aria-label`, which provides a high level description of the card via the speak property, but doesn't allow the user to hide irrelevant containers or text, or a way to manually provide aria-labels that improve the understanding of the card. If this is the issue you're having, @gabog, please let me know and I will close this issue. I recommend filing this again with the Adaptive Cards team. 

If this is an ongoing Cognitive Services issue and Narrator is not involved, please copy-paste our 'New issue' template for reporting bugs and provide the information requested in that template. (You don't have to file a new issue, continuing the conversation in this thread is fine). Thanks!

**Comment by gabog** [comment] 2019-06-20 19:14
Hi, below is the repro code:

The minimalistic code to generate the card in C# is: 

        public static IMessageActivity BuildThumbnailCard()
        {
            var response = Activity.CreateMessageActivity();
            response.Speak = "This is what the bot should say";
            var card = new ThumbnailCard(text: "This text goes in the card (and SHOULD NOT BE SPOKEN)")
            {
                Images = new List<CardImage>
                {
                    new CardImage("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtB3AwMUeNoq4gUBGe6Ocj8kyh3bXa9ZbV7u1fVKQoyKFHdkqU")
                }
            };
            response.Attachments = new List<Attachment>
            {
                card.ToAttachment(),
            };

            var jsonResponse = JsonConvert.SerializeObject(response);

            return response;
        }

That produces the following json for the activity:

{
  "type": "message",
  "id": null,
  "timestamp": null,
  "localTimestamp": null,
  "localTimezone": null,
  "serviceUrl": null,
  "channelId": null,
  "from": null,
  "conversation": null,
  "recipient": null,
  "textFormat": null,
  "attachmentLayout": null,
  "membersAdded": null,
  "membersRemoved": null,
  "reactionsAdded": null,
  "reactionsRemoved": null,
  "topicName": null,
  "historyDisclosed": null,
  "locale": null,
  "text": null,
  "speak": "This is what the bot should say",
  "inputHint": null,
  "summary": null,
  "suggestedActions": null,
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "contentUrl": null,
      "content": {
        "title": null,
        "subtitle": null,
        "text": "This text goes in the card (and SHOULD NOT BE SPOKEN)",
        "images": [
          {
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtB3AwMUeNoq4gUBGe6Ocj8kyh3bXa9ZbV7u1fVKQoyKFHdkqU",
            "alt": null,
            "tap": null
          }
        ],
        "buttons": null,
        "tap": null
      },
      "name": null,
      "thumbnailUrl": null
    }
  ],
  "entities": [],
  "channelData": null,
  "action": null,
  "replyToId": null,
  "label": null,
  "valueType": null,
  "value": null,
  "name": null,
  "relatesTo": null,
  "code": null,
  "expiration": null,
  "importance": null,
  "deliveryMode": null,
  "listenFor": null,
  "textHighlights": null,
  "semanticAction": null
}


When using speech, the bot will read the text property in the card and the speak property in the activity.

It should only read aloud the Speak property if set and never read the Text property in the card.

**Closed** 2019-06-25 18:57 UTC
Labels: 4.5, Approved, Bug, Help wanted, P1, Triaged
