### ISSUE TITLE
Change speechSynthesizer voicename in Node js

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotFramework-WebChat#605] opened 2017-07-28 20:27 UTC
I have created a bot in node js and it can now talk. How can I change its voce it JessaRUS for example? Is there a bot.set('speechOptions', speechOptions)? and set voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'? Thank you!

**Comment by danmarshall** [comment] 2017-07-28 20:54
@shahidkhuram can you help?

**Comment by nwhitmont** [comment] 2017-08-02 00:56
duplicate of: https://github.com/Microsoft/BotBuilder/issues/3231

**Comment by danmarshall** [comment] 2017-11-21 22:38
@shahidkhuram ping :)

**Comment by shahidkhuram** [comment] 2017-11-22 02:49
As Nils responded earlier, i think this is a dupe and should be closed. Let me know if there's a remaining issue.

**Closed** 2017-11-22 05:03 UTC
Labels: speech
