### ISSUE TITLE
Sample: Chat bot single sign-on

### ISSUE THREAD

**Issue by pedrosalider** [microsoft/BotFramework-WebChat#1564] opened 2019-01-09 20:58 UTC
I have a bot running on a hosting page where users are logged in using SSO.
I want to authenticate the user in the bot automatically when the bot starts and I do not want to use anAuthCard to do it. Just want to automatically authenticate the user without prompting anything to him, just using SSO.

I found an article that refers three ways to authenticate an user in the bot:

Sharing the client's user token directly with the bot via ChannelData
Using an OAuthCard to drive a sign-in experience to any OAuth provider
A third option, called Single Sign-On (SSO), that is in development.
And, according to the article my situation is:

WebChat in an authenticated website where the user is already signed in and the website has a token to the same identity provider but to a different app that the bot needs -> in the future, this is single sign-on, but for now you 'll need to use an OAuthCard.

Is there any update about this functionality? How can I authenticate the user into the bot without using an OAuthCard or a SigninCard?

Thanks in advance

**Comment by corinagum** [comment] 2019-01-10 18:04
Hi @pedrosalider, do you mind sharing the article that refers to three ways to authenticate? :)

I have closed #1503 as a dupe of this issue. I know that @compulim kept it open because he wants to give you a detailed response, but we've been low on bandwidth and he hasn't been able to respond to your question yet.

@compulim assigning you as gentle reminder 👍

**Comment by pedrosalider** [comment] 2019-01-10 21:48
Hi @corinagum. You can find the article [here](https://blog.botframework.com/2018/08/28/sign-in-experiences/). I copied the text from stackoverflow and I forgot about the link.

**Comment by corinagum** [comment] 2019-01-14 22:13
+1 from @darrenj via email discussion

**Comment by darrenj** [comment] 2019-01-18 14:48
I spoke to another customer today who has a pressing need for this capability in their internal Bot, scenario information below. This is quite a common scenario and there have been people that have solved it externally to Microsoft eg: [this article](https://stephaneeyskens.wordpress.com/2017/01/04/microsoft-bot-framework-transparent-authentication-with-the-webchat-control/)

The scenario is:

- An ASP.NET web-page on the company intranet which makes use of the WebChat control has AD Authentication enabled (normal ASP.NET auth configuration)
- User is already authenticated on the network and the act of browsing to said intranet page authenticates the user to the ASP.NET App/page.
- UserId is retrieved from claim provided and set on WebChat control
- Token is passed to the Bot (event?)
- User starts talking to the Bot and asks a question requiring access to a corporate service, Microsoft graph for example. 
- Bot uses the token passed to the Bot and **does not** prompt the user for authentication
- Currently the Bot will prompt the user to authenticate even though they are already authenticated

We need two things (suggested order) - ideally both by the end of month but could work with just the recommended approach if needed.

- [ ] Recommended approach
- [ ] Sample

**Comment by cwhitten** [comment] 2019-01-18 20:22
Thank you @darrenj. @compulim is going to provide a recommended approach soon and we will include a sample of such an approach at a later date.

**Comment by darrenj** [comment] 2019-01-21 07:19
Thanks!

Sent from Outlook Mobile<https://aka.ms/sdimjr>
________________________________

**Comment by anevjes** [comment] 2019-01-29 13:35
HI team, I too am facing the exact single sign on requirements without having the oAuth card thrown? @compulim / @cwhitten any updates as per above?

**Comment by darrenj** [comment] 2019-01-30 09:32
A sample showing how a enterprise/intranet scenario using WebChat can retrieve a (AAD token) from the browser session (already authenticated) and pass through channelData will be key for our enterprise customers to get started. Unclear from the above if httpOnly will need to be enabled for this scenario so would be good to clarify - perhaps by having a section for Intranet/Enterprise scenarios?

**Comment by compulim** [comment] 2019-02-15 02:03
In my experience, Intranet/enterprise means a custom scenario and not necessarily AAD. Please correct me if I am wrong.

We can setup a section specifically for AAD.

**Comment by darrenj** [comment] 2019-02-15 02:08
AAD is a safe assumption given our customers.

**Comment by cbtham** [comment] 2019-03-22 04:36
Is there a good guide/sample around SSO? I see that Darren is onto something :) There is another customer asking something similar

**Comment by mekinney** [comment] 2019-04-30 15:03
Following this thread, because I have the exact same need and this is a very common scenario for enterprise customers.

**Closed** 2019-06-19 18:32 UTC
Labels: 4.5, Approved, P0, Sample, Triaged
