### ISSUE TITLE
Kickstart conversation

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotFramework-WebChat#709] opened 2017-10-02 22:29 UTC
Hi,
After initialising the WebChat, I'd like my bot to kickstart the conversation.

I tried something like:

```
$('.wc-shellinput').val('hello').trigger('change')
$('.wc-send').click()
```
But it won't trigger because of change event not fired to wc-shellinput.
(No I d'ont want to postActivity using backstage)

**Comment by alyssaong1** [comment] 2017-10-03 02:03
You can do this from the bot side by listening for the 'conversationUpdate' event and sending a message.
In this way, when the webchat is first initialised along with the bot, the bot will send a proactive welcome message to the user. 

See [this link](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages).

**Comment by danmarshall** [comment] 2017-10-03 05:19
This may be a duplicate of #680. React is managing the state, so modifying the textbox value in the DOM won't get picked up. Perhaps we should add an API to set the text?
Or you can do it from the bot as @alyssaong1 suggested.

**Comment by JpEncausse** [comment] 2017-10-03 15:42
Thanks, in normal usage yes I would use conversationUpdate.

My use case is a little bit tricky. It's for a landing page (http://bot.viseo.io) that show off a bot. i'd like to kickstart the conversation to involve the user.

**Comment by billba** [comment] 2017-10-03 16:05
Why does using converationUpdate not work for your scenario?

**Comment by JpEncausse** [comment] 2017-10-03 17:54
Well I think the behavior of the bot should remain the same when we talk to it. It should have a custom behavior because of a conversationUpdate from a given landing page. 
(Yes it should work but it's kind of a hack where I just want to control the bot)

BTW, an other usecase, I was looking for a way to automate testing chat. I think you should let more control on that Web UI. Good things can come

**Comment by billba** [comment] 2017-10-03 18:00
I don't understand. conversationUpdate is not a hack. It is an activity generated from all channels when a user joins a conversation. Responding to that activity is a best practice for a bot "kickstarting" a conversation. If this doesn't work for your scenario please be extremely specific about your needs or close this issue.

**Comment by danmarshall** [comment] 2017-10-03 19:02
@JpEncausse are you looking for something like `sendMessage: (text: string)` ?

This is in the source [here](https://github.com/Microsoft/BotFramework-WebChat/blob/88034a804bf438c99d9f47e0d977e7cf4ec76e2b/src/Shell.tsx#L159) it is internal only. Perhaps you can make it public so that you can call it from your app.

**Comment by tiloc** [comment] 2017-10-10 16:00
I am having a related issue with "conversationUpdate". I am reacting to conversationUpdate and checking whether a member has been added, then posting my welcome banner (a hero card). This works well in the emulator. In the web chat however, I am seeing behavior, where after opening a new web chat, I am seeing a blank chat window. If I then send any message, for instance "hello", the conversationUpdate gets triggered and responds with the banner. Is there sample bot code that is known to start the conversation immediately after the web chat has been loaded?

**Comment by billba** [comment] 2017-10-11 14:13
@tiloc Your bot should get a `conversationUpdate` update as soon as WebChat is able to connect. This is functionality you can depend on. However the emulator has slightly different behavior than the real-life Direct Line, so I suggest you debug your bot code carefully, perhaps using `ngrok` to run the bot locally.

**Comment by billba** [comment] 2017-10-11 14:14
Since there has been no response from the original poster, I'm closing this issue.

**Closed by billba** 2017-10-11 14:14 UTC
