### ISSUE TITLE
Compile error: Can't resolve 'botframework-directlinejs'

### ISSUE THREAD

**Issue by stanleyk** [microsoft/BotFramework-WebChat#3924] opened 2021-06-02 13:35 UTC
## Version

botframework-webchat-api@4.13 installed via npm

## Describe the bug

When trying to compile on my TS React project with Webpack 5 (not a CRA), I get the following error:

```
ERROR in ./node_modules/botframework-webchat-core/lib/sagas/connectSaga.js 16:32-68
Module not found: Error: Can't resolve 'botframework-directlinejs' in '/var/www/html/node_modules/botframework-webchat-core/lib/sagas'
```

## Expected behavior

The app should compile without errors.

**Comment by corinagum** [comment] 2021-06-02 18:17
Duplicate of #3908. Please also see #3856

**Closed by corinagum** 2021-06-02 18:17 UTC
Labels: Bot Services, Bug, customer-reported
