### ISSUE TITLE
Request: Add bubble nub to attachments

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2667] opened 2019-12-04 18:45 UTC
##
Right now, attachments (carousel, adaptive card, image, etc) will not show a bubble nub even when bubblenub is enabled. This is by design. The request is to enable the user to choose to include a nub on the attachments or not.

---

## Screenshots

![nub](https://user-images.githubusercontent.com/22778273/70170641-ed891e00-1681-11ea-82b9-6023c7a0fd4b.PNG)

## Version

CDN v4.6.0

## Describe the bug

The fallowing style options do not reflect bot bubble 
```
bubbleNubOffset: 'bottom',
bubbleNubSize: 10
```

## Steps to reproduce

Add these to options under styleoptions using CDN and observe the result. You should not see nub on the bot bubbles.

## Expected behavior

Should show bubble nubs on bot bubbles.

## Additional Information

After doing more tests it seems the problem happens with hero and adaptive cards (see the image).

![nub](https://user-images.githubusercontent.com/22778273/70182611-051fd100-1699-11ea-8062-6f342f5d4d70.jpg)

[Bug]

**Comment by arman-g** [comment] 2019-12-04 21:18
@corinagum I added more information about my findings.

**Comment by corinagum** [comment] 2019-12-04 21:53
ah! @arman-g your investigations are exactly what we needed :) I thought they weren't working for any from-bot activities. 

When implementing the bubblenub feature, the design decision was to *not* include attachments as having a bubblenub. This means that any kind of activity that is considered an attachment (carousel, adaptive card, image, herocard) will not show a nub, and is not intended to. As it is, this is not a bug, it's by design. ^^

However, I'm assuming you would like to include the bubblenub on attachments. I'm going to re-categorize this bug as an Enhancement request. If anyone else is looking for this behavior, please feel free to add a +1 below.

**Comment by arman-g** [comment] 2019-12-04 22:43
> ah! @arman-g your investigations are exactly what we needed :) I thought they weren't working for any from-bot activities.
> When implementing the bubblenub feature, the design decision was to not include attachments as having a bubblenub. This means that any kind of activity that is considered an attachment (carousel, adaptive card, image, herocard) will not show a nub, and is not intended to. As it is, this is not a bug, it's by design. ^^
> However, I'm assuming you would like to include the bubblenub on attachments. I'm going to re-categorize this bug as an Enhancement request. If anyone else is looking for this behavior, please feel free to add a +1 below.

Thanks for the update. I understand that it is by design but this is not solving my problem since we can't have bubble nubs show on some and not show for the others. This means I have to create it manually which defeats purpose of having this option. Not sure if this decision was made before adaptive cards came out but for sure it needs rethinking. Anyways I opt to this future, thank you.
+1

**Comment by compulim** [comment] 2020-03-06 20:32
Assigning to @DesignPolice.

Marc, can you consider this case when you are restyling Web Chat? Throwing some random thoughts, not really something I want, but things that might drive our directions.

- Should we have different bubble style for activity vs. attachments?
   - Bubble for activity could have lighter gray, and attachment is white
   - Bubble for activity is more round, while attachment is rectangular

**Comment by DesignPolice** [comment] 2020-03-06 20:41
Sure I can take a look at that... looking at all of it right now. If there are any other things we should look at let me know! @compulim

**Comment by v-kydela** [comment] 2020-04-24 20:45
I don't know why Web Chat would want to differentiate between text messages and attachments when it comes to bubble nubs. Web Chat v3 didn't. You might be interested to see this customer's issue: https://github.com/microsoft/BotFramework-WebChat/issues/2667

**Comment by Tiger519** [comment] 2020-04-24 21:50
Yes, that was my issue. I'm interested in this not only for the nub (I think it looks better), but also for the fact that in Web Chat v3 the attachment had it's own white box _inside_ the gray speech bubble with nub. Check out the screenshots in the SO issue Kyle linked above. I felt this was a much better UI. I'm actually trying to figure out how I can somehow replicate the old Web Chat v3 adaptive card host as I felt the UI was much better.

**Comment by droidriz** [comment] 2020-08-04 07:41
any updates on this?

**Comment by compulim** [comment] 2020-08-04 07:55
Sorry, we are not adding bubble nubs to attachments.

Attachments are not something the user/bot **mentioned**. Instead, they are **attached**.

Since it is not something "spoken", the bubble nub should not appear next to them.

**Closed by compulim** 2020-08-04 07:55 UTC
Labels: Backlog, Bot Services, Enhancement, customer-replied-to, customer-reported

**Comment by droidriz** [comment] 2020-08-04 08:10
@compulim  Thanks for replying :)
Appreciate all your efforts.

**Comment by compulim** [comment] 2020-08-04 08:23
@droidriz Thanks for understanding.

Be sure to check out the new "activity grouping" feature, it may give you what you need. 😉

Will add a nice sample soon.

![recording (30)](https://user-images.githubusercontent.com/1622400/89271077-138c0700-d5f1-11ea-9326-3cc3c047808e.gif)
