### ISSUE TITLE
Provide Location

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#64] opened 2016-10-13 23:20 UTC
WebChat might be able to provide the user's location if they so choose. This feature might be lower priority but just getting this on the books.

**Comment by amitbend** [comment] 2017-07-11 14:52
Any update @danmarshall ?
This can be very helpful.

**Comment by danmarshall** [comment] 2017-07-11 17:51
@amitbend no updates at this point.

**Comment by compulim** [comment] 2018-06-15 07:37
@amitbend I am closing this because dupe of #987. Let's track it over there.

Stay tuned, it's pretty high on our radar now.

**Closed by compulim** 2018-06-15 07:37 UTC
Labels: enhancement
