### ISSUE TITLE
Keyboard navigation issue when links/button in content - Intermittent

### ISSUE THREAD

**Issue by venkatx5** [microsoft/BotFramework-WebChat#3913] opened 2021-05-25 16:10 UTC
Getting intermittent focus issue when the content has button to expand / collapse the content. This makes navigation challenging for keyboard users.

## Screenshots
![image](https://user-images.githubusercontent.com/11777507/119529651-ebe47600-bd9f-11eb-98db-18ba642b8f54.png)

## Version
webchat es5 version 4.13.0
https://cdn.botframework.com/botframework-webchat/4.13.0/webchat-es5.js
Integrating the CDN version js directly on the page using script tag (No Iframe). Desktop Chrome Browser.

```
<meta name="botframework-directlinespeech:version" content="4.13.0">
<meta name="botframework-webchat:bundle:variant" content="full-es5">
<meta name="botframework-webchat:bundle:version" content="4.13.0">
<meta name="botframework-webchat:core:version" content="4.13.0">
<meta name="botframework-webchat:ui:version" content="4.13.0">
```

## Describe the bug
The virtual agent has adaptive card response with expand/collapse option button. When trying to navigate using up/down to select card and hit enter to set focus on the first element on the selected card, nothing happens. This issue is intermittent.

## Steps to reproduce

1. Deploy Web App Bot with adaptive cards.
2. Open the web app bot on browser.
3. Interact with the bot till the adaptive card response arrives using up/down arrow key.
4. Hit enter to set focus on first element (which should be the expand/collapse option).

## Expected behavior
After selecting the card and hit enter, The read more/read less button should be focused.

## Additional context
This issue is intermittent. The button getting focus sometimes, But sometimes it's not focus. Adaptive card json given below. The lengthy response has been stripped in the backend to show short version at first. Read more option shows the full content. Please advice if any change has to be done in this expand/collapse implementation.

```
{
  "type": "message",
  "serviceUrl": "http://localhost:56223",
  "channelId": "emulator",
  "from": {
    "id": "db8f84e0-b217-11eb-b23***********89",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "4dff8ba0-b246-11**************"
  },
  "recipient": {
    "id": "ffb569b4-b872-4ab2**************",
    "role": "user"
  },
  "locale": "en-US",
  "inputHint": "expectingInput",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "TextBlock",
            "id": "firstresponse",
            "text": "This is a sample response from the virtual agent. This is 2nd line for long response testing. This is 3rd line for long response testing. This is 4th line for long response testing. This is 5th line for long response testing. This is 6th line for long response testing. This is 7th line for long response testing...."
          },
          {
            "type": "TextBlock",
            "id": "secondresponse",
            "text": "This is a sample response from the virtual agent. This is 2nd line for long response testing. This is 3rd line for long response testing. This is 4th line for long response testing. This is 5th line for long response testing. This is 6th line for long response testing. This is 7th line for long response testing. This is 8th line for long response testing. This is 9th line for long response testing. This is 10th line for long response testing. ",
            "isVisible": false
          },
          {
            "id": "showmorebtns",
            "type": "ActionSet",
            "actions": [
              {
                "type": "Action.ToggleVisibility",
                "targetElements": [
                  {
                    "elementId": "firstresponse",
                    "isVisible": false
                  },
                  {
                    "elementId": "secondresponse",
                    "isVisible": true
                  },
                  {
                    "elementId": "showmorebtns",
                    "isVisible": false
                  },
                  {
                    "elementId": "hidemorebtns",
                    "isVisible": true
                  }
                ],
                "title": "Read more"
              }
            ]
          },
          {
            "id": "hidemorebtns",
            "type": "ActionSet",
            "actions": [
              {
                "type": "Action.ToggleVisibility",
                "targetElements": [
                  {
                    "elementId": "secondresponse",
                    "isVisible": false
                  },
                  {
                    "elementId": "showmorebtns",
                    "isVisible": true
                  },
                  {
                    "elementId": "firstresponse",
                    "isVisible": true
                  },
                  {
                    "elementId": "hidemorebtns",
                    "isVisible": false
                  }
                ],
                "title": "Read less"
              }
            ],
            "isVisible": false
          },
          {
            "type": "TextBlock",
            "text": "Does this answer your question?"
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "id": "Success",
            "data": {
              "IsSatisfied": "true",
              "UserAskedQuestion": "How are you today",
              "ResolvedIntent": "howareyou_general"
            },
            "iconUrl": "******************************"
          },
          {
            "type": "Action.Submit",
            "id": "Failure",
            "data": {
              "IsSatisfied": "false",
              "UserAskedQuestion": "How",
              "ResolvedIntent": "howare_you_general"
            },
            "iconUrl": "******************************"
          },          
          {
            "type": "Action.Submit",
            "id": "return",
            "data": "Main Menu",
            "title": "Main Menu"
          }
        ]
      }
    }
  ],
  "replyToId": "815ef170-b2******************************e",
  "id": "868a7d90-b******************************9ee29c2ede",
  "localTimestamp": "2021-05-11T16:19:13+05:30",
  "timestamp": "2021-05-11T10:49:13.961Z"
}
```

[Bug]

**Comment by corinagum** [comment] 2021-06-02 18:19
Duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/3798 Please visit for more information.

**Closed by corinagum** 2021-06-02 18:19 UTC
Labels: Bot Services, Bug, Support, customer-reported

**Comment by venkatx5** [comment] 2021-06-17 06:37
@corinagum This issue is not related to #3798 
Please tag appropriately and provide some solution.

**Comment by corinagum** [comment] 2021-06-19 01:03
Please answer the questions I asked above, and after confirmation I will request to reopen.
