### ISSUE TITLE
Direct Line channel writes out the CardAction value on first interaction

### ISSUE THREAD

**Issue by BeigeBadger** [microsoft/BotFramework-WebChat#2109] opened 2019-06-21 04:44 UTC
## Screenshots

![https://i.imgur.com/GGp9jNi.png](https://i.imgur.com/GGp9jNi.png)

## Version

ms-botchat.js

## Describe the bug

The very first click of a CardAction (Button) displays the CardAction Value immediately after the chatbot's response to the CardAction. It only happens with the very first CardAction interaction per session.

I am using HeroCards and the Postback ActionType, my value is a serialized JSON string.

![https://i.imgur.com/43G7icH.png](https://i.imgur.com/43G7icH.png).

## To Reproduce

1. Load page with embedded bot
2. Trigger waterfalldialog flow
3. Click on button
4. Value is posted into the chat, moves to next step
5. Click button on another card
6. Value is not posted into the chat, moves to next step.

## Expected behavior

The interaction with the first card per session does not post the Value into chat.

[Bug]

**Comment by tdurnford** [comment] 2019-06-21 18:04
Embedded Web Chat has not been migrated to v4 and is stilling using Web Chat v3.  Could you try out your bot on a basic v4 web page made by following our [sample 01.a](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.a.getting-started-full-bundle)? This is just to test if your errors are persisting to v4 of Web Chat. If so, we'll be able to investigate the problem and file this as a bug. Otherwise, my immediate fix recommendation would be to use v4 through CDN or MyGet until we get v4 available via embed, which will hopefully be in the upcoming weeks.

**Comment by BeigeBadger** [comment] 2019-06-21 21:57
@tdurnford thank you for the prompt response. I downloaded the sample and ran it successfully on my local machine using the config that it came with.

However, when I replaced the built in URL (https://webchat-mockbot.azurewebsites.net/directline/token
) with the URL for my bot (https://my-bot.azurewebsites.net/directline/token
) I get CORS issues. The documentation [linked](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication) in the file itself has examples of how to use the secret and token but all of the URLs begin with 'https://directline.botframework.com/v3/directline/' which seems to suggest v3 (of WebChat, Bot Framework, or the DirectLine API - of this I am not sure). So I investigated further down the page around how to get tokens and saw that there was a trustedOrigins parameter than can be passed into this request and it refers to "the Direct Line configuration page for you bot". My bot only has a single DirectLine site setup and that isn't event for the site that I am trying to host the bot on, and that site has the [Enhanced authentication options](https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/) toggle set to "Disabled", which I take to mean I shouldn't get CORS issues.

But the plot thickens, I am not the original developer who setup the DirectLine channel nor did the page setup for the bot. I talked to the original developer and he said:

> We're using Botjs: https://cdn.botframework.com/botframework-webchat/latest/botchat.js then initializing in script.

So what next? Thanks again for your help.

**Comment by tdurnford** [comment] 2019-06-21 23:11
@BeigeBadger The most current version of the DirectLine API is v3, and it is still used by the BotFramework and Web Chat even though they are on v4. 

The CORs error you're encountering is likely related to the token endpoint you have configured on your bot, not the request to https://directline.botframework.com/v3/directline/. I would take a look at this blog post on [Enable Cross-Origin Requests](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.2) for more details. 

It looks like you are using the correct CDN for your project. If you want to get a quick page up and running to test Web Chat v4 with your bot, you can add your Web Chat Secret to the html snippet below. It makes a simple HTTP request to /v3/directline/tokens/generate to get a token for your bot and passes it to Web Chat to initialize the conversation.

 ```html
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>WebChat</title>
  <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
  <style>
    html, body { height: 100% }
    body { 
      margin: 0;
      }

    #webchat {
      height: 100%;
    }

  </style>
</head>
<body>

  <div id="webchat" role="main"></div>

  <script>
    (async function() {

      const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', { 
        method: 'POST',
        headers: {
          'Authorization': `Bearer <WEB_CHAT_SECRET>`
        }
      });

      const { token } = await res.json();

      window.WebChat.renderWebChat({
      directLine: window.WebChat.createDirectLine({ token }),
    }, document.getElementById('webchat'));

    })().catch(err => console.log(err));
  
  </script>
</body>

```

**Comment by BeigeBadger** [comment] 2019-06-22 00:37
Thanks for that @tdurnford. I managed to get my bot talking using the above snippet. I can also confirm that the issue I was encountering where the action `Value` was being posted into the chat for the first card interaction per session no longer manifests itself.

I am using the correct CDN, I managed to pull out the following from the page source:

```
BotChat.App(
    {
        directLine: { secret: "secret-here" },
        user: { id: 'Guest' },
        bot: { name: 'Robot' },
        resize: 'detect'
    },
    document.getElementById("ac-ms-bot")
);
```

The value for "secret-here" is the secret from the DirectLine site that I mentioned earlier (it had the incorrect name against the site so I assumed it wasn't relevant). I don't get CORS errors on the production site, only locally - thanks for the article though.

Where to from here?

**Comment by tdurnford** [comment] 2019-06-22 03:22
@BeigeBadger Glad to hear the issue isn't persistent in Web Chat v4! 

It looks like your site is using Web Chat v3, which is also known as Bot Chat. Since Web Chat v3 is deprecated and is currently in sunset, I would recommend updating your site to use the newest version of Web Chat. Take a look at the [Migrating from Web Chat v3 to v4](https://github.com/microsoft/BotFramework-WebChat#migrating-from-web-chat-v3-to-v4) section in the read me and the Web Chat [samples](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples) for more details on getting started with Web Chat v4.

I'm guessing your REST API is configured to accept request from the main site but not from sites hosted locally, which makes sense since you don't want to overexpose your API. 

I'm closing this issue since it is not manifesting itself in Web Chat v4. The BotFramework Support Team monitors BotFramework and WebChat issues on StackOverflow, so if you need additional help with **how to** questions or getting started, I would recommend opening a question there - you seem to be pretty active on StackOverflow anyway.

**Closed by tdurnford** 2019-06-22 03:22 UTC
Labels: Bug, Pending, v3
