### ISSUE TITLE
Adaptive Card Render function for WebChat

### ISSUE THREAD

**Issue by kalykodu** [Microsoft/BotFramework-WebChat#467] opened 2017-05-18 18:25 UTC
Hi,

I am trying to use an adaptive card to add images on a button . Is there a render function for the webchat so that i can leverage that for the use case i am trying?

Thanks,
Kalyani

**Comment by danmarshall** [comment] 2017-05-18 23:53
Hi Kalyani, we are working on an integration with Adaptive Cards, please stay tuned for an upcoming PR.
Thanks!

**Comment by miscalencu** [comment] 2017-06-29 14:11
I see that Adaptive Cards have been implemented. But this is still not available in the sources available at https://unpkg.com/botframework-webchat, is this correct? Because I get a "[File of type 'application/vnd.microsoft.card.adaptive']" error using unpkg resources. Any idea when this will be updated?

**Comment by photodesignch** [comment] 2017-06-29 16:11
@miscalencu I believed that the adaptive cards integration is in the adaptivecards branch right now. It just hasn't merged into the master yet.

**Comment by PrasenjitSaha** [comment] 2017-06-30 11:29
@photodesignch can you please share the code base location?

**Comment by photodesignch** [comment] 2017-06-30 17:45
@PrasenjitSaha 

[Adaptive card branch](https://github.com/Microsoft/BotFramework-WebChat/tree/adaptivecards) has the most up-to-date adaptive cards' integration to webchat.  However, it's heavily depend on the adaptive card module in the node_module.  If you want to integrate the most up-to-date adaptive cards. You should go to [Adaptive Cards repo](https://github.com/Microsoft/AdaptiveCards) and build the newest adaptive cards module from there.  Then port into your webchat.

**Comment by Chitma** [comment] 2017-07-06 06:21
Hello All, 

I am implementing custom webchat for my bot. I have linked .css and .js files as shown in documentation by providing directline secret. My bot contains adaptive cards to be rendered but i get "[File of type 'application/vnd.microsoft.card.adaptive']" error could anyone please tell me am I doing it right? or is it something I am missing?

I have read some comments above but couldn't get it.

Thanks,
Manish Chitre.

**Comment by danmarshall** [comment] 2017-07-06 19:19
Hi @Chitma the latest release 0.10.8 may fix this for you. Can you get the latest version and try again?

**Comment by danmarshall** [comment] 2017-07-06 19:20
Hi @miscalencu the latest version 0.10.8 may fix this for you. Can you get the latest version and try again?

**Comment by miscalencu** [comment] 2017-07-09 00:09
I can confirm that everything is OK now. The card is displayed.

**Comment by rachelbransom** [comment] 2017-07-14 00:25
How can I go about getting the latest version 0.10.8? All my Microsoft.AdaptiveCards packages in Visual Studio say they are up to date (e.g. Microsoft.AdaptiveCards is at version 0.5.0)

**Comment by danmarshall** [comment] 2017-07-14 01:11
@rachelbransom if you are creating a web-based project you can get it by running `npm install botframework-webchat`. However it sounds like you may be in a C# project?

**Comment by rachelbransom** [comment] 2017-07-14 01:16
Yes, i'm writing a bot using .NET

**Comment by danmarshall** [comment] 2017-07-14 01:18
@rachelbransom - so then you are using the Iframe-based WebChat. I am working to get the latest WebChat bits up to the BotFramework site. I'm hoping it will be just a couple days.

**Comment by danmarshall** [comment] 2017-07-24 21:34
The Bot Framework is now hosting the latest version of the WebChat. Thanks all 👍

**Closed by danmarshall** 2017-07-24 21:34 UTC

**Comment by annevah** [comment] 2017-08-01 05:51
@danmarshall  I am using direct line and i am getting the same error [File of type 'application/vnd.microsoft.card.adaptive']. Please help me out :(
