### ISSUE TITLE
A way to override Localisation

### ISSUE THREAD

**Issue by Hatzman91** [microsoft/BotFramework-WebChat#2467] opened 2019-10-14 12:06 UTC
## Feature Request

I have found no way to override the localisation for example the "Type your message" in the SendBox. Because in the German version we want to use a more polite form of language.

![image](https://user-images.githubusercontent.com/26482488/66750037-a6ee2300-ee8b-11e9-8321-35e3e35770ab.png)

We want there to have "Verfassen Sie eine Nachricht".

Thanks :)

**Comment by tdurnford** [comment] 2019-10-14 15:21
This a duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/1833 which is being tracked with https://github.com/microsoft/BotFramework-WebChat/issues/1839.

**Comment by corinagum** [comment] 2019-10-14 16:38
Closing as a duplicate.

**Closed by corinagum** 2019-10-14 16:38 UTC
Labels: Bot Services, Duplicate, Enhancement, Pending, customer-replied-to, customer-reported
