### ISSUE TITLE
Directline Speech Sample unsuccessful Directline WebSocket connection

### ISSUE THREAD

**Issue by steps371** [microsoft/BotFramework-WebChat#3307] opened 2020-07-14 07:30 UTC
## Version
I'm using the 3. Speech example in the BotFramework-WebChat npm package. 

> Here are the versions of the npm packages I'm running:
```
<meta name="botframework-directlinespeech:version" content="4.9.1">
<meta name="botframework-webchat:bundle:variant" content="full">
<meta name="botframework-webchat:bundle:version" content="4.9.1">
<meta name="botframework-webchat:core:version" content="4.9.1">
<meta name="botframework-webchat:ui:version" content="4.9.1">
```

## Describe the bug

Our team has been struggling to activate directline speech in a webchat in our react examples, which prompted us to reproduce the error in a barebones bot-framework example. 

When adjusting the speech example to connect to a deployed bot instead of the mockbot, I receive an error (in the console) when clicking on the microphone to record speech, and the webchat freezes up.

## Steps to reproduce

1. Download BotFramework-WebChat repo
2. Replace the  the code in between `<script>` tags in 03.speech example with the following:
```
(async function() {
        const fetchCredentials = async () => {
            const res = await fetch("https://westus.api.cognitive.microsoft.com/sts/v1.0/issueToken", {
            headers: {"Ocp-Apim-Subscription-Key": "XXXX"},
            method: "POST"
            })

          if (res.status === 200) {
          const region = 'westus'
          const authorizationToken = await res.text()
          return {region, authorizationToken}
          } else {
          return (new Error('error!'))
          }

          return { authorizationToken, region };
        };

        // Create a set of adapters for Web Chat to use with Direct Line Speech channel.
        // Please refer to /packages/directlinespeech/src/createAdapters.js for list of supported options.
        const adapters = await window.WebChat.createDirectLineSpeechAdapters({
          fetchCredentials
        });

        // Pass the set of adapters to Web Chat.
        window.WebChat.renderWebChat(
          {
            ...adapters,          },
          document.getElementById('webchat')
        );

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.log({err}));
```
3. Run example with `npx serve`, navigate to `localhost:5000` and you should see this:

![image](https://user-images.githubusercontent.com/17024747/87395653-fe9ff300-c5b1-11ea-9355-a6de94ee3b05.png)

4. After clicking on the microphone, the webchat hangs on the following, and the following error is logged in the console

```
WebSocket connection to 'wss://westus.convai.speech.microsoft.com/api/v3?language=en-GB&format=simple&Authorization=XXXX-ConnectionId=XXX’ failed: Error during WebSocket handshake: Unexpected response code: 200
```

And in the network tab (visible even before pressing the microphone):

![image](https://user-images.githubusercontent.com/17024747/87396658-71f63480-c5b3-11ea-8d7a-da11a6f4c11c.png)

## Expected behavior

Following the directline speech webchat example, I would've expected recorded speech to be transcribed to text, and sent to the bot.

## Additional context

The speech resource and deployed bot works when configured on the bot-framework emulator, so the issue is likely not with the provisioned resources.

[Bug]

**Comment by compulim** [comment] 2020-07-16 18:01
I copied your code snippets into our `03.speech/a.direct-line-speech` sample by replacing the `fetchCredentials` part and it works.

1. What browsers and OS are you testing it on?
2. If on Windows, can you use Fiddler and see what's the HTTP response body on the request?
   - Browser network tab may not give you this information, you might need to use Fiddler instead

**Comment by EricDahlvang** [comment] 2020-07-27 18:18
@steps371 please respond to William's questions.  We would like to close this in a few days.

**Comment by steps371** [comment] 2020-07-28 18:51
Apologies for the delay in response

I experienced this issue on Mac Catalina in Both Chrome and Safari browsers. I believe a colleague was able to get the sample working on Windows.

Will investigate further tomorrow

**Comment by steps371** [comment] 2020-07-29 15:07
Still running into the same error.

OS:
macOS Catalina 10.15.4

Browsers:
Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)
Safari Version 13.1 (15609.1.20.111.8)

**Comment by steps371** [comment] 2020-08-06 11:11
Does anyone have any suggestions on what the possible issue might be? Still stuck on this

**Comment by peterinnesmsft** [comment] 2020-08-17 18:20
@compulim can you take a look and help with @steps371's latest question?

**Comment by compulim** [comment] 2020-08-18 03:59
@steps371 do you think this is dupe of https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221?

**Comment by steps371** [comment] 2020-08-18 05:51
@compulim, definitely.

**Comment by pavolum** [comment] 2020-08-31 18:08
This is a duplicate and is being tracked here: https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221

**Closed by pavolum** 2020-08-31 18:08 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported
