### ISSUE TITLE
[Accessibility] [Screen-Reader] Screen reader starts reading from beginning of chat on new message

### ISSUE THREAD

**Issue by agriniex** [microsoft/BotFramework-WebChat#3174] opened 2020-05-26 12:05 UTC
## Version
 NPM; 
meta name="botframework-directlinespeech:version" content="4.9.0"
meta name="botframework-webchat:bundle:variant" content="full"
meta name="botframework-webchat:bundle:version" content="4.9.0"
meta name="botframework-webchat:core:version" content="4.9.0"
meta name="botframework-webchat:ui:version" content="4.9.0"

## Describe the bug

Some screen reader combinations read whole chat from start on new message. Investigated following combinations

Chrome Version 81.0.4044.138 (Official Build) (64-bit) + NVDA 2020.1 - **Reading from start (not as expected)**
Chrome Version 81.0.4044.138 (Official Build) (64-bit)  + Chrome VOX plugin - Not reading from start (as expected)
Mozilla Firefox 76.0.1 (64-bit) + NVDA 2020.1 Not reading from start (as expected)
MS Edge Version 83.0.478.37 (Official build) (64-bit) + NVDA 2020.1 **Reading from start (not as expected)**
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) + VoiceOver (Mac)  **Reading from start (not as expected)**

## Steps to reproduce

- Open webchat with + enable screen reader
- Send any message to webchat 

## Expected behavior
Screen readers read only latest messages from webchat.

## Actual behavior
There are some browsers+reader combinations that read the whole webchat from beginning when new messages appear in section.

## Additional context
Tested both on custom webchat integration and on this official demo standalone version [here](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/e.host-with-react/)
[Bug]

**Comment by cimbis** [comment] 2020-05-26 12:12
Currently am looking into WebChat a11y issues as well and am experiencing similar behaviour.

**Comment by gabog** [comment] 2020-05-26 18:32
Hi @cwhitten, can you take a look at this one? 
Thanks

**Comment by gabog** [comment] 2020-05-29 18:23
Hi, this seems to be related to [this issue in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1067257), are you able to reproduce the problem in Firefox? If not, we will need to wait for the chromium fix to address it.

Let us know how it goes with firefox.

Thanks

**Comment by corinagum** [comment] 2020-09-18 19:39
Adding this to the repro list since the issue in chromium appears to have been addressed.

**Comment by corinagum** [comment] 2020-10-09 18:41
I tested this on Chrome x NVDA and Edge Canary x Narrator, and I'm no longer reproducing this bug. Closing as resolved.

**Closed by corinagum** 2020-10-09 18:41 UTC
Labels: Area: Accessibility, Bot Services, Bug, ExemptFromDailyDRIReport, customer-replied-to, customer-reported, needs-repro, needs-scheduling
