### ISSUE TITLE
Using speech: Mismatch between input box and what gets sent

### ISSUE THREAD

**Issue by tiloc** [microsoft/BotFramework-WebChat#736] opened 2017-10-17 12:59 UTC
I am using the Web Chat with speech input through Bing Speech. I am oftentimes experiencing a situation where the text that I speak and which is dictated into the "Type your message..." box differs significantly from what is later being sent to the bot. For instance, I say "get checklist". The input box shows "get checklist". But what gets sent to my bot is "Goodbye". What could be causing this? Is there some spell checker or grammar checker that I can disable? Typically what shows up in the text box is much closer to what I want than what is sent to the bot.

**Comment by danmarshall** [comment] 2017-10-17 18:28
@shahidkhuram do you know what could be causing this?

**Comment by shahidkhuram** [comment] 2017-10-21 18:18
With speech recognition sometimes the hypothesis text you see can change when the recognition is finalized but usually the final result is phonetically similar to the hypothesis. I wouldn't expect "get checklist" to morph in to "goodbye".

I haven't seen this  myself and don't have any theories at the moment. Looking at the network trace should narrow down the issue area. You can look at the response that was received from cognitive services which contains the recognized text and compare that to the request that was sent to the bot.

**Comment by iamgraviteja** [comment] 2018-10-23 06:10
@danmarshall @compulim any updates on this issue? I'm facing this issue many times. I say "Find a part", it shows the same in input but, sending as "Find a path".

**Comment by corinagum** [comment] 2018-11-28 23:15
It looks like this is functioning as designed. As a workaround, should we be waiting for user confirmation before sending the message? @mewa1024 @DesignPolice

**Comment by corinagum** [comment] 2020-03-02 19:51
Closing, as Bing Speech has been deprecated. If Cognitive Services is showing a similar problem, please file a new issue in the appropriate rep.

**Closed by corinagum** 2020-03-02 19:51 UTC
Labels: Backlog, Design needed, Enhancement, Speech, Triaged
