### ISSUE TITLE
Image not showing for AudioCard

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#713] opened 2017-10-04 00:04 UTC
The [AudioCard schema](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.audiocard?view=botbuilder-3.8) has an **Image** property but it does not appear to be rendered in Web Chat.

**Comment by compulim** [comment] 2017-12-12 00:45
Dupe of #793

**Closed by compulim** 2017-12-12 00:45 UTC
