### ISSUE TITLE
Welcome Message from Bot language

### ISSUE THREAD

**Issue by 20112077** [Microsoft/BotFramework-WebChat#572] opened 2017-07-12 11:01 UTC
Hello,
 I send the user a welcome message when the conversation is updated. The string for this message comes from a ressource file. The message is available in English and German, but the bot always sends the welcome message in English. With the following messages the bot always uses the right language, depending on the browser settings. Is it possbile to also get the first message in the right language?

**Comment by billba** [comment] 2017-07-12 14:35
I would guess the problem is that the user locale (like the user name) is only sent to the bot with a user message. @dandriscoll it would be nice to send these when starting the conversation.

As a workaround, you can use the [backchannel](https://github.com/Microsoft/BotFramework-WebChat/#the-backchannel) to send the an event containing the locale to the bot.

**Comment by GaiaAnn** [comment] 2017-07-14 02:25
@20112077 Hi,
Can you send the welcome message on web chat ?

**Comment by 20112077** [comment] 2017-07-14 08:26
@GaiaAnn Hi,
The welcome message is working on webchat, I send the message with this code:
`  else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
                if (message.MembersAdded.Any(o => o.Id == message.Recipient.Id))
                {
                    var reply = message.CreateReply("Welcome");
                    ConnectorClient connector = new ConnectorClient(new Uri(message.ServiceUrl));
                    await connector.Conversations.ReplyToActivityAsync(reply);
                }
            }`

**Comment by GaiaAnn** [comment] 2017-07-15 13:31
Thanks for your reply. 
I'll try this!

**Comment by coronag** [comment] 2018-01-05 15:44
Same problem for me. Sending the welcome message is possible with ConversationUpdate but only in one language. 

@billba : using backchannel didn't help me because I didn't managed to send a response message to a backchannel incoming event, is this something possible ? And if I only try to use the backchannel event to store the user language in context, it's not working either as the ConversationUpdate is happening before the backchannel activity that set the language. 

Did somebody find something to have a localized welcome message? 
Thanks.

**Comment by 20112077** [comment] 2018-01-05 16:23
@coronag  you can try this:
```
   else if (activity.Type == ActivityTypes.Event && activity.Name == "setLanguage")
            {
                if(activity.Value.ToString().ToLower() == "en")
                {
                    language = CultureInfo.GetCultureInfo("EN");
                }
                else
                {
                    language = CultureInfo.GetCultureInfo("DE");
                }
                await SayHi(activity);
            }
```
`private async Task SayHi(Activity message)
        {
            Thread.CurrentThread.CurrentUICulture = language;
            var reply = message.CreateReply();
            var heroCard = new ThumbnailCard();
            heroCard.Title = Resources.Text
            heroCard.Text = Resources.Text1;
            heroCard.Images = new List<CardImage> { new CardImage("url to Image") };
            var attachment = heroCard.ToAttachment();
            reply.Attachments.Add(attachment);
            ConnectorClient connector = new ConnectorClient(new Uri(message.ServiceUrl));
            await connector.Conversations.ReplyToActivityAsync(reply);
            return;
        }`

**Comment by coronag** [comment] 2018-01-05 17:07
@20112077 thanks for your response. Just tried what you said on an event activity but the response never come back to the bot. The network response is only the same as without the "SayHi" and looks like this : 
{
  "id": "............"
}

In fact, I have also already tried something similar but without a card (just a simple text response).... but I never managed to get something working on "event".... I can't make a response from the bot. Any idea ?

Many thanks.

**Comment by coronag** [comment] 2018-01-05 17:10
Thanks !
Thumbnail card seems to work, is it possible to do the same without a card, only text ?

**Comment by corinagum** [comment] 2018-11-28 22:37
Closing, can be tracked over on #1371

**Closed by corinagum** 2018-11-28 22:37 UTC
Labels: Enhancement
