### ISSUE TITLE
[Direct Line Speech] Investigate supporting sovereign cloud

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3377] opened 2020-08-03 20:14 UTC
## Feature Request

In Direct Line Speech [`packages/directlinespeech/src/createAdapters.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/directlinespeech/src/createAdapters.js#L37), I think in addition of `region`, we need to support hostname.

Code excerpt of today:

```js
const { authorizationToken, directLineToken, region, subscriptionKey } = await resolveFunctionOrReturnValue(
  fetchCredentials
);
```

[Enhancement]

**Comment by corinagum** [comment] 2020-10-19 18:07
Assigning to @trrwilson per @nisheetjain

**Comment by corinagum** [comment] 2021-01-14 18:26
Closing as dupe of #3666 Please take conversation over there.

**Closed by corinagum** 2021-01-14 18:26 UTC
Labels: Area: Direct Line Speech, P1, backlog, feature-request
