### ISSUE TITLE
[WebChat Carousel] doesn't display right scroll button

### ISSUE THREAD

**Issue by GaiaAnn** [Microsoft/BotFramework-WebChat#567] opened 2017-07-11 07:04 UTC
## System Information (Required)
* SDK Language: .NET/C# 
* SDK Version: 3.8.2
* Development Environment: LOCALHOST

## Issue Description
I used the standard Bot Framework WebChat channel to get an IFRAME of mybot and embeded in my website.
This is my Carousel. It doesn't show the right button.

<img width="693" alt="2017-07-10 10 32 40" src="https://user-images.githubusercontent.com/17616235/28001222-9bcb466a-655d-11e7-8072-295faf6ed292.png">

So, I go to see iframe's code and I figure out the problem.
I change width to 500px then everything works fine.
But I can't modify iframe's code.

```` html
<!-- react-empty: 338 -->
<div class="wc-carousel" style="width: 500px;">
````

After I change the width it looks like this:

<img width="544" alt="2017-07-10 10 33 15" src="https://user-images.githubusercontent.com/17616235/28001345-6366e774-655e-11e7-96c1-8be8c63d76c2.png">

Hope anyone can help me to fix this problem.

**Comment by danmarshall** [comment] 2017-07-11 07:07
Can you please share the JSON of your message which contains the carousel?

**Comment by GaiaAnn** [comment] 2017-07-11 07:24
```json
{
  "type": "message",
  "timestamp": "2017-07-11T07:21:05.414Z",
  "localTimestamp": "2017-07-11T15:21:05+08:00",
  "serviceUrl": "http://127.0.0.1:10832",
  "channelId": "emulator",
  "from": {
    "id": "ng4h8h409lcl9dm3",
    "name": "Bot"
  },
  "conversation": {
    "id": "c9ih7kf9mjef3cl0dc"
  },
  "recipient": {
    "id": "default-user"
  },
  "attachmentLayout": "carousel",
  "membersAdded": [],
  "membersRemoved": [],
  "locale": "zh-TW",
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "601會議室(A館 6人)",
        "subtitle": "room_601@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[1A]07月19日13:00",
            "value": "1A"
          },
          {
            "type": "imBack",
            "title": "[1B]07月20日09:00",
            "value": "1B"
          },
          {
            "type": "imBack",
            "title": "[1C]07月21日09:00",
            "value": "1C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "507會議室(E館 5人)",
        "subtitle": "room_507@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[2A]07月18日13:00",
            "value": "2A"
          },
          {
            "type": "imBack",
            "title": "[2B]07月19日09:00",
            "value": "2B"
          },
          {
            "type": "imBack",
            "title": "[2C]07月24日13:00",
            "value": "2C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "506會議室(E館 5人)",
        "subtitle": "room_506@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[3A]07月14日15:00",
            "value": "3A"
          },
          {
            "type": "imBack",
            "title": "[3B]07月17日09:00",
            "value": "3B"
          },
          {
            "type": "imBack",
            "title": "[3C]07月20日09:00",
            "value": "3C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "501會議室(A館 5人)",
        "subtitle": "room_501@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[4A]07月13日09:00",
            "value": "4A"
          },
          {
            "type": "imBack",
            "title": "[4B]07月19日09:00",
            "value": "4B"
          },
          {
            "type": "imBack",
            "title": "[4C]07月24日13:00",
            "value": "4C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "602會議室(走廊 6人)",
        "subtitle": "room_602@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[5A]07月12日13:00",
            "value": "5A"
          },
          {
            "type": "imBack",
            "title": "[5B]07月13日09:00",
            "value": "5B"
          },
          {
            "type": "imBack",
            "title": "[5C]07月17日13:00",
            "value": "5C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "502會議室(A館 5人)",
        "subtitle": "room_502@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[6A]07月13日15:30",
            "value": "6A"
          },
          {
            "type": "imBack",
            "title": "[6B]07月14日13:00",
            "value": "6B"
          },
          {
            "type": "imBack",
            "title": "[6C]07月20日15:30",
            "value": "6C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "協志會議室-舞蝶館",
        "subtitle": "room_xz_01@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[7A]07月14日09:00",
            "value": "7A"
          },
          {
            "type": "imBack",
            "title": "[7B]07月17日15:00",
            "value": "7B"
          },
          {
            "type": "imBack",
            "title": "[7C]07月18日13:00",
            "value": "7C"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "505會議室(E館 5人)",
        "subtitle": "room_505@xxx.com.tw",
        "text": "",
        "images": [],
        "buttons": [
          {
            "type": "imBack",
            "title": "[8A]07月14日14:30",
            "value": "8A"
          },
          {
            "type": "imBack",
            "title": "[8B]07月17日09:00",
            "value": "8B"
          },
          {
            "type": "imBack",
            "title": "[8C]07月18日13:00",
            "value": "8C"
          }
        ]
      }
    }
  ],
  "entities": [],
  "replyToId": "52494hh87m3d8kie1c",
  "id": "45i11ca1f14a394kac"
}
```

**Comment by danmarshall** [comment] 2017-07-12 23:00
Thanks @GaiaAnn . I could not reproduce the error. Is this the first message in the chat? Perhaps there is a previous message that is not word-wrapping and forcing a wide layout?

**Comment by GaiaAnn** [comment] 2017-07-13 07:38
No this is not the first message.We have two message without attachments before Carousel.

**Comment by danmarshall** [comment] 2017-07-13 08:20
Ok, can you tell me:
* Is this on Localhost? If so, is this in the emulator?
* Is this in the Iframe from BotFramework?
  * If so, what is your bot Id?
  * can you tell me how can I get to the carousel?
  * which browser is this?
  * what type of page is hosting the iframe?

**Comment by GaiaAnn** [comment] 2017-07-13 08:53
- Is this on Localhost? If so, is this in the emulator?
    * I had test on Localhost too. In emulator it works fine.
    * I also test on Server.
- Is this in the Iframe from BotFramework? If so, what is your bot Id?
    * Yes, id is **FB_Conn**
    * You can use my web chat here(key any word) :https://tdd-2012-2/webchat/
    * I use Safari & Chrome. Both not working.
    * html

**Comment by GaiaAnn** [comment] 2017-07-13 08:58
My code in **RootDialog.cs**
Just create the same Hero card.

```` C#
public async Task StartAsync(IDialogContext context)
        {
            context.Wait(ResumeAfter);
        }

        public async Task ResumeAfter(IDialogContext context, IAwaitable<object> result)
        {
            var resultMessage = context.MakeMessage();
            resultMessage.Attachments = new List<Attachment>();
            resultMessage.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            resultMessage.Attachments.Add(BuildHeroCard().ToAttachment());
            resultMessage.Attachments.Add(BuildHeroCard().ToAttachment());
            resultMessage.Attachments.Add(BuildHeroCard().ToAttachment());
            resultMessage.Attachments.Add(BuildHeroCard().ToAttachment());
            await context.PostAsync(resultMessage);

            context.Done<object>(null);
        }

        public HeroCard BuildHeroCard()
        {
            HeroCard card = new HeroCard()
            {
                Title = "Hero Card",
                Subtitle = "Hero",
                Text = "This is hero card",
                Images =  new List<CardImage>() { new CardImage(RESOURCE_IMAGE) },
                Buttons = new List<CardAction>()
                {
                    new CardAction(ActionTypes.ImBack, "讚123123123123123123", value:"Like"),
                    new CardAction(ActionTypes.ImBack, "爛1231231231231231231", value:"Unlike"),
                }
            };
            return card;
        }
````

*Thank you for your prompt  reply !*

**Comment by reyesrico** [comment] 2017-07-14 00:12
@GaiaAnn another couple of questions:
1. Which browser are you using?
2. Are you changing the width (CSS) from the iFrame or any other outside div?

**Comment by GaiaAnn** [comment] 2017-07-14 01:56
Hi @reyesrico

1. **Safari** & **Chrome**
2. Yes. But the right button still not working if I remove all css.
3. This is not happen only in my web chat . It also happened in bot framework's test web chat.
4. It's very weird. I try it in bot framework's test web chat today.It shows right button at the first time. After I refresh my page, button disappear again !
<img width="300" alt="2017-07-14 9 50 03" src="https://user-images.githubusercontent.com/17616235/28194996-493b267a-687a-11e7-805e-ff1fdde0c372.png">

**Comment by danmarshall** [comment] 2017-07-14 02:06
Hi @GaiaAnn - Safari & Chrome - on a Mac or PC? I'm guessing Mac since Safari on PC is no longer supported :)

**Comment by GaiaAnn** [comment] 2017-07-14 02:09
Yes I'm using **Mac**. But my friend use PC also have the same problem.
So, you test my web chat also can see the right button?
https://tdd-2012-2/webchat/

**Comment by danmarshall** [comment] 2017-07-14 02:11
The URL https://tdd-2012-2/webchat/ is not accessible to me. I can repro your error on a Mac. It works correctly on my PCs.

**Comment by GaiaAnn** [comment] 2017-07-14 02:14
Sorry my bad.
This URL you can try again https://tdd-2012-2.gss.com.tw/webchat/

**Comment by cimpoesub** [comment] 2017-08-09 06:29
Hello.

I am having the same issue as above. The right arrow out of bounds and not visible. Scrolling with the mouse wheel/touchpad_swipe works, just the button is not visible. On windows, all browsers.

Have you found any solution for the problem yet?

**Comment by danmarshall** [comment] 2017-08-09 20:07
@compulim - can you take a look at this?

**Comment by punitganshani** [comment] 2017-08-31 00:49
+1 facing this same issue, any quick fix on recommended width to make it work on Chrome/IE?

**Comment by UtkarshBehre** [comment] 2017-09-04 05:41
I have the same issue as above. Right arrow does not show in both the azure test chat and web channel as well. Is there a fix for this out yet?

**Comment by UtkarshBehre** [comment] 2017-09-08 08:44
Please provide any updates on this issue if possible.

**Comment by cimpoesub** [comment] 2017-09-08 09:05
The issue still manifests itself. Nothing seems to have changed from the node module's side. I have not found any workaround so far.

**Comment by pavei** [comment] 2017-10-07 20:14
i'm getting the same problem!

**Comment by pavei** [comment] 2017-10-07 21:33
My workaround was, on Carousel.tsx i fixed the width to a size smaller then container. Root offset is larger than the webchat container (400px) fixed on iframe.

```
 width 784
 root offsetwitdh 440

```
    private updateContentWidth() {
        //after the attachments have been rendered, we can now measure their actual width
        const width = this.props.size.width - this.props.format.carouselMargin;

        console.log("width", width);
        //important: remove any hard styling so that we can measure the natural width
        this.root.style.width = '';

        console.log("root offsetwitdh", this.root.offsetWidth);
        //now measure the natural offsetWidth
         if (this.root.offsetWidth > width) {
            // the content width is bigger than the space allotted, so we'll clip it to force scrolling
            this.root.style.width = width.toString() + "px";
            // since we're scrolling, we need to show scroll buttons
            this.hscroll.updateScrollButtons();
         }else{
             this.root.style.width = 339+ "px";
             // since we're scrolling, we need to show scroll buttons
             this.hscroll.updateScrollButtons();
         }

    }

**Comment by VishalWaman** [comment] 2017-12-13 07:25
+1

**Comment by pratyushdhanuka** [comment] 2018-07-27 08:19
Further debugging a bit, i found out that `this.root.offsetWidth` sometimes gives incorrect values for carousel, likely when we have only 2 elements
because of that the scroll function does not trigger

**Comment by pratyushdhanuka** [comment] 2018-07-27 08:30
Could the above be happening if the images are not loaded before we do this calculations ?
once image is loaded, the window resizes but it dont call the update function again

**Comment by pratyushdhanuka** [comment] 2018-07-27 11:57
so after going through hours tying to understand how to call the element's updateComponentWidth() when image loads, i did a hot fix instead

The hack was 
for hero cards, i added a css to have a minimum width of 175px, in botchat.css file
works for my bots because iframe width never crosses 400px for our chatbots and my carousel has a upper limit for 320

you can custom set the width depending on your application, until the dev fixes the bug and calls the above function when image inside cards are finished loading

**Comment by corinagum** [comment] 2019-05-01 00:04
Closing since this is a v3 bug, which is in sunset.

**Closed by corinagum** 2019-05-01 00:04 UTC
Labels: Backlog, Bug, Triaged, v3
