### ISSUE TITLE
Using runkit.com for BOTFramework Message Endpoint

### ISSUE THREAD

**Issue by bhanu2507** [Microsoft/BotFramework-WebChat#544] opened 2017-07-03 11:26 UTC
```
var botbuilder = require('botbuilder');

var connector = new botbuilder.ChatConnector({
    appId: <insert app id>,
    appPassword: <insert app password>
});

var bot = new botbuilder.UniversalBot(connector, function (session) {
    session.send("You said: %s", session.message.text);
});

exports.endpoint = function (request, response) {
var listener = connector.listen();
        if (request.method == 'POST') {
        var body = '';
        request.on('data', function (data) {
            body += data;
            // Too much POST data, kill the connection!
            // 1e6 === 1 * Math.pow(10, 6) === 1 * 1000000 ~~~ 1MB
            if (body.length > 1e6)
                request.connection.destroy();
        });
        
        request.on('end', function () {
        var post = JSON.parse(body);
        var reqWrapper = {
            body: post,
            headers: request.headers
        };
        var statusCode;
        var resWrapper = {
            status: (code) => {
                statusCode = code;
            },
            end: () => {
                return(null, { statusCode: statusCode });
            }
        };
        listener(reqWrapper, resWrapper);
        });
}
}
```

**Comment by billba** [comment] 2017-07-03 13:19
What is the issue?

**Comment by bhanu2507** [comment] 2017-07-03 13:31
Errors in channel health but code works fine with skype channel



​

**Comment by billba** [comment] 2017-07-03 15:25
Okay so if you'd like some help on this issue then you have to be more expansive. Your original report doesn't even mention errors. What errors are you seeing? I'm not familiar with runkit.com, so you might need to fill in some gaps there.

**Comment by nwhitmont** [comment] 2017-07-03 17:20
@billba - duplicate of https://github.com/Microsoft/BotBuilder/issues/3075

**Closed** 2017-07-03 17:23 UTC
