### ISSUE TITLE
getting 'â€™' instead of APOSTROPHE(') in bot chat window

### ISSUE THREAD

**Issue by RachaRatan** [Microsoft/BotFramework-WebChat#695] opened 2017-09-20 10:29 UTC
I am using embedded chat window which is downloaded from github.
I have built the downloaded file and build it. After build it i got botcht.js and botcht.css.
I have taken these files and created on html file by referring those two files.
Now everything is working fine. am able to chat based on my requirement.
But when I see the response in chat window there I am getting 'â€™' instead of APOSTROPHE(') all the time
Why am getting the response with 'â€™' instead of APOSTROPHE(').
Can anybody help me to fix this.

**Comment by danmarshall** [comment] 2017-09-20 16:44
Hi @RachaRatan this is a duplicate of #622 can you please see this issue for details.

**Closed by danmarshall** 2017-09-20 16:44 UTC
