### ISSUE TITLE
Warning on react checkproptypes activity.timestamp

### ISSUE THREAD

**Issue by leolorenzoluis** [microsoft/BotFramework-WebChat#2595] opened 2019-11-14 04:22 UTC
## Version 4.6.0/master

1. Checkout tag/v4.6.0 or master
2. Build all packages
3. Reference the bundled dist
```
VM13397 checkPropTypes.js:20 Warning: Failed prop type: The prop `activity.timestamp` is marked as required in `Timestamp`, but its value is `undefined`.
    in Timestamp (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in WebChatConnectedComponent (created by StackedLayout)
    in div (created by StackedLayout)
    in div (created by StackedLayout)
    in div (created by StackedLayout)
    in StackedLayout (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in WebChatConnectedComponent (created by BasicTranscript)
    in li (created by BasicTranscript)
    in ul (created by BasicTranscript)
    in Composer (created by BasicTranscript)
    in div (created by Panel)
    in Panel (created by Context.Consumer)
    in _default (created by BasicTranscript)
    in div (created by BasicTranscript)
    in BasicTranscript (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in WebChatConnectedComponent (created by Composer)
    in div (created by FocusBox)
    in FocusBox (created by Composer)
    in Composer (created by Context.Consumer)
    in Composer
    in Unknown (created by ConnectFunction)
    in ConnectFunction (created by ConnectedComposerWithStore)
    in Provider (created by ConnectedComposerWithStore)
    in ConnectedComposerWithStore (created by BasicWebChat)
    in BasicWebChat (created by FullReactWebChat)
    in FullReactWebChat
```

## Expected behavior
No warnings present

**Comment by tdurnford** [comment] 2019-11-14 18:28
@leolorenzoluis this issue seems to be resolved in master.

It's worth noting the timestamp property is marked as required in the [`Timestamp`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Activity/Timestamp.js) component; however, if the property is falsy, we just return false so it's not actually required. I'm pretty sure we added this check for an issue with the emulator. 

```javascript
const Timestamp = ({ activity: { timestamp }, className }) => {
...
  if (!timestamp) {
    return false;
  }
...
}
```

We should update the `propTypes` to reflect this behavior. @compulim @corinagum thoughts?

**Comment by compulim** [comment] 2019-11-14 19:44
@tdurnford I prefer to patch the activity to have `timestamp` by timestamping it on `incomingActivity` saga. Thoughts?

Upside: there will always be a timestamp and the order of activities are mostly correct.
Downside: if some activities have server timestamp on, clockskew may bring them out of order.

**Comment by leolorenzoluis** [comment] 2019-11-15 03:57
@tdurnford I don't think this is resolve in master, I checked out master yesterday and bundled it. I get the warnings when I use the bundled output. This is not with the emulator, this is just direct web chat.

**Comment by tdurnford** [comment] 2019-11-15 17:13
@leolorenzoluis Can you add the bot code you are using that triggers the warning message? I'm not able to reproduce your error.

**Comment by leolorenzoluis** [comment] 2019-11-20 19:32
@tdurnford I still get the same error. 
1. I checked out master. 
2. Run npm run build at the root project
3. Grab webchat-instrumented.js from packages/bundle/dist
4. Create a simple index.html with a reference to that script.

**Comment by tdurnford** [comment] 2019-11-20 19:50
Are you using MockBot or your own bot? What is the activity that is causing the issue? If I strip out the timestamp from incoming activities I can reproduce the issue; otherwise, I'm not getting an error.

**Comment by leolorenzoluis** [comment] 2019-11-20 20:21
I'm using my own bot.  If I use the bundled src from CDN then I don't get any errors. No code changes.

**Comment by tdurnford** [comment] 2019-11-20 20:39
Can you provide some additional details about your bot so I can debug this issue further? Are you using the Javascript or the C# BotBuilder SDK? What version of the SDK are you using? Can you add the bot code that is causing the timestamp issue in Web Chat?

**Comment by leolorenzoluis** [comment] 2019-11-20 20:44
I'm using the following code
```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Full-featured bundle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--
      This CDN points to the latest official release of Web Chat. If you need to test against Web Chat's latest bits, please refer to pointing to Web Chat's MyGet feed:
      https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits
    -->
    <!-- <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script> -->
    <script src="/webchat-instrumented.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }
      body {
        margin: 0;
      }
      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      async function fetchJSON(url, options = {}) {
        const res = await fetch(url, {
          ...options,
          headers: {
            ...options.headers,
            accept: 'application/json'
          }
        });
        if (!res.ok) {
          throw new Error(`Failed to fetch JSON due to ${res.status}`);
        }
        return await res.json();
      }
      async function postData(url = '', data = {}) {
        console.log('Posting data');
        // Default options are marked with *
        const response = await fetch(url, {
          method: 'POST', // *GET, POST, PUT, DELETE, etc.
          mode: 'cors', // no-cors, *cors, same-origin
          cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
          credentials: 'same-origin', // include, *same-origin, omit
          headers: {
            'Content-Type': 'application/json'
            // 'Content-Type': 'application/x-www-form-urlencoded',
          },
          redirect: 'follow', // manual, *follow, error
          referrer: 'no-referrer', // no-referrer, *client
          body: JSON.stringify(data) // body data type must match "Content-Type" header
        });
        return await response.json(); // parses JSON response into native JavaScript objects
      }

      (async function() {
        // const { token, conversationId } = await postData(
        //   'http://localhost:3000/directline/conversations'
        // );
        // console.log(`Token: ${token}. Conversation Id: ${conversationId}`);
        // In this demo, we are using Direct Line token from MockBot.
        // Your client code must provide either a secret or a token to talk to your bot.
        // Tokens are more secure. To learn about the differences between secrets and tokens
        // and to understand the risks associated with using secrets, visit https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0

        const store = WebChat.createStore(
          {},
          ({ dispatch }) => next => action => {
            console.log(action);
            return next(action);
          }
        );
        window.store = store;
        window.WebChat.renderWebChat(
          {
            sendTimeout: 30000,
            userID: '12345',
            store,
            directLine: window.WebChat.createDirectLine({
              domain: 'http://localhost:3000/directline',
              token: 'token'
            })
          },
          document.getElementById('webchat')
        );
        window.botchatDebug = true;
        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>
```

In combination of offline-directline package from npm for mocking directline. Other than that, nothing else. The bot responds back the activities just fine. It's just the warning on the client.

**Comment by tdurnford** [comment] 2019-11-20 20:50
Is the bot just an echo bot? This is most likely an issue with Offline-DirectLine not adding the timestamps correctly.

**Comment by leolorenzoluis** [comment] 2019-11-20 20:51
Yeah just a simple bot. Well, if that's even true then why don't I get warnings if I use the CDN version without changing anything on the code? I explicitly return a timestamp too from the response

**Comment by tdurnford** [comment] 2019-11-20 20:55
Can you clarify what you mean by "I explicitly return a timestamp too from the response?"

**Comment by leolorenzoluis** [comment] 2019-11-21 01:56
I hijacked the directions and explicitly turned a timestamp property on
activities

**Comment by tdurnford** [comment] 2019-12-02 22:36
@leolorenzoluis It sounds like we are going to patch the timestamp on incoming activities if it's missing.

**Comment by leolorenzoluis** [comment] 2019-12-03 00:18
@tdurnford But the timestamp is not missing in this case.

**Comment by cwhitten** [comment] 2020-01-09 23:08
@leolorenzoluis if the warning is saying that the timestamp field on the activity is undefined when it should not be, are you sure the timestamp is not missing?

**Comment by leolorenzoluis** [comment] 2020-03-26 19:47
@cwhitten Yes I'm sure it's not undefined.

**Comment by lzc850612** [comment] 2020-10-05 18:41
Closing due to inactivity.

**Closed by lzc850612** 2020-10-05 18:41 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported, front-burner
