### ISSUE TITLE
bug: Provide more context when links open in a new window/tab [screen reader accessibility]

### ISSUE THREAD

**Issue by nfreear** [microsoft/BotFramework-WebChat#3659] opened 2021-01-07 16:57 UTC
Hi,

 * Relates to :~ #3655.

## Version

 * WebChat.js version :~ 4.10.1;
 * JS :~ https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js;

## Describe the bug

As a screen reader user, when I follow a link from within a _WebChat_-based Chat-bot, it is set to open in a new window/tab in my browser, which will confuse me and mean that my _Back_ button doesn't work.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

I need extra text (_visually hidden_) within the link, warning me that the link will open in a new window. For example:

```html
<div id="webchat">

    <a target="_blank" href="...">
        Find out more about learning disabilities
        <span class="sr-only"> Opens in a new window</span>
    </a>

</div>
```

CSS example - [twbs/bootstrap ~ _visually-hidden.scss](https://github.com/twbs/bootstrap/blob/main/scss/mixins/_visually-hidden.scss):

```css
.sr-only,
.visually-hidden {
    position: absolute;
    width: 1px;
    /* ... */
}
```

I suggest that this should be implemented in [`renderMarkdown.js`](https://github.com/microsoft/BotFramework-WebChat/blob/v4.11.0/packages/bundle/src/renderMarkdown.js#L64-L67).

I'm currently investigating a possible implementation.

## Additional context

Yours,

Nick

[Bug]

**Comment by gabog** [comment] 2021-01-08 19:21
Hi @compulim, can you review this issue?

**Comment by compulim** [comment] 2021-01-11 19:14
We only support plain text and Markdown content. For this type of work, I recommend you to pass a custom Markdown renderer to do so.

This is a topic outside of Web Chat, but out of my personal experience, you could use Markdown-It to achieve the job.

1. [Parse the Markdown into a tree of token](https://markdown-it.github.io/markdown-it/#MarkdownIt.parse)
2. Walk the tree of token, add `sr-only` as needed
3. [Render the Markdown back into a string](https://markdown-it.github.io/markdown-it/#Renderer.render)
4. Wrap step 1-3 into a function and pass it to Web Chat as using `renderMarkdown` option

**Comment by nfreear** [comment] 2021-01-11 19:31
Hi @compulim,

> We only support plain text and Markdown content.
>
Yes, the example HTML above was output, not Markdown passed into a Bot.

> For this type of work, I recommend you to pass a custom Markdown renderer to do so.
>
The "_I_" in my report above is the end-user, not me specifically. Apologies if that wasn't clear.

I'm not concerned about my implementation specifically. I'm trying to help `WebChat` support better, more accessible behaviour by default ... most implementors are not going to bother passing a custom Markdown renderer.

Please can you re-open this bug report?

Thank you!

Nick

**Comment by corinagum** [comment] 2021-01-12 00:24
This is a duplicate of #3087. Closing as dupe.

**Closed by corinagum** 2021-01-12 00:24 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported
