### ISSUE TITLE
Setting up Direct Line Speech using webSpeechPonyFillFactory prop, not getting Microphone

### ISSUE THREAD

**Issue by ivanELEC** [microsoft/BotFramework-WebChat#3485] opened 2020-09-16 15:03 UTC
Versions:
 botframework-directlinejs: 0.13.1
 botframework-webchat: 4.10.1
 reactjs: 16.13.1

## Describe the bug

I am trying to add speech to my bot via Azure Cognitive Speech services using the webSpeechPonyFillFactory  prop in the ReactWebChat component - when the component loads I do not get a microphone to indicate speech is available.

## Steps to reproduce (Code flow)

1. Create direct line
2. Get token from cognitive search API using subscription key
3. Use token retrieved as authorizationToken for createCognitiveServicesSpeechServicesPonyfillFactory function 
4. With direct line and ponyfillfactory, create ReactWebChat component

## Expected behavior

Bot loads with Microphone icon for speech functionality

## Actual behavior

Bot loads but with no microphone

## Code (Slightly abstracted for clarity)
```
import React, { useState, useEffect } from "react";
import ReactWebChat, { createDirectLine } from "botframework-webchat";
import DirectLine from "botframework-webchat";
import { ConnectionStatus } from "botframework-directlinejs";
const axios = require("axios");

export const MSBot: React.FunctionComponent<Props> = (props) => {
  //hooks for setting all the states
  const [botLoading, setBotLoading] = useState<boolean>(false); //for determining whether bot direct line has been retrieved or not
  const [speechLoading, setSpeechLoading] = useState<boolean>(false); //for determining whether bot direct line speech pony fill has been retrieved or not
  const [directLinev2, setDirectLinev2] = useState<DirectLine>();
  const [botPonyfill, setBotPonyFill] = useState<any>({});

  //--- functions ---//
  //create axios instance for direct line secret API call
  const directLineAPI = axios.create({
    baseURL: "https://directline.botframework.com/v3/directline/tokens",
    timeout: 5000,
  });

  const speechAPI = axios.create({
    baseURL: "https://eastus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken",
    timeout: 5000,
  });

  //function for creating ponyfillfactory for speech
  async function createPonyFill(webchat) {
    const res = await speechAPI.post("/", null, {
      headers: {
        "Ocp-Apim-Subscription-Key": `xxxxxxxxxxxxxxxxxxxxxxx`, //hidden for security
      },
    });

    if (res.statusText != "OK") {
      throw new Error("Failed to fetch authorization token and region.");
    }

    const adapters = await webchat.createCognitiveServicesSpeechServicesPonyfillFactory(
      {
        region: "eastus2",
        authorizationToken: res.data,
      }
    );
    console.log(adapters);

    return adapters;
  }

  function handleDirectLine() {
    //--- function for creating/updating directline would be here --//
  }

  //create direct line and memorize
  useEffect(() => {
    //use fetchCredentials function to retrieve credentials for speech adapter and assign to bot
    let windowObj: any = {};
    windowObj = window;
    createPonyFill(windowObj.WebChat)
      .then((res) => {
        setBotPonyFill(res);
        setSpeechLoading(true);
        console.log("set speech loading to true");
      })
      .then((res) => {
        handleDirectLine();
        setBotLoading(true);
      });
  }, []);

  //React Components to Return from Functional Component
  return botLoading && speechLoading ? (
    <div>
      <ReactWebChat
        adaptiveCardsHostConfig={properties.adaptiveCardsHostConfig}
        directLine={directLinev2} //retrieved in handleDirectLine function
        userId={`dl_${props.userId}`} //these are retrieved however I am not showing the code in my sample
        styleOptions={styleOptions} //these are retrieved however I am not showing the code in my sample
        webSpeechPonyFillFactory={botPonyfill}
      />
    </div>
  ) : (
    <div>Loading...</div>
  );
};
```

**Comment by tsuwandy** [comment] 2020-09-16 18:09
@compulim, is this related to the other direct line speech issues?  Could you take a look?

**Comment by tsuwandy** [comment] 2020-09-18 18:20
@ivanELEC , did you take a look at this sample?
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech

**Comment by stevkan** [comment] 2020-09-18 20:04
@ivanELEC, are you receiving any errors in the dev console when you try to run? If so, can you list them? Also, have you verified that `botPonyfill` actually has a value and is not undefined or some other?

Have you had a chance to look over the above sample? As I have re-verified that that implementation does work, are you able to simplify your set up to match the sample as closely as possible with the aim of just getting it to work, as demonstrated? If you can get it to work as-is, then you can introduce the different implementations such as using Axios, etc.

**Comment by ivanELEC** [comment] 2020-09-29 14:02
Hello @stevkan unfortunately there are 2 differences in my infrastructure which means I may not be able to follow the link above exactly (or that this would lead to an unsatisfactory experience): 

1. Since I am using the ReactWebChat component exposed by the botframework-webchat module, the only prop of that component that allows me to enable speech is assigning webSpeechPonyFillFactory via creating it using the createCognitiveServicesSpeechServicesPonyfillFactory function. 

2. Since this project is in React, I need to handle the webSpeechPonyFillFactory via states (as it starts as empty/null and gets generated over time after the page loads) - when I use the fetchCredentials method outlined in the [sample ](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech) - I get the following error:

Error: web-speech-cognitive-services: Credentials must be specified.

Here is a look at  code using a more similar approach to the sample, note that this is just the snippets of my code relevant to the issue and how the botPonyFill state gets loaded into the React component is not relevant in this case as the error occurs even if I do not assign it to anything

```
//hook to use and set state of speech service pony fill factory object
 const [botPonyfill, setBotPonyFill] = useState<any>(null);

//function for creating speech services ponyfill factory
async function getBotSpeechPonyfill(webchat) {
    const fetchCredentials = async () => {
      const res = await speechAPI.post("/", null, {
        headers: {
          "Ocp-Apim-Subscription-Key": `xxxxxxxxxxxxxxxxxxxxxxxxxxxxx`,
        },
      });
      if (!res.ok) {
        throw new Error("Failed to fetch authorization token and region.");
      }

      const { region, token: authorizationToken } = await res.json();
      return { authorizationToken, region };
    };

    const adapters = await webchat.createCognitiveServicesSpeechServicesPonyfillFactory(
      {
        fetchCredentials
      }
    );
    console.log(adapters);
    return adapters;
  }

...

//effect that assigns bot speech pony fill to state
useEffect(() => {
        let windowObj: any = {};
        windowObj = window;
        getBotSpeechPonyfill(windowObj.WebChat).then((res) => {
            setBotPonyFill(res);
        });
   });
```

Attempting to do this as close to the example as possible, I tried this on a vanilla HTML page however nothing happened (nothing of note in console.log):

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--<link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />-->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
 
    <title>Nova PA</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {
        const fetchCredentials = async () => {
          const res = await fetch('https://eastus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken', {
            method: 'POST',
            headers:{"Ocp-Apim-Subscription-Key": `6801d4e912c840f282129630e03cca3d`}
          });
          if (!res.ok) {
            throw new Error('Failed to fetch authorization token and region.');
          }
          
          const { region, token: authorizationToken } = await res.json();
          return { authorizationToken, region };
        };

        const adapters = await window.WebChat.createDirectLineSpeechAdapters({
          fetchCredentials
        });

        window.WebChat.renderWebChat(
          {
            ...adapters
          },
          document.getElementById('webchat')
        );
        document.querySelector('#webchat > *').focus();
      })().catch(err => err);
    </script>
  </body>
</html>
```

**Comment by ivanELEC** [comment] 2020-09-30 11:26
Update: I can confirm that the following code works (the main difference being that I do not check for status = 200 anymore - I simply check for the fail state to return errors, this means that speech would work on this particular bot service with this speech service. However the result I am trying to achieve is adding speech to the ReactWebChat component via the  createCognitiveServicesSpeechServicesPonyfillFactory which should also work: 

```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <script
      crossorigin="anonymous"
      src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"
    ></script>
    <title>Nova PA</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <div id="webchat" role="main"></div>
    <script>
      (async function () {
        async function fetchCredentials(){
          const res = await fetch(
            "https://eastus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken",
            {
              method: "POST",
              headers: {
                "Ocp-Apim-Subscription-Key": `xxxxxxxxxxxxxxxxxxxxxx`,
              },
            }
          );
          if (!res.ok) {
            throw new Error("Failed to fetch authorization token and region.");
          }
          return { authorizationToken: await res.text(), region: "eastus2" };
        };
        const adapters = await window.WebChat.createDirectLineSpeechAdapters({
          fetchCredentials
        });

        window.WebChat.renderWebChat(
          {
            ...adapters
          },
          document.getElementById("webchat")
        );
        document.querySelector("#webchat > *").focus();
      })().catch((err) => err);
    </script>
  </body>
</html>
```

**Comment by ivanELEC** [comment] 2020-10-01 16:58
I can confirm that using the method of bringing in Speech via webSpeechPonyfillFactory property of the ReactWebChat component object does load the function to the prop when the component is loaded (and I have code that prevents the component from loading before the state for that prop is populated  - however since this prop expects a function as an input, i'm not entirely sure what a successful input for this prop looks like: 

![image](https://user-images.githubusercontent.com/26544538/94838594-5ad22080-0405-11eb-81d5-63be597e2919.png)

This is what the console.log for the state I am inputting into the webSpeechPonyfillFactory looks like: 

![image](https://user-images.githubusercontent.com/26544538/94839973-468f2300-0407-11eb-92bd-fc5dcd5e5902.png)

**Comment by ivanELEC** [comment] 2020-10-07 17:40
Hi @stevkan  @tsuwandy any idea on the above? I have tested that speech works using the basic example - but speech should also work via the property in ReactWebChat. Is there any place that I can maybe add some console logs in the js files of the botframework-webchat module to diagnose this further?

**Comment by stevkan** [comment] 2020-10-07 21:09
@ivanELEC, per your post on 9/29, I can confirm that the 3rd code sample works for me, as well. The 2nd wouldn't, initially, because of the below code. In the `.then()` you need to either return `res` after the `console.log()` or remove the `.then()`, all together (which is why the 3rd worked as it doesn't have the `.then()`.

```
const adapters = await window.WebChat.createDirectLineSpeechAdapters( {
  fetchCredentials
} ).then( res => {
  console.log( res );
  return res;    <=== Added code
} );
```

I'm attempting a repro / build in a React project and will let you know what I find. As I don't know, specifically, how you have set up your project, I'm trusting anything I produce will match close enough to be of help. I will keep you posted.

**Comment by stevkan** [comment] 2020-10-08 22:08
@ivanELEC, after a little investigating, I was able to figure out what was needed to get your React project version of Web Chat + CS speech to work. There were two things I needed to change, however the primary focus is on the first. Also, note that I don't have a TS + React project up and running, so this is in pure JS which _shouldn't_ be an issue.

1. The `webSpeechPonyfillFactory` (which should have a lowercase 'f' in 'Ponyfill") requires a function be passed in, not an object as you already noted. So, on line 59, instead of only passing in `res`, I passed it in as a function: `setBotPonyfill(() => res)`. The interesting thing about this is, even though `createPonyfill()` returns a function, when `res` (a function) is passed into `setBotPonyfill()`, it is saved as an object. To override this, I had to specifically pass in `res` as a function for it to be saved as such.

    Because of the above, I also had to change `useState({})` to `useState()` on line 12. Simply removing the curly braces didn't allow `res` to be saved as a function.

2. Maybe of no consequence to you, but I was unable to get `directLineAPI()` to work for me, tho `speechAPI()` did. I relied on a 'token' server I already have running which I called directly in `handleDirectLine()`. I found that I had to `await` the `handleDirectLine()` call on line 64 for the direct line object to be read correctly. If this was working for you before, then you can revert and ignore my changes here.

Hope of help!

```js
import React, { useState, useEffect, useMemo } from "react";
import ReactWebChat, { createDirectLine } from "botframework-webchat";
import DirectLine from "botframework-webchat";
import { ConnectionStatus } from "botframework-directlinejs";
const axios = require("axios");

export const WebChatSpeech = (props) => {
  //hooks for setting all the states
  const [botLoading, setBotLoading] = useState(false); //for determining whether bot direct line has been retrieved or not
  const [speechLoading, setSpeechLoading] = useState(false); //for determining whether bot direct line speech pony fill has been retrieved or not
  const [directLinev2, setDirectLinev2] = useState();
  const [botPonyfill, setBotPonyfill] = useState();      //  <===== Removed '{}' in 'useState()'

  //--- functions ---//
  // create axios instance for direct line secret API call
  const directLineAPI = axios.create({
    baseURL: "https://directline.botframework.com/v3/directline/tokens",
    timeout: 5000,
  });

  const speechAPI = axios.create({
    baseURL: "https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken",
    timeout: 5000,
  });

  //function for creating ponyfillfactory for speech
  async function createPonyFill(webchat) {
    const res = await speechAPI.post("/", null, {
      headers: {
        "Ocp-Apim-Subscription-Key": `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`, //hidden for security
      },
    });

    if (res.statusText !== "OK") {
      throw new Error("Failed to fetch authorization token and region.");
    }

    const adapters = webchat.createCognitiveServicesSpeechServicesPonyfillFactory(
      {
        region: "westus2",
        authorizationToken: res.data,
      }
    );

    return adapters;
  }

  async function handleDirectLine() {
    //--- function for creating/updating directline would be here --//
  }

  //create direct line and memorize
  useEffect(() => {
    //use fetchCredentials function to retrieve credentials for speech adapter and assign to bot
    let windowObj = {};
    windowObj = window;
      createPonyFill(windowObj.WebChat)
        .then((res) => {
          setBotPonyfill(() => res);       // <===== Passing 'res' as a function
          setSpeechLoading(true);
          console.log("set speech loading to true");
        })
        .then(async (res) => {
          const directLine = await handleDirectLine();       // <===== 'awaiting' the direct line response
          setDirectLinev2(directLine);
          setBotLoading(true);
        });
  }, []);

  //React Components to Return from Functional Component
  return botLoading && speechLoading ? (
    <div>
      <ReactWebChat
        // adaptiveCardsHostConfig={properties.adaptiveCardsHostConfig}
        directLine={directLinev2} //retrieved in handleDirectLine function
        // userId={`dl_${props.userId}`} //these are retrieved however I am not showing the code in my sample
        // styleOptions={styleOptions} //these are retrieved however I am not showing the code in my sample
        webSpeechPonyfillFactory={botPonyfill}
      />
    </div>
  ) : (
    <div>Loading...</div>
  );
};
```

**Comment by stevkan** [comment] 2020-10-13 18:05
Closing this as resolved.

**Closed by stevkan** 2020-10-13 18:05 UTC
Labels: Bot Services, Bug, Support, customer-replied-to, customer-reported

**Comment by ivanELEC** [comment] 2020-10-14 14:52
Sorry for the late reply on your comment - thank you so much for your help as using the non capitalised F in the property and also passing in via forcing the input to be a function worked. 

Much appreciated
