### ISSUE TITLE
Bot not loading in Modern SharePoint online IE browser

### ISSUE THREAD

**Issue by manjunathangv** [microsoft/BotFramework-WebChat#2646] opened 2019-12-01 07:47 UTC
I verified #1824. I dint find any solution for this.
I'm using **/webchat-es5.js/** CDN.
Is there any solution for Bot not loading in IE but the same is getting loaded in Chrome and Edge.

`window.WebChat.renderWebChat({
                    directLine: window.WebChat.createDirectLine({ token: '---------' }),
                    userID: ID,
                    username:Uer',
                    locale: 'en-US',
                    styleOptions:styleOptions,
                    store:store,
                    webSpeechPonyfillFactory: window.WebChat.createBrowserWebSpeechPonyfillFactory()
                }, document.getElementById('webchat'));`

**Getting Below console errors:**
Unable to get property 'createStore' of undefined or null reference
Unable to get property 'renderWebChat' of undefined or null reference

I tried to Load webchat cdn through console also but not working.

Let me know is there any solution for this.
Thanks in advance.

**Comment by corinagum** [comment] 2019-12-02 20:27
Hi @manjunathangv, could you post all of your HTML? Based off of the errors I would say that perhaps the CDN is not linked correctly. Latest bits seem to be working fine, though not tested in SharePoint.

**Comment by manjunathangv** [comment] 2019-12-04 05:36
Hi @corinagum ,its a SPFX build. I have include the link and its working good in chrome and Edge.

**Comment by corinagum** [comment] 2019-12-04 17:31
This is IE11, correct? What version of Web Chat are you using?

**Comment by manjunathangv** [comment] 2019-12-04 17:47
> This is IE11, correct? What version of Web Chat are you using?

Yes IE11. 
I tried master, latest and 4.5.3 webchat versions.

**Comment by corinagum** [comment] 2019-12-04 18:00
`master` is deprecated, so there's no longer a need to test that CDN. :) If you want latest bits, you can build Web Chat and use any of the bundles in `packages/bundles/dist/`

Could you post your code so I can take a look? Thank you!

**Comment by manjunathangv** [comment] 2019-12-05 06:05
@corinagum 
PFA screenshots.

![2](https://user-images.githubusercontent.com/54570517/70208156-cea68c80-1752-11ea-829f-5a08d5ca9669.png)
![1](https://user-images.githubusercontent.com/54570517/70208157-cea68c80-1752-11ea-87b4-964faf9d7e21.png)

**Comment by corinagum** [comment] 2019-12-05 17:37
Could you share the code you use to fetch the token? If that code has arrow functions, they won't work in IE11.

**Comment by compulim** [comment] 2019-12-05 21:04
@manjunathangv do you see any console errors that prevents `webchat-es5.js` to be loaded?

**Comment by corinagum** [comment] 2019-12-05 21:56
@compulim I believe we've established previously that SharePoint doesn't report Web Chat's errors. However, still a good question, especially if I'm wrong and there are errors xD

**Comment by manjunathangv** [comment] 2019-12-06 06:29
> Could you share the code you use to fetch the token? If that code has arrow functions, they won't work in IE11.

@corinagum , I have hard coded the token value.

Atleast, i should see **window.Webchat**, **window.renderWebChat**  in IE browser console but Chrome i can see.

I tried loading below script also,I'm seeing window object with **renderWebChat** & **Webchat** in chrome and other IE sites. but only in SharePoint site where i deployed custom bot, i'm facing this issue.

`var cdnScript = document.createElement('script');
cdnScript.setAttribute('src','https://cdn.botframework.com/botframework-webchat/4.5.3/webchat-es5.js');
document.head.appendChild(cdnScript);`

**Comment by compulim** [comment] 2019-12-07 04:40
In the console log, do you see any warnings or errors when the script is loaded?

**Comment by manjunathangv** [comment] 2019-12-13 05:33
@compulim I'm not getting any errors and warning while loading.

**Comment by CoHealer** [comment] 2020-01-09 21:17
Adding @dmvtech to assist. @corinagum, how can we help?

**Comment by corinagum** [comment] 2020-01-13 17:28
Sorry for the late reply. Thanks @CoHealer and @dmvtech We've had SharePoint problems filed in the past that dmvtech helped customers work through. Do you think you could do similar for this one? SP is not one of our test scenarios unfortunately.

**Comment by dmvtech** [comment] 2020-01-13 18:00
@manjunathangv You mentioned modern page, but how exactly are you implementing? Is this being done in a SPFx (web part, extension)? or in a custom page? or something else?

**Comment by manjunathangv** [comment] 2020-01-14 06:20
@dmvtech , yes we build a spfx package but its not purely done in react we used webchat-es5.js .

Atleast, i should see window.Webchat, window.renderWebChat in IE browser console but Chrome i can see.

**Comment by dmvtech** [comment] 2020-01-22 16:52
Thanks. I am looking into this further.

**Comment by dmvtech** [comment] 2020-01-22 18:28
@manjunathangv If you have a sanitized repo of your SPFx code/reproduction that I could use, that might make things go a little faster/easier for me.

**Comment by CoHealer** [comment] 2020-01-29 20:49
Closing due to lack of user activity.

**Closed by CoHealer** 2020-01-29 20:49 UTC
Labels: Bot Services, Bug, Pending, R8, Support, customer-replied-to, customer-reported
