### ISSUE TITLE
Base 64 local images not rendered in Webchat after deployment to azure web app

### ISSUE THREAD

**Issue by HebatallaTarek** [microsoft/BotFramework-WebChat#3650] opened 2020-12-27 21:27 UTC
## Version

Webchat V4 embedding into website using iframe

## Describe the bug
I generate local base64 images and upload it to azure blob then use the blob URL  to be displayed into Hero Card , when i run through emulator everything works fine but once i deploy to azure web app nothing is rendered i wait for hero card to be displayed but nothing appear an no errors in logs 

I tried to use relative path as shown below it work locally but it did not work on webchat after deployment  :

 **var imagePath = "./Dialogs/Services/CardInquiry/image.Jpg";**

I tried to use sample 15 Using Attachements  to handle local images it work locally fine but also not work on deployed version 

**var imagePath = Path.Combine(Environment.CurrentDirectory, @"Dialogs\Services\CardInquiry\image.Jpg");**	

I do not know what could i do to deploy the local path of image remotely on azure web app and be able to render the image 

		
## Expected behavior

image has to render in webchat like rendering on emulator 

## Additional context

[Bug]

**Comment by joshgummersall** [comment] 2020-12-28 19:53
How big is the image file? The Emulator does not enforce a file size limit, but DirectLine does.

**Comment by HebatallaTarek** [comment] 2020-12-28 21:16
@joshgummersall  it's 221.4 KB i know  from previous posts that the limit of image size is 4 MB

**Comment by joshgummersall** [comment] 2020-12-28 21:51
What is the path that shows up in the browser when rendering the image?

**Comment by HebatallaTarek** [comment] 2020-12-28 22:04
@joshgummersall  sorry i did not get what you mean by path in the browser ? i embed iframe  in html to use webchat

**Comment by joshgummersall** [comment] 2020-12-28 22:06
Within the iframe, there should be some HTML that renders an image. Could you copy and paste that HTML so I can see the image path?

**Comment by joshgummersall** [comment] 2020-12-28 22:06
Within the iframe, there should be some HTML that renders an image. Could you copy and paste that HTML so I can see the image path?

**Comment by HebatallaTarek** [comment] 2020-12-28 22:11
`<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Full-featured bundle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <script src="https://unpkg.com/markdown-it@8.4.2/dist/markdown-it.min.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }
      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }

			.avatar {
				background: white  !important;
			}
			.from-user .avatar {
					background: rgb(0, 150, 136) !important;
			}
			/* Truncation Of Messages */
      pre {
          white-space: pre-line;
      }
			</style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {
          const markdownIt = window.markdownit();
          // Remember old renderer, if overridden, or proxy to default renderer
          var defaultRender = markdownIt.renderer.rules.link_open || function(tokens, idx, options, env, self) {
              return self.renderToken(tokens, idx, options);
          };

          markdownIt.renderer.rules.link_open = function (tokens, idx, options, env, self) {
              // If you are sure other plugins can't add `target` - drop check below
              var aIndex = tokens[idx].attrIndex('target');

              if (aIndex < 0) {
                  tokens[idx].attrPush(['target', '_blank']); // add new attribute
              } else {
                  tokens[idx].attrs[aIndex][1] = '_blank';    // replace value of existing attr
              }

              // pass token to default renderer.
              return defaultRender(tokens, idx, options, env, self);
          };

          const directLine = window.WebChat.createDirectLine({
              secret: " ",
              webSocket: false
          });

          window.WebChat.renderWebChat(
              {
                  directLine: directLine,
                  userID: 'testuser',
                  renderMarkdown: markdownIt.render.bind(markdownIt),
                  styleOptions: {
                      hideUploadButton: true,
											botAvatarImage:
												'https://smarterachatbot.blob.core.windows.net/images/chat bot logo.png',
											botAvatarInitials: 'SB',
											userAvatarInitials: 'USER'
                  }
              },
              document.getElementById('webchat')
          );
		  directLine
			  .postActivity({
				  from: { id: "testuser", name: "Web Chat" },
				  name: "requestWelcomeDialog",
				  type: "event",
				  value: "token"
			  })
			  .subscribe(
				  id => console.log(`Posted activity, assigned ID ${id}`),
				  error => console.log(`Error posting activity ${error}`)
			  );

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>`

@joshgummersall  that's content of index.html but i did not write image path inside this html it's in source code like what i mention in issue description

**Comment by joshgummersall** [comment] 2020-12-28 23:00
If you use a browser like Edge, Chrome, or Firefox you should be able to "Right Click - Inspect" rather than just viewing the source of `index.html`. This includes all DOM updates made by Javascript code. The code you included looks like the results of "Right Click - View Source" which do not include any DOM updates.

u reproduce the issue (i.e. receive a message with an image card) you should be able to "Right Click - Inspect" to see the card HTML, including the image path. Does that work?

**Comment by HebatallaTarek** [comment] 2020-12-28 23:21
@joshgummersall  unfortunately no it does not work as the bot reply of image not received to be inspected

**Comment by joshgummersall** [comment] 2020-12-28 23:49
Hey @stevkan, it looks like this issue is related to https://github.com/microsoft/BotFramework-WebChat/issues/3638. Any idea what might be going on?

**Comment by stevkan** [comment] 2020-12-29 23:16
@HebatallaTarek, this is actually expected behavior. Emulator is built in Electron which, when started, runs a server and has access to the local file system. Files uploaded in Emulator are stored with generated URL endpoints as part of the server process thus making them accessible at a later point (while running). Web Chat, running in a browser, is simply a client that **does not** have access to the file system. Whether the bot and/or Web Chat is run locally with locally sourced images makes no difference as the browser will continue to maintain a separation from the file system.

In order for an image to be displayed in a card, the image must be stored remotely and passed thru in the card as a URL. In other words, you need to host the image online (Azure Blob Storage, OneDrive, Imgur, etc.), create a (shared) URL endpoint for that file, and then provide that URL as the value for the image property in the card.

I am going to close this issue as this should resolve the problem.

**Comment by HebatallaTarek** [comment] 2020-12-30 11:07
@stevkan  hello , i mentioned in issue description that i already uploaded the image to Azure Blob and use the URL inside Hero Card and also it did not work  what you suggest ?

**Comment by HebatallaTarek** [comment] 2020-12-30 11:17
@stevkan  @joshgummersall  please reopen the issue

**Comment by HebatallaTarek** [comment] 2020-12-30 11:30
@joshgummersall  @stevkan  Please i would like to reopen the issue  till we reach solution

**Comment by joshgummersall** [comment] 2020-12-30 18:56
@HebatallaTarek, can you share a fully Azure Blob Storage URL? It's possible you could be uploading a file without the proper permissions for public access. It's also possible that the browser refuses to render the image because the blob doesn't have the correct metadata.

**Comment by HebatallaTarek** [comment] 2020-12-30 19:21
@joshgummersall  thanks josh for your response , okay sure it's  https://smarterachatbot.blob.core.windows.net/tempimage/tamweencard-blob 
I know by default it's private access , but i change private settings to anonymous access

**Comment by joshgummersall** [comment] 2020-12-30 19:59
@HebatallaTarek, try to set the Content-Type of the blob to something like `image/jpeg`. It's currently reported as `application/octet-stream` which is likely why the browser is not rendering it as an image.

**Comment by HebatallaTarek** [comment] 2020-12-30 20:45
@joshgummersall  thanks josh , i tried your suggested solution now , but unfortunately it did not work after changing content type

**Comment by joshgummersall** [comment] 2020-12-30 20:48
@HebatallaTarek you've used the wrong mime type:

```bash
jpg@MININT-5EKF9AQ ~> curl -sv https://smarterachatbot.blob.core.windows.net/tempimage/tamweencard-blob 2>&1 | grep Content-Type
< Content-Type: image/Jpg
```

It should be `image/jpeg` _exactly_. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types for a list of common mime types.

You should be able to visit https://smarterachatbot.blob.core.windows.net/tempimage/tamweencard-blob in your browser and see the image rendered. At the moment, for me, it forces a download of the file.

**Comment by HebatallaTarek** [comment] 2020-12-30 20:52
@joshgummersall  yes i make it as Jpg as it's path was  Jpg type before uploading to Blob , okay i will try to change it  right now and deploy again

**Comment by HebatallaTarek** [comment] 2020-12-30 21:16
@joshgummersall  i change type and the url render not download like before , but it did not render in webchat i can not understand why ?

**Comment by joshgummersall** [comment] 2020-12-30 21:24
@stevkan do you have any other ideas? I've verified that the URL points to a file hosted on Blob Storage that is accessible and has the proper image mime type.

**Comment by HebatallaTarek** [comment] 2020-12-30 21:33
@joshgummersall  I tried multiple browsers and the same issue , i checked  Avg response time and it did not exceed 15 sec logs files of deployed version nothing appear as error  , it has to work normally like any image url inside hero card ,  so strange

**Comment by HebatallaTarek** [comment] 2020-12-30 22:25
@joshgummersall  i noticed   something but i would like to verify if it's right or not from you , normally in Hero Card Images [] we use url ended with extensions like .png / ,jpg  , but in blob URL  we have here it's not ended with that extensions , could that make confusion in card template to be  rendered ?

**Comment by joshgummersall** [comment] 2020-12-30 22:27
I'm not as well versed in the specifics of rendering cards, but it's certainly worth a shot. In general, browsers won't render images without the proper mime type. The library may do extra validation on URLs as well, so I would definitely suggest giving that a shot.

**Comment by stevkan** [comment] 2021-01-11 18:26
@HebatallaTarek, @joshgummersall, apologies. I somehow missed this discussion in any notifications.

It looks to me that the wrong URL is being supplied. You appear to be using the literal path to the file  (https://smarterachatbot.blob.core.windows.net/tempimage/tamweencard-blob). You want to use the generated URI for the shared access signature (SAS) you create for the image. After specifying the policy parameters for your SAS and you click create, you will be presented with both a URI and a Query String. Copy the URI as this is the pathway that houses the baked in policy you assigned/created for it.

For instance, after creating a policy and SAS on a file I have, here is the generated link (it will expire in 1 week). Yours should look something like this: https://botberg81bd.blob.core.windows.net/images/image_192.png?sv=2019-12-12&st=2021-01-11T18%3A08%3A04Z&se=2021-01-18T18%3A08%3A00Z&sr=b&sp=r&sig=4fobF13MfS2SDuDD2%2BjchZpniBRYEXJvEbhE5G52aIQ%3D

**Comment by stevkan** [comment] 2021-01-21 01:33
Closing due to inactivity.

**Closed by stevkan** 2021-01-21 01:33 UTC
Labels: Bot Services, Support, customer-replied-to, customer-reported
