### ISSUE TITLE
Chatbot Avatar image not showing for all message

### ISSUE THREAD

**Issue by UtkarshSinghal17** [microsoft/BotFramework-WebChat#3649] opened 2020-12-22 15:19 UTC
I am using webchat-es5.js CDN.

## Describe the bug

 I am using botAvatarImage style property to Show chatbot image but If I am sending two activity from bot  to any user response then only for one activity image is coming and for second activity chatbot avatar not showing.

## Steps to reproduce
Step 1: use Webchat-es5 js 
Step 2: In  window.WebChat.renderWebChat under styleOptions provide botAvatarImage.
Step 3:  From backend side send two separate message for one user query.

## Expected behavior
chatbot avatar Image should display for all the activity.

## Additional context

[Bug]
![image](https://user-images.githubusercontent.com/44197601/102904092-3ed79b80-4497-11eb-83bc-cc7c32546aa9.png)

**Comment by corinagum** [comment] 2020-12-22 18:35
Because attachments are technically the same activity as the text before, the avatar message is only displayed once. 

You can look into this sample for more info: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/k.per-message-avatar/ but please note there are some bugs that have yet to be addressed.

**Comment by stevkan** [comment] 2020-12-22 18:44
@UtkarshSinghal17, this is also expected behavior as of v4.10.0. As you can see from the change log, posted [here](https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.10.0):

> By default, we will group avatar per status group.
> If you want to switch back to previous behaviors, please set styleOptions.showAvatarInGroup to true.

Closing as resolved.

**Closed by stevkan** 2020-12-22 18:44 UTC
Labels: Bot Services, customer-replied-to, customer-reported
