### ISSUE TITLE
Markdown table is not working on 4.5+

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2765] opened 2019-12-19 03:15 UTC
## Screenshots

The first screenshot is 4.4.2. The second screenshot is 4.5.2.

![image](https://user-images.githubusercontent.com/1622400/71141947-a09d5f80-21ca-11ea-8cd9-b6ea0ca9bd57.png)

![image](https://user-images.githubusercontent.com/1622400/71141953-a98e3100-21ca-11ea-8c73-872fbaf8a58f.png)

## Version

`4.5.2`, and possibly `4.5.0`.

## Describe the bug

In 4.4, the `markdown` command will render a table.

In 4.5, it no longer render a table.

## Steps to reproduce

1. Go to playground
1. Type `markdown`

## Expected behavior

Observe the section "Table".

It should render as a HTML table.

## Additional context

Please investigate why it happened. Maybe Markdown-It is correct that the table should not be rendered. Or maybe not.

[Bug]

**Comment by tdurnford** [comment] 2019-12-19 16:33
Markdown tables seem to work fine in Web Chat v4.7.1.

**Bot Framework SDK v4 (Node)**
```javascript
await context.sendActivity({ text: `| My | Table |  \n|-------|--------|  \n| Hello | World! |` });
```

**Screenshot**
![image](https://user-images.githubusercontent.com/17039790/71190785-12f95880-223a-11ea-9041-9a1224496f39.png)

The Mock Bot command is probably malformed.

**Comment by cwhitten** [comment] 2020-01-09 22:42
Closing as unable to reproduce

**Closed by cwhitten** 2020-01-09 22:42 UTC
Labels: Bug, Pending
