### ISSUE TITLE
Adaptive card buttons causing postback to page

### ISSUE THREAD

**Issue by vinod83k** [Microsoft/BotFramework-WebChat#656] opened 2017-08-30 04:53 UTC
I already have this updated repo, but I am still getting the same problem of Form submit on click on any button in the Adaptive cards. So, I changed the following in AdaptiveCardContainer.jsx...

_AdaptiveCardContainer.prototype.onClick = function (e) {
if (!this.props.onClick)
return;
//do not allow form elements to trigger a parent click event
switch (e.target.tagName) {
case 'A':
case 'AUDIO':
case 'VIDEO':
case 'BUTTON':
**e.preventDefault();**
break;
case 'INPUT':
case 'LABEL':
case 'TEXTAREA':
case 'SELECT':
default:
this.props.onClick(e);
}
};_

and my button stopped submitting the form.
But, still I am facing issues with the other type of buttons in the Adaptive cards, i.e, Action.ShowCard or Action.OpenUrl, but I am not able to find a place where I shall apply code to preventDefault.
Request you to please help.

**Comment by danmarshall** [comment] 2017-09-05 19:51
Closing this as a duplicate of #594 , fix is in PR #661 right now

**Closed** 2017-09-05 19:51 UTC
