### ISSUE TITLE
Mic remains turned on even after no input.

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#3280] opened 2020-06-25 10:12 UTC
## Screenshots
![image](https://user-images.githubusercontent.com/11289456/85698451-4d1b4980-b6f8-11ea-9479-47e04461de92.png)

![image](https://user-images.githubusercontent.com/11289456/85698866-adaa8680-b6f8-11ea-9004-2d21f04183e1.png)

## Version
4.9.1 cdn . using it in an angular project

## Describe the bug
The mic is not getting turned off even after 10 minutes of no input from user. It just remains on until we say something. This was not the case a few months back. 

## Steps to reproduce

Click on the mic and do not give any input.

## Expected behavior
min turns off after 5s of no input from user.

## Additional context

https://github.com/microsoft/BotFramework-WebChat/issues/2975
[Bug]

**Comment by prashanthsridhar** [comment] 2020-06-25 10:18
Implemented as below:
```
window.WebChat.renderWebChat(
      {
        userID: "jD@xyz.com",
        username: "jonDoe",
        locale: 'en-GB',
        directLine: directLine,
        styleOptions,
        groupTimestamp,
        webSpeechPonyfillFactory: options => {
          var { speechSynthesis, SpeechSynthesisUtterance ,SpeechGrammarList, SpeechRecognition } = textToSpeechPonyfillFactory(options);
          return {
            speechSynthesis,
            SpeechSynthesisUtterance,
            SpeechGrammarList,
            SpeechRecognition        
          };
        }
      },
      this.botWindowElement.nativeElement
    );
```

**Comment by srinaath** [comment] 2020-06-25 18:10
@compulim Is this an issue with DL speech or webchat?

**Comment by stevkan** [comment] 2020-06-26 02:14
@prashanthsridhar, can you please post the code you are using for the "textToSpeechPonyfillFactory" object? Here is what mine looks like. This will also work if you first get a token and pass that in using the `authorizationToken` property instead of `subscriptionKey`.

```js
    const textToSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory( {
      subscriptionKey: '<<YOUR SUBSCRIPTION KEY>>',
      region: '<<YOUR SUBSCRIPTION REGION>>'  // "westus" or "westus2", etc.
    } );
```

**Comment by prashanthsridhar** [comment] 2020-06-26 05:00
Hi @stevkan , the implementation is as below.
```
const textToSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({

            subscriptionKey: '<<YOUR SUBSCRIPTION KEY>>',
            region: 'westus2',
            speechSynthesisDeploymentId: '<<YOUR DEPLOYMENT ID>>'
        });
```


This issue is easily reproducible using the completed code in:
 https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/b.cognitive-speech-services-js

**Comment by stevkan** [comment] 2020-06-29 22:28
Hi @prashanthsridhar, I went thru the steps for creating a custom voice which, in turn, provided me with the `deploymentId`. I am able to run web chat with no issues. For reference, here is the complete code for my `bot.components.ts` file. Compare it with yours and note any differences of significance. If there are any, try altering your code to match and give it a try. If it works, great. If it doesn't, then we'll need to explore other areas of your application.

Please note these two items:

- I am also passing in the `selectVoice` parameter which assigns my custom voice's `voiceURI` which I don't see in your code. In my case, if I leave that out, I get an error when I try and speak. The error occurs immediately and before the bot get's a chance to speak. It's possible your code is handling the error differently than mine.
- In case of wonder, I get my direct line token from a back end "token" server I run, hence the call to `localhost:3500`. This can be ignored.

```js
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

declare global {
  interface Window {
    WebChat: any;
  }
}

window.WebChat = window.WebChat || {};
@Component( {
  selector: 'app-bot',
  templateUrl: './bot.component.html',
  styleUrls: [ './bot.component.css' ]
} )
export class BotComponent implements OnInit {
  @ViewChild( 'botWindow' ) botWindowElement: ElementRef;
  public BotChat: any;
  public CognitiveServices: any;
  async ngOnInit(): Promise<void> {
    this.init();
  }

  async init() {

    const res = await fetch( 'http://localhost:3500/directline/token', { method: 'POST' } );
    const { token } = await res.json();

    const directLine = window.WebChat.createDirectLine( {
      secret: token
    } );

    const textToSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory( {
      subscriptionKey: '<<MY SUBSCRIPTION KEY>>',
      region: 'westus2',
      speechSynthesisDeploymentId: '<<MY DEPLOYMENT ID>>'
    } );

    const styleOptions = {
      bubbleNubOffset: 'center',
      bubbleNubSize: 10,
      bubbleFromUserNubOffset: 'top',
      bubbleFromUserNubSize: 10,
      bubbleFromUserBackground: 'rgba(241,98,54,1)',
      bubbleFromUserTextColor: 'white',
      bubbleMinWidth: 80,
      bubblefontSize: '30px',

    };

    const groupTimestamp = true;
    window.WebChat.renderWebChat(
      {
        userID: 'dl_area51',
        username: 'My Favorite Martian',
        locale: 'en-US',
        directLine,
        styleOptions,
        groupTimestamp,
        selectVoice: () => ( { voiceURI: 'My Voice' } ),
        webSpeechPonyfillFactory: options => {
          // tslint:disable-next-line: max-line-length
          const { speechSynthesis, SpeechSynthesisUtterance, SpeechGrammarList, SpeechRecognition } = textToSpeechPonyfillFactory( options );
          return {
            SpeechGrammarList,
            SpeechRecognition,
            speechSynthesis,
            SpeechSynthesisUtterance
          };
        }
      },
      this.botWindowElement.nativeElement
    );
  }
}
```

**Comment by prashanthsridhar** [comment] 2020-06-30 18:11
Hi @stevkan ,the snippet you have provided is almost identical to my implementation. The issue is not with custom speech/voice. My understanding is that there has been a change in how silence is detected or what is done after only silence is detected. _The implementation works fine if i give the input_.  But in case i do not give any input it should stop listening after 5 seconds.

In this scenario, i am not saying that webchat fails but just that it continues to wait for input even after **five minutes** of silence. 
Attaching screen recording of the same. 
https://drive.google.com/file/d/1YSxcPieNG0YArpl8u5-Jt---joyuITnf/view?usp=sharing

When you say you able to run webchat, are you trying the scenario where you click the mic and don't say anything. 
 
is the mic getting turned off automatically after 5 seconds of no input in your implementation?

**Comment by stevkan** [comment] 2020-07-01 22:22
Hi @prashanthsridhar, it appears that this is the current behavior in Web Chat and is not specific to running Web Chat in an Angular project. I'm still looking into whether this is expected behavior, which I don't believe it is, but I will let you know more as soon I have something more tangible to share with you.

**Comment by stevkan** [comment] 2020-07-06 18:21
@prashanthsridhar, the mic remaining on and not turning off is a function managed by the speech provider (for example, Cognitive Services Speech). It is an issue you would want to post with them. It looks like creating a support ticket thru Azure is the best method, according to their site [here](https://azure.microsoft.com/en-us/support/options/).

Closing this as resolved as the issue lies with another team.

**Closed by stevkan** 2020-07-06 18:21 UTC
Labels: Bot Services, Bug, Support, customer-replied-to, customer-reported
