### ISSUE TITLE
Mic Button Does Not Get Changed to Send Button when Started Typing

### ISSUE THREAD

**Issue by PradipKumarDas** [microsoft/BotFramework-WebChat#3110] opened 2020-04-17 11:10 UTC
## Version

Web chat being used is from CDN at https://cdn.botframework.com/botframework-webchat/latest/webchat.js.

> `<meta name="botframework-directlinespeech:version" content="4.8.0">↵<meta name="botframework-webchat:bundle:variant" content="full">↵<meta name="botframework-webchat:bundle:version" content="4.8.0">↵<meta name="botframework-webchat:core:version" content="4.8.0">↵<meta name="botframework-webchat:ui:version" content="4.8.0">"`

## Describe the bug

As speech is being supported since long, I was expecting this behavior, but was surprised to see that it is not the case.  Basically when typing, the mic button is not getting changed to send button.

## Steps to reproduce

This could easy be reproduced by integrating voice over webSpeechPonyfillFactory during call to windows.WebChat.renderWebChat() method. But mic button appears. But it does not change when user starts typing. Ideally, the mic button should change to send button.

Please let me know of we can expect this behavior can be made available at the earliest as our team is planning for a production rollout with CDN webchat very soon.

Thanks.

**Comment by compulim** [comment] 2020-04-17 16:52
This is by-design. We are working on a new UI/UX design for send box in #2211. The design is going to finish in R9 (~May) and going to implement it in R10 timeframe (~August).

@DesignPolice please consider this when working on #2211.

**Comment by compulim** [comment] 2020-04-17 16:53
Sorry we couldn't make it sooner than we should have. I am closing this issue because it is (kinda) a dupe of #2211.

**Closed by compulim** 2020-04-17 16:53 UTC
Labels: Bot Services, Bug, Design needed, customer-replied-to, customer-reported

**Comment by PradipKumarDas** [comment] 2020-04-20 02:13
Thanks a lot. I am sure team will prioritize this because this is something customers will notice and report back for sure. We shall wait for this functionality to be available. And of course, I would like to thank each contributor of this web chat project for sharing so feature-rich and useful component with the world.

**Comment by DesignPolice** [comment] 2020-04-20 03:32
Thanks William, yes we are doing some UX research into this now... it seems like such a simple thing, but it does require another level or two of interaction to make the experience as intuitive as possible. 

thanks for the feedback PKD
m

**Comment by pwilliams2020** [comment] 2020-06-10 05:24
Hi. 

I am facing the same issue and it is a customer requirement. Is there any update on this ?
