### ISSUE TITLE
Incorrect Message Time Reporting

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2562] opened 2019-11-06 03:43 UTC
## Screenshots
![UML1](https://user-images.githubusercontent.com/22778273/68266372-cb10d000-0003-11ea-8d1d-3bf87cf3cbf9.png)

## Version
Webchat CDN v4.6/latest

## Browsers
Edge v44.18362.387.0
IE v11.418.18362.0
Firefox v70.0
Chrome v78.0.3904.87

## Describe the bug

The message reported timing is not showing correctly.

## To Reproduce

1. Run the webchat.
2. Make conversation history.
3. Wait around 5 min (longer you wait grater would be the inconsistency).
4. See the reported message time inconsistency.

## Expected behavior
The earlier entered messages should have grater reporting time.

[Bug]

**Comment by compulim** [comment] 2019-11-06 19:19
@arman-g Thanks for reporting. We will take a look at this bug shortly.

**Comment by benbrown** [comment] 2019-11-26 19:13
@arman-g This is scheduled for our next release. Updates will be posted here!

**Comment by corinagum** [comment] 2019-12-02 20:49
@arman-g, sorry for the delay in getting back to you on this. Unfortunately I haven't been able to reproduce this problem on Mock Bot. 

![image](https://user-images.githubusercontent.com/14900841/69994023-d4f1fa00-1501-11ea-8c4f-ebda78ff9db9.png)

Is your bot hosted somewhere that I can test for reproduction purposes? Or would you be able to provide me temporary access to the bot? Please feel free to email me at v-corgum@microsoft.com to coordinate.

Since I haven't been able to reproduce yet, I have a few follow up questions.
- Are there any console warnings/errors in any of the browsers?
- Is this a brand new bot? Or has this bot been around for a while and this is buggy behavior has recently changed?

**Comment by corinagum** [comment] 2019-12-02 21:31
@arman-g scratch my notes above; I was able to reproduce this problem! 

![image](https://user-images.githubusercontent.com/14900841/69996919-e50cd800-1507-11ea-9c24-7e3fecfef1bc.png)

I still haven't found the cause, but I am investigating. For now, all I know is that the absolute time is still accurate (based off of the aria-label), but the relative time component may be causing the issue.

**Comment by arman-g** [comment] 2019-12-03 03:34
I see you are able to produce the problem after all. To your questions:
1. No there are no console warnings.
2. Yes it is a new bot that is in development.

**Comment by corinagum** [comment] 2019-12-03 08:16
@arman-g the triangles are bubble nubs. You can take a look at `packages\playground\src\App.js` to see how they are implemented. :)

No progress yet on finding cause. I'll continue to investigate.

**Comment by arman-g** [comment] 2019-12-04 21:17
@corinagum I added more information about my findings.

**Comment by clearab** [comment] 2020-02-14 19:12
We're currently tentatively targeting a fix for this in the R9 release.

**Comment by compulim** [comment] 2020-04-01 16:59
Looking at this one, I am seeing it in 4.8.0.

![image](https://user-images.githubusercontent.com/1622400/78164920-649bac80-73ff-11ea-8fd5-d9aa961abeee.png)

**Comment by compulim** [comment] 2020-04-01 22:22
Logging here to understand what is happening. It's difficult to get this repro.

![image](https://user-images.githubusercontent.com/1622400/78192248-97a86500-742c-11ea-8e0d-5c41f788bbea.png)

![image](https://user-images.githubusercontent.com/1622400/78192277-a42cbd80-742c-11ea-9948-9a824ff63f18.png)

**Comment by compulim** [comment] 2020-04-01 22:35
![image](https://user-images.githubusercontent.com/1622400/78193073-78123c00-742e-11ea-897c-394910824647.png)

**Comment by compulim** [comment] 2020-04-02 01:03
This is the root cause. In Chrome:

```
// Given time t = 0
 
setTimeout(() => {
  console.log(Date.now());
}, 100);
```

The code above can sometimes print 99, instead of >= 100. And this is causing the timer not to be rescheduled, because the new scheduled time has not changed.

**Closed** 2020-04-03 17:47 UTC
Labels: Bot Services, Bug, P1, R9, Triaged, customer-replied-to, customer-reported
