### ISSUE TITLE
TypeError: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2495] opened 2019-10-24 23:31 UTC
Using botframework-webchat latest cdn does throw an error on IE and early versions of Edge.

IE v11.737.17763.0.
Edge v15 or earlier.
Bot Framework-webchat CDN: Latest.

Error message: TypeError: Object doesn't support property or method 'includes'

![webchat](https://user-images.githubusercontent.com/22778273/67532379-dc102780-f67a-11e9-980d-f475467088e4.PNG)

**Comment by corinagum** [comment] 2019-10-25 00:18
Duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/2449

This error will be fixed in our upcoming release.  If you need these changes immediately, please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits). You can also reference the `CONTRIBUTING.md` to build your own stop-gap Web Chat bundle.

**Closed** 2019-10-25 00:18 UTC
Labels: Duplicate

**Comment by arman-g** [comment] 2019-10-25 00:30
> Duplicate of #2449
> This error will be fixed in our upcoming release.  If you need these changes immediately, please see our documentation on pointing to our MyGet feed for latest bits. You can also reference the CONTRIBUTING.md to build your own stop-gap Web Chat bundle.

#2444 is not exactly the same error but I hope it will be fixed along the way in your upcoming release.
