### ISSUE TITLE
DirectLine 'event trigger' makes the last message to be disappeared/deleted 

### ISSUE THREAD

**Issue by selvaduraiece** [microsoft/BotFramework-WebChat#3639] opened 2020-12-08 17:17 UTC
I come across a strange issue. I trigger an event using DirectLine and based on the event name I am posting back the message to the user. 

But after triggering the message my last message which is already sent got deleted/disappeared. I am not sure why this is happening. Please refer the screenshot. 
![image](https://user-images.githubusercontent.com/40558980/101518194-9958fe00-39a7-11eb-85bc-dc6cb783f4db.png)
![image](https://user-images.githubusercontent.com/40558980/101518329-c9a09c80-39a7-11eb-8dcf-ba94644cc604.png)

Only the last message got deleted/disappeared. 
Here is the code I am using.
![image](https://user-images.githubusercontent.com/40558980/101517536-dd97ce80-39a6-11eb-859f-7c6227a3b9ba.png)
Here is the Payload
![image](https://user-images.githubusercontent.com/40558980/101517968-55fe8f80-39a7-11eb-8e3d-e040c5477738.png)

**Comment by stevkan** [comment] 2020-12-14 19:50
@selvaduraiece, the Direct Line channel doesn't support updating or deleting activities. While there could have been a hiccup in the service, it is more probable that the issue you are experiencing is rooted in your Web Chat code and how it's interacting with your bot's code.

To start, can you supply your Web Chat code as well as your bot's dialog that handles sending the initial activity / receives the response from the user?

**Comment by selvaduraiece** [comment] 2020-12-14 21:02
Hi Stevkan,
Attached webchat code. For dialog code since I am using composer sharing screenshot 
![image](https://user-images.githubusercontent.com/40558980/102131305-07099c00-3e78-11eb-944b-e05522ffd09d.png)
and then resume dialog
![image](https://user-images.githubusercontent.com/40558980/102134971-41296c80-3e7d-11eb-8af0-054eabc26aee.png)

[WebChat-github.zip](https://github.com/microsoft/BotFramework-WebChat/files/5691560/WebChat-github.zip)

**Comment by selvaduraiece** [comment] 2020-12-14 21:14
One more thing I am using ES5 version webchat. Majorly our client want IE11 support, that's y

**Comment by stevkan** [comment] 2020-12-15 09:24
@selvaduraiece, thank you for your files/details. I'll take a look at them and see if I can repro your issue.

**Comment by selvaduraiece** [comment] 2020-12-16 08:12
Hi Steven, Any update on this? it quiet urgent requirement. I am suspecting it might be because of the payload I am using. It would be great help if you could help me as early as possible.

**Comment by selvaduraiece** [comment] 2020-12-21 14:54
Hi Steven, Any update on this?

**Comment by selvaduraiece** [comment] 2020-12-25 13:17
@stevkan @peterinnesmsft - Team  any update on this? If needed, I can even raise a support ticket for the same. It would be great help if I could get some resolution. UAT is about to happen.

**Comment by stevkan** [comment] 2021-01-04 19:25
@selvaduraiece, thank you for your patience. Unfortunately, I've had encountered a separate issue in Composer that is hindering me from assisting you properly. I'm assigning this to a colleague of mine who  will continue to provide assistance.

**Comment by dmvtech** [comment] 2021-01-06 01:53
Hi @selvaduraiece I have attempted to setup a working repro, and I think i have the bot setup correctly and perhaps most of the webchat. the one thing I am unclear on is how the function `sendProactiveMsg()` is being fired? How is that being triggered?

**Comment by selvaduraiece** [comment] 2021-01-06 05:05
Hi, 

Find  the attached Front end JavaScript which triggers the sendProactiveMsg(). If the user is Idle for 3 minutes then I am calling the function.(Payload also included in the script)
[chat.txt](https://github.com/microsoft/BotFramework-WebChat/files/5773969/chat.txt)

**Comment by selvaduraiece** [comment] 2021-01-11 12:16
Hi Dana,

Any update on this?

**Comment by dmvtech** [comment] 2021-01-12 01:27
Hi @selvaduraiece I am not able to get that event firing. I am continuing to work on it.

**Comment by selvaduraiece** [comment] 2021-01-13 17:07
Hi Dhana, Was that helpful? hope the event will automatically triggered after 1minute.  Let me know if anything required from my end

**Comment by selvaduraiece** [comment] 2021-01-14 15:50
Hi Dana,
I am sharing the complete code. Just replace DirectLine secret with yours. 
1. Extract the .zip and open WebChat.js and replace your Directline Secret as shown below
![image](https://user-images.githubusercontent.com/40558980/104612509-4829e180-56ac-11eb-87b0-08760f04721a.png)
2. Open Assistant.html and start conversation as below
![image](https://user-images.githubusercontent.com/40558980/104613101-e3bb5200-56ac-11eb-90a8-5dc7a688bd4d.png)
3. Once conversation is initiated wait for 2 minute, after that automatically it should trigger a msg as shown below. As I told earlier last msg will get disappeared automatically as shown below. 
![image](https://user-images.githubusercontent.com/40558980/104614193-0a2dbd00-56ae-11eb-9409-8bff8a46df64.png)
I hope this helps. Let me know if this doesn't help you out.
It would be grt if I get some assistance at the earliest.
[chatbot.zip](https://github.com/microsoft/BotFramework-WebChat/files/5815434/chatbot.zip)

**Comment by dmvtech** [comment] 2021-01-14 20:00
Thank you. I am testing this out.

**Comment by dmvtech** [comment] 2021-01-15 01:49
I am able to reproduce and investigating the cause.

**Comment by dmvtech** [comment] 2021-01-19 16:46
Still not sure why this is happening. I've isolated it to confirm it has nothing to do with whether it is ES5 or not, whether it is a composer bot or simple echo bot. I'm still investigating and troubleshooting the code to figure it out.

**Comment by selvaduraiece** [comment] 2021-01-19 20:52
Okay, I tested with emulator using postman. But with Emulator it is not happening. I thought tht is because of Payload. Stil no luck. Will wait for your update.

**Comment by selvaduraiece** [comment] 2021-01-29 07:28
Hi, Any update on this?

**Comment by dmvtech** [comment] 2021-02-01 16:26
Hi @selvaduraiece My apologies. I am still investigating. Hope to have some info to share with you soon.

**Comment by dmvtech** [comment] 2021-02-09 01:48
Hi @selvaduraiece I am still struggling to find out what the cause is with your approach. Would you be interested in other (timer) approaches that will work?

**Comment by selvaduraiece** [comment] 2021-02-09 04:00
I am fine with other approaches as wel. can u help me with the approach
?

**Comment by compulim** [comment] 2021-02-19 19:32
If the activity come in with the same ID or same `channelData.clientActivityID`, the previous one will be replaced.

Do you think if it's the case?

**Comment by dmvtech** [comment] 2021-02-20 02:16
Thanks @compulim It is the clientActivityID.

With a quick comment out of this line the issue no longer reproduces:
`  // payload.channelData.clientActivityID = updateConversation.clientActivityID;`

**Comment by dmvtech** [comment] 2021-02-22 22:56
@selvaduraiece Can you give the above a try and let me know if that works for you?

**Comment by dmvtech** [comment] 2021-02-26 17:56
hi @selvaduraiece Just checking in. Does that resolve the issue for you?

**Comment by dmvtech** [comment] 2021-03-03 17:54
Closing as solution/fix given. Please let us know if you need further assistance.

**Comment by stevkan** [comment] 2021-03-03 17:56
Closing, per request.

**Closed by stevkan** 2021-03-03 17:56 UTC
Labels: Bot Services, Support, customer-replied-to, customer-reported, needs-team-attention
