### ISSUE TITLE
Not able to integrate createDirectLineAppServiceExtension in a.minimizable-web-chat sample present in github.

### ISSUE THREAD

**Issue by gourav-madan** [microsoft/BotFramework-WebChat#3674] opened 2021-01-17 19:09 UTC
Hi Team,

Please help me on this, I am trying to integrate directlineappserviceextension in minimizable web chat instead of createdirectline.

I have done changes in react app at two places, but its giving me an error.

1)  In minimizablewebchat.js
![image](https://user-images.githubusercontent.com/57317108/104853154-fcce3800-5924-11eb-8d1e-386c90c15832.png)

2) In WebChat.js
![image](https://user-images.githubusercontent.com/57317108/104853180-2f783080-5925-11eb-878b-ce1dfd24bf86.png)

But its giving me an error while running the bot in browser.
![image](https://user-images.githubusercontent.com/57317108/104853247-90a00400-5925-11eb-9789-f42fb55a608e.png)

I don't have idea of react coding, help me on this how i can make it work?

**Comment by gourav-madan** [comment] 2021-01-19 08:20
Is there any update on this? Its an urgent requirement and need to check whether its feasible or not.

**Comment by stevkan** [comment] 2021-01-19 19:19
@gourav-madan, thank you for your patience. I have been looking into this and have been able to repro the issue. It looks like the issue is tied to the [directLine.activity$](https://github.com/microsoft/BotFramework-WebChat/blob/0cd6b8d268b710a0194d59b0ad6765bea6b0d236/packages/api/src/hooks/Composer.js#L583) property being passed into the Composer object. When inspecting the `directLine` object created from `createDirectLineAppServiceExtension()`, it doesn't appear the `activity$` is being properly constructed.

Compare these two `directLine` objects. The first is from a typical Web Chat instance and the second from the above repro:

![image](https://user-images.githubusercontent.com/18403946/105081062-8f1a2d00-5a46-11eb-879c-ccdf99b2605b.png)

![image](https://user-images.githubusercontent.com/18403946/105080969-6eea6e00-5a46-11eb-8d94-018d00fdfd5e.png)

@compulim, @corinagum Do you have suggestions on next steps?

**Comment by gourav-madan** [comment] 2021-01-20 13:43
Hi Stevkan, Correct the error is coming with directline.activity. Hope it will get resolved early, as we have customer demo scheduled next week to show minimizable chat window working with direclineappserviceextension.

**Comment by datarocker974** [comment] 2021-01-22 11:19
Hi guys, 
Indeed, I also encounter the exact same errors using the Direct Line App Service Extension.

**Comment by corinagum** [comment] 2021-01-22 21:15
Thanks @gourav-madan for reporting, and thank you @stevkan for the repro. I have added this to list of items to triage, and we'll see next steps early next week.

**Comment by compulim** [comment] 2021-01-25 16:43
> @gourav-madan, thank you for your patience. I have been looking into this and have been able to repro the issue. It looks like the issue is tied to the [directLine.activity$](https://github.com/microsoft/BotFramework-WebChat/blob/0cd6b8d268b710a0194d59b0ad6765bea6b0d236/packages/api/src/hooks/Composer.js#L583) property being passed into the Composer object. When inspecting the `directLine` object created from `createDirectLineAppServiceExtension()`, it doesn't appear the `activity$` is being properly constructed.
> 
> Compare these two `directLine` objects. The first is from a typical Web Chat instance and the second from the above repro:
> 
> ![image](https://user-images.githubusercontent.com/18403946/105081062-8f1a2d00-5a46-11eb-879c-ccdf99b2605b.png)
> 
> ![image](https://user-images.githubusercontent.com/18403946/105080969-6eea6e00-5a46-11eb-8d94-018d00fdfd5e.png)
> 
> @compulim, @corinagum Do you have suggestions on next steps?

The difference is correct. One is constructing `activity$` using RxJS 5 (from DLJS), another is ES Observable (from other adapters). Web Chat supports both type of observable.

On the other hand, the `createDirectLineAppServiceExtension` is an async function, thus it need some time to setup. And I guess probably the `Promise` object is passed, instead of the resolved object.

```js
const ReactWebChat, { createDirectLineAppServiceExtension } from 'botframework-webchat';

const App = () => {
  const [directLine, setDirectLine] = useState();

  useEffect(() => {
    // This component can be unmounted before the return of the async function.
    // We are using an AbortController to stop the async function from calling setDirectLine, if the component is unmounted.
    const abortController = new AbortController();

    (async function () {
      const directLine = await createDirectLineAppServiceExtension(...);

      if (!abortController.signal.aborted) {
        setDirectLine(directLine);
      }
    })();

    // If the component is unmounted, abort.
    return () => abortController.abort();
  }, [setDirectLine]);

  // Only show Web Chat if directLine object is initialized.
  return (
    directLine && <ReactWebChat directLine={directLine} />
  );
};
```

p.s. for older browser that does not support `AbortController`, you can get it from [`abort-controller`](http://npmjs.com/package/abort-controller) (or ES5 version [`abort-controller-es5`](http://npmjs.com/package/abort-controller-es5))

**Comment by gourav-madan** [comment] 2021-01-27 14:47
@compulim Thanks for sharing the working code, its working fine and currently m using hardcoded bearer token generated by postman.
because m getting issue while generating the token and its coming undefined.

![image](https://user-images.githubusercontent.com/57317108/106007838-b8892780-60dc-11eb-9628-3c974bc67ee2.png)


Please find the below screen shot which m using to generate the token.
<img width="665" alt="1" src="https://user-images.githubusercontent.com/57317108/106006913-bd011080-60db-11eb-9e82-6a1680ede8d7.PNG">

Could you please tell me the changes required in "MinimizableWebChat.js." to generate the token.

**Comment by compulim** [comment] 2021-01-27 22:11
You can find the token generation API in this article, https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0#integrate-web-chat-client.

Please note that this API should only be called from your server because you will need to pass a secret to it. For security reason, never pass the secret via browsers.

**Comment by compulim** [comment] 2021-01-27 22:25
Looks like the issue is resolved by `await`-ing the Direct Line object. I am closing the issue now.

**Closed by compulim** 2021-01-27 22:25 UTC
Labels: Bot Services, P0, customer-replied-to
