### ISSUE TITLE
Timestamp of message should be formatted according to locale

### ISSUE THREAD

**Issue by Andrea-Orimoto** [Microsoft/BotFramework-WebChat#763] opened 2017-11-03 22:11 UTC
Currently the timestamp says something like "Botname il 3:07:19 PM" (it-it).

a few problems here for italian (general issue for all langs/locales):

1. the time format should be the 24 hours version, i.e. 15:07:19
2. if you ever display a date, it should be in the right locale format. i.e. dd/MM/yyyy in italian
3. the article "il" before the time doesn't make sense. It would if you displayed a date. if you only display time, it should probably be omitted.

**Comment by danmarshall** [comment] 2017-11-03 23:46
Duplicate of #748

**Closed** 2017-11-04 16:13 UTC
