### ISSUE TITLE
botchat.js file is not present in current update

### ISSUE THREAD

**Issue by virendrak** [Microsoft/BotFramework-WebChat#281] opened 2017-01-13 14:52 UTC
botchat.js file is not present in latest release. However index.html is referring to parent folder for that file.

![image](https://cloud.githubusercontent.com/assets/10959600/21933414/544f7112-d9cb-11e6-83f0-e201649412fb.png)

I have noticed wired behavior of carousel, in this release. I have defined iFrame width 500, but I am not getting arrow icons to scroll to see the other items. However, with old /css/js, it was working fine with width 350.

![image](https://cloud.githubusercontent.com/assets/10959600/21933598/0fae0b08-d9cc-11e6-97ad-5deee48e588e.png)

Also, whichever I am typing that is also not visible to me in this screen due to width issue.

If I am increasing the width of iFrame to 600, than I am able to see the Scroll icons, but whichever I am typing is still not visible fully, I can see only half text

![image](https://cloud.githubusercontent.com/assets/10959600/21933948/88b2553a-d9cd-11e6-92de-b9f083484dbf.png)

**Comment by billba** [comment] 2017-01-13 18:23
Please submit different issues for different, well, issues.

We no longer include compiled files in the GitHub repo. The idea with the samples file is that you would clone the repo and build, then run the samples. This is pretty common practice. However we might move towards pointing the samples at a CDN copy of the compiled files.

I'm going to rename this issue to focus on the carousel issue.

**Comment by billba** [comment] 2017-01-13 18:24
Actually I believe the carousel issue is a duplicate of #230 so I'm going to close this for now. Thanks for the feedback.

**Closed by billba** 2017-01-13 18:24 UTC
