### ISSUE TITLE
Infinite loop when pressing the image upload button

### ISSUE THREAD

**Issue by jash101** [Microsoft/BotFramework-WebChat#249] opened 2016-12-29 08:08 UTC
When the import/upload button besides the text input field is pressed, an infinite loop is initialised, disabling the user to escape the browse window.

**Comment by billba** [comment] 2016-12-30 08:15
I'm sorry, I can't reproduce that on Safari or Chrome on my Mac. What loop exactly are you seeing go infinite? This button is really just an `<input type="file">` and none of our code is executed until the user selects a file.

**Comment by billba** [comment] 2017-01-03 14:39
Closing for lack of reply. Happy to reopen this if I get a reproduceable case.

**Closed by billba** 2017-01-03 14:39 UTC
