### ISSUE TITLE
Send button not shown once the user types in the message box

### ISSUE THREAD

**Issue by alokraj68** [microsoft/BotFramework-WebChat#2475] opened 2019-10-16 10:42 UTC
## Version
latest from CDN

## To Reproduce

1. Go to Voice-enabled chatbot
2. Start typing a message. 
3. The send button is not shown and only the mic icon is shown

## Expected behavior
The mic icon should turn to send icon once the user starts typing something in the send box.

## Additional context

[Bug]

**Comment by tdurnford** [comment] 2019-10-16 15:55
@alokraj68 Can you please fill in the template above with the requested information? I am not able to reproduce this issue.

**Comment by alokraj68** [comment] 2019-10-17 07:40
> @alokraj68 Can you please fill in the template above with the requested information? I am not able to reproduce this issue.

Hi, Am sorry about that. Something went wrong there.

**Comment by corinagum** [comment] 2019-10-17 17:31
@alokraj68 Please note that you can still send the typed message by pressing Enter when you are ready to send. 

I just tested this out and it is true that clicking the microphone button (instead of pressing enter) with a typed message in the send box turns on the microphone, rather than sending the typed message. It looks like this is a UX oversight, but I'm not sure how quickly we would implement a fix. 

A related enhancement we have filed is https://github.com/microsoft/BotFramework-WebChat/issues/2211, which looks to have separate inputs depending on whether customer is using voice or keyboard.

**Comment by compulim** [comment] 2019-10-17 17:56
This is one of the parity work we missed when moving to v4. In v3, it used to behave what @alokraj68 said.

But since we have a plan to revamp the sendbox (#2211), the UX will be greatly improve and this bug will no longer repro.

We can keep this bug open until we close #2211.

**Comment by marq47** [comment] 2020-01-09 08:47
Hi,
I agree with @alokraj68. The behavior of the sendbox is not intuitive when the user writes on the input text and even less on mobile devices. We thought that interface redesign would come out with the 4.6 version.
We need some solution for this. Do you have some suggestion or temporary patch? When do you think sendbox redesing will be complete?

Thank you very much!!

**Comment by corinagum** [comment] 2020-10-06 17:38
I'm switching this from feature request to a bug, since there's no timeline for #2211 at the moment and this is technically a parity issue.

**Comment by cwhitten** [comment] 2021-02-25 23:57
We have some progress on https://github.com/microsoft/BotFramework-WebChat/issues/2211 and will use that to track addressing this issue. Thanks

**Closed by cwhitten** 2021-02-25 23:57 UTC
Labels: Bot Services, Bug, backlog, customer-replied-to, customer-reported, front-burner
