### ISSUE TITLE
Sent messages shown as "Sent Failed. Retry." when rendering chat using existing conversation

### ISSUE THREAD

**Issue by antoniobriones** [microsoft/BotFramework-WebChat#4506] opened 2022-11-15 21:05 UTC
### Is it an issue related to Adaptive Cards?

- [ ] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

![image](https://user-images.githubusercontent.com/50162129/202024359-1884689d-261c-47cb-ab12-69b0bbb3bb5e.png)

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Chat history

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

- Start a conversation with a bot by making a POST to https://directline.botframework.com/v3/directline/conversations
- Use that token to render the webchat on a page:
 `window.WebChat.renderWebChat( 
    { directLine: window.WebChat.createDirectLine({ token: token, }), 
    styleSet: getBotStyleSet(), 
    sendTypingIndicator: true, 
    store, 
    styleOptions: 
    getBotStyleOptions(), 
 }, document.getElementById(ctrl.widgetId + "-container") );`
- Start a conversation with the chatbot, sending a message
- Refresh the page using the same token (for the existing conversation)
- The chatbot will render the existing conversation, but the messages that were sent by the user, will appear as "Sent Failed. Retry.", see pic above.

### Do you see any errors in console log?

No

### How to reproduce the issue?

 Start a conversation with a bot by making a POST to https://directline.botframework.com/v3/directline/conversations
- Use that token to render the webchat on a page:
 `window.WebChat.renderWebChat( 
    { directLine: window.WebChat.createDirectLine({ token: token, }), 
    styleSet: getBotStyleSet(), 
    sendTypingIndicator: true, 
    store, 
    styleOptions: 
    getBotStyleOptions(), 
 }, document.getElementById(ctrl.widgetId + "-container") );`
- Start a conversation with the chatbot, sending a message
- Refresh the page using the same token (for the existing conversation)

### What is the expected and actual behavior?

Expected:
- The chatbot should render the existing conversation, and the messages should appear as "Sent"
Actual:
- The chatbot will render the existing conversation, but the messages that were sent by the user, will appear as "Sent Failed. Retry.", see pic above.

**Comment by compulim** [comment] 2022-11-16 18:27
This is duplicate of #4501.

**Closed by compulim** 2022-11-16 18:27 UTC
Labels: bug, customer-reported, Bot Services
