### ISSUE TITLE
[Accessibility] Custom render attachment for screen reader

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3547] opened 2020-10-20 06:54 UTC
## Feature Request

Today, in live region, we render activity and attachment as "Bot said, Hi I am Clara. 1 attachment."

Tomorrow, we want to render attachment with a bit more details: "Bot said, Hi I am Clara. Card: I agree button. I don't agree button."

We will need to add a middleware pipeline dedicated for rendering attachment in live region, which will be read by screen reader. The DOM tree of the attachment in live region is different than in transcript and is simplified for compatibility reason.

For attachment without a middleware, we will render as "X attachments".

### Adaptive Card and other rich cards

Example, "Card: I agree button. What states? Dropdown. Has popup. Collapsed."

Another example, "Card: Title Subtitle Content. Surface Pro image. Submit button."

### Audio

Example, "An audio clip."

### Image

Example, "An image."

[Enhancement]

**Comment by corinagum** [comment] 2020-10-20 17:18
This is a dupe of #3521

**Comment by cwhitten** [comment] 2020-10-23 14:55
Closing as a duplicate

**Closed by cwhitten** 2020-10-23 14:55 UTC
Labels: Area: Accessibility, Duplicate, P0, feature-request
