### ISSUE TITLE
Unable to change 4MB photo upload limit

### ISSUE THREAD

**Issue by andynorton** [microsoft/BotFramework-WebChat#789] opened 2017-11-18 07:32 UTC
In WebChat, the limit for “Images” is set to 4MB. This is problematic when using phone cameras to upload images for processing.

**Comment by billba** [comment] 2017-11-18 17:51
I don't think that limit is set by WebChat.

**Comment by danmarshall** [comment] 2017-11-18 17:52
Hi @andynorton I don't believe we are setting any limit in the client side code, but we have seen [similar reports for DirectLine](https://stackoverflow.com/questions/42109661/upload-max-file-size-for-botframework-directline). Can you provide a conversationID so that we can inspect on our server side?

**Comment by andynorton** [comment] 2017-11-18 17:57
An Azure Escalation Engineer said that “For WebChat, the limit for “Images” is set to 5MB. In my testing, I also noticed that the limit is currently 4MB.”

We’ve been unsuccessful when changing web config max file size options.

**Comment by billba** [comment] 2017-11-18 19:26
Seriously, the limit is not set by WebChat.

**Comment by andynorton** [comment] 2017-11-18 19:29
Okay thanks for coming back to me, would you have any suggestions on how this might be happening outside of WebChat, as we’ve struggled with anything over 4MB?

**Comment by danmarshall** [comment] 2017-11-18 22:39
Please see my comment above

**Comment by andynorton** [comment] 2017-11-19 04:34
Hi @danmarshall - Conversation ID: AphyPzEXUHlJlBQclkCiqD. Submitted 3 images under 4MB and 3 over.

**Comment by andynorton** [comment] 2017-11-26 15:29
@danmarshall - is that Conversation ID of any use?

**Comment by danmarshall** [comment] 2017-11-26 18:44
@dandriscoll - can you trace upload errors for this conversation ID: AphyPzEXUHlJlBQclkCiqD

**Comment by danmarshall** [comment] 2017-11-27 18:16
Hello @andynorton - there was an error reading the multipart MIME body. Can you please share a file which causes the issue?

**Comment by andynorton** [comment] 2017-11-27 18:22
Hi @danmarshall - https://files.slack.com/files-pri/T6D796N7M-F87453BEK/32969.png

**Comment by andynorton** [comment] 2017-11-27 18:23
Sorry - try this

https://1drv.ms/i/s!AkI2BTKSRBbJhLpiIFwFrV-a3z1LAQ

**Comment by danmarshall** [comment] 2017-11-27 21:28
Thanks @andynorton that was very helpful. I've reproduced the error, and it is being limited on the server side in Direct Line. So, 4MB will be the max size limit until further notice. Sorry you had to find out with ad hoc testing, we should publish this in our documentation. Our team will be reviewing the size limit policy.

**Comment by andynorton** [comment] 2017-11-27 21:36
Thanks @danmarshall, we’d love to help out with any testing if this limit is increased in future. Could you post a link to the  documentation you mentioned?

**Comment by danmarshall** [comment] 2017-11-27 21:46
The documentation we have is for the Direct Line Rest API itself:
https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-send-activity#upload-attachments

But - I do realize that's opaque to you and other Web Chat developers, since you're a downstream consumer of this. You're just using Web Chat, which uses DirectLineJs, which uses the Rest API.

I imagine that we need to support modern phones, which are something of a moving target wrt cameras and photo file sizes.

**Comment by danmarshall** [comment] 2017-11-27 21:47
Thanks for the help offer @andynorton :) We welcome your (and the community's) suggestions as to what this limit might be.

**Comment by compulim** [comment] 2017-12-11 18:05
I think @andynorton has his point. And we need to think about an API that filter the user upload before sending it to the server.

Like an async call so dev have chances to downscale photos on JS side, or block uploads which doesn't meet some requirements.

**Comment by mralnis** [comment] 2018-02-19 14:49
Any updates regarding this?
And why this is marked as enhancement? I receive 500 error code from direct line when i try to upload something bigger. This should be marked as bug.

**Comment by billba** [comment] 2018-02-20 15:30
This is marked as an enhancement because it is by design.

**Comment by mralnis** [comment] 2018-02-20 16:28
@billba Should't there be some validation or least a place to hook in your own validation?  
Receiving error and chat getting stuck* doesn't feel like by design.  And there is now good way that i know to inform customer that file size was too big.

* Stuck -  stopping the chat flow until you type something else.

**Comment by billba** [comment] 2018-02-20 17:05
Fair enough.

________________________________

**Comment by HainanZhao** [comment] 2018-04-05 04:45
This is annoying, my new phone camera takes 4K photos by default, the photo size goes up to 9MB easily.  And there's no setting to reduce the image resolution. Please fix this. Thanks.

**Comment by danmarshall** [comment] 2018-04-16 18:25
FWIW - here's a library that can resize the image prior to uploading: https://github.com/nodeca/pica

**Comment by chaha126** [comment] 2018-10-26 23:44
@danmarshall Hi Dan, we are developing a feature which allows our users to attach a media file (image, video, audio etc.) to their notes. Is there any way that we can configure the maximum file attachment size? Otherwise, the file icon on the bottom-left of webchat window will be not so helpful since most files (images, videos etc.) in current phones will exceed 4MB.

**Comment by compulim** [comment] 2019-04-08 17:37
When I upload a 16.3 MB file, the server returned 500. Looks like our server has some hard limits.

```http
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 51
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000
Date: Mon, 08 Apr 2019 17:34:51 GMT

{
  "error": {
    "code": "ServiceError"
  }
}
```

**Comment by compulim** [comment] 2019-04-08 17:50
Looks like we are using the default value for attachment limit (4 MB).

I can upload a 3.999 MB file (1 KB short of 4 MB). But I cannot upload a 4 MB minus 1 byte file.

**Comment by compulim** [comment] 2019-04-13 23:13
I don't think we will change this value. Will need to find a way (write a sample) for Web Chat users to upload files using their our storage, e.g. blob storage with SAS key.

**Closed** 2019-07-02 20:18 UTC
Labels: 4.5, Approved, Enhancement, P1, Triaged

**Comment by Aleimar** [comment] 2020-10-30 03:26
Hi, it's now 2020 (almost 2021). Do we have an update about file size limit now?

**Comment by zhaoxing-msft** [comment] 2021-07-13 11:40
> I don't think we will change this value. Will need to find a way (write a sample) for Web Chat users to upload files using their our storage, e.g. blob storage with SAS key.
> 
> Recommend to postpone to 4.5.

Hi, @compulim  do we now support uploading by user's storage, if yes, could you give me a ref link? thanks

**Comment by sebastianstephan** [comment] 2022-02-16 22:32
It is annoying, that this tiny limit is still in place. When can we expect to have larger file support for WebChat over DirectLine that tiny 4MB? Is there an update on that limitation?

**Comment by bradrlaw** [comment] 2022-02-22 20:11
@zhaoxing-msft What some clients have done is upload their file to blob storage from their web client / mobile app and then attach the URL to the activity to send to the bot.  This had several advantages to manage the life cycle / access control of the file.  In many cases, the bot needs to send the file to other backend services and having it already in blob storage makes that easier.
