### ISSUE TITLE
Polling missing first message, getting stuck with 'undefined' watermark

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotFramework-WebChat#163] opened 2016-11-23 21:51 UTC
Occasionally the control loads and starts polling in a weird state. Two symptoms:
1. It misses any opening message the bot has sent. The message is only visible after the user sends a different message.
2. It queries for watermark of 'undefined.' See screenshot.

![image](https://cloud.githubusercontent.com/assets/5069805/20579833/d79e1264-b183-11e6-824a-3ec080f3eed4.png)

**Comment by billba** [comment] 2016-11-24 00:41
I'm not sure how old the code is that you're testing against. I rewrote the GET loop late last week. As a result:

1. I think the ?watermark=undefined problem has gone away.
2. I'm seeing OPTIONS less often - every fourth of fifth GET. I need to delve into the RxJS ajax code and see what prompts these.
3. I can't speak to the missing-opening-message problem.

**Comment by billba** [comment] 2016-11-24 12:51
I fixed the ?watermark=undefined problem. Do you think it could have been causing the first problem (which I can't reproduce)? In other words, if we were passing watermark=undefined, might DirectLine have failed to give us the first message?

**Comment by dandriscoll** [comment] 2016-11-24 20:42
I bet so. We just treat the watermark as a string and 'undefined' would skip all messages.

**Comment by billba** [comment] 2016-11-24 21:41
In that case I'm surprised it ever worked at all. Let's wait and see if this recurs.

**Comment by billba** [comment] 2016-12-12 14:08
Closing unless/until someone else sees this happening.

**Closed by billba** 2016-12-12 14:08 UTC
