### ISSUE TITLE
User Name coming empty in activity.From.Name

### ISSUE THREAD

**Issue by rachita0311** [Microsoft/BotFramework-WebChat#643] opened 2017-08-18 05:07 UTC
I am initializing my chat bot . I am sending username as 'Agent Bot'👍 

  var user = {
                id: 'userid1',
                name: 'AgentBot '
                };
            
            var bot = {
                id: params['botid'] || 'botid',
                name: params["botname"] || 'botname'
            };

            window['botchatDebug'] = params['debug'] && params['debug'] === "true";

            var botConnection = new BotChat.DirectLine({
                secret: params['s'],
                token: params['t'],
                domain: params['domain'],
                webSocket: params['webSocket'] && params['webSocket'] === "true" // defaults to true
            });

            BotChat.App({
                botConnection: botConnection,
                user: user,
                bot: bot
            }, document.getElementById("BotChatGoesHere"));

Now I need to get the username information in my bot code to send a welcome message to user with username. I am trying to fetch username from message.From.Name . But this is giving me empty value. Please guide me how to get the username in Bot code.
private async Task<Activity> HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                //await CallDirectLine();
                IConversationUpdateActivity iConversationUpdated = message as IConversationUpdateActivity;
                if (iConversationUpdated != null)
                {
                    ConnectorClient connector = new ConnectorClient(new System.Uri(message.ServiceUrl));

**Comment by billba** [comment] 2017-08-18 19:32
See https://github.com/Microsoft/BotFramework-WebChat/issues/536 for a discussion and workaround. Closing as duplicate.

@dandriscoll here is your weekly notification that this is our #1 issue report.

@danmarshall we should probably document this workaround in the README, maybe in an "Identity" section that talks about the DL identity system or lack of same.

**Closed by billba** 2017-08-18 19:32 UTC

**Comment by danmarshall** [comment] 2017-08-18 22:19
@rachita0311 see [this C# sample fro getting the members of a conversation](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-GetConversationMembers)

**Comment by billba** [comment] 2017-08-18 22:27
@danmarshall the problem is that no messages have been sent, so the bot has no user ID to access.

**Comment by danmarshall** [comment] 2017-08-18 22:33
@billba OIC. Purely speculating, could this be solved if the WebChat sent a backchannel message upon startup?

**Comment by billba** [comment] 2017-08-18 23:53
That is the workaround linked to above, but it still requires custom code on the bot. The correct solution is to pass the user identity when connecting to the conversation. But that is a protocol level change.

If you're suggesting building the workaround into WebChat, I'm disinclined to institutionalize a hack.
