### ISSUE TITLE
[Accessibility][Screen Reader][NVDA] - Screen reader ignores text messages on hover.

### ISSUE THREAD

**Issue by Valentyn-Chornovol** [microsoft/BotFramework-WebChat#3002] opened 2020-03-11 09:35 UTC
![sreenreader](https://user-images.githubusercontent.com/62014745/76402578-499fc480-638c-11ea-8c20-44d3a38be41b.gif)

**Actual result:**
The screen reader ignores text messages on hover.

**Expected result:**
The screen reader will read text messages on hover.

**Repro Steps:**
1. Turn on NVDA.
2. Open https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/ in Chrome.
3. Type and send a message.
4. Hover the cursor on the message.

**Comment by corinagum** [comment] 2020-04-01 20:47
@Valentyn-Chornovol
Sorry for the late reply. I am able to reproduce this issue. There have been several accessibility bugs filed recently, and our current milestone will be resolving several bugs. I am bringing this up with our accessibility team and I will report back.

**Comment by compulim** [comment] 2020-04-20 21:30
Dupe of #3048.

**Closed by compulim** 2020-04-20 21:30 UTC
Labels: Accessibility, Bot Services, Bug, External: Dynamics 365, customer-replied-to, customer-reported
