### ISSUE TITLE
Separate the SuggestedActions and SendBox.

### ISSUE THREAD

**Issue by grimz11** [microsoft/BotFramework-WebChat#3299] opened 2020-07-10 03:35 UTC
Npm package version <b>botframework-webchat": "^4.9.0"</b>.

When you set the <b>hideSendBox = true</b>.
The suggested actions are also hidden. Or is there an alternative to this?

We have this instance that we need to hide the sendbox when there are suggested actions. Maybe it's a good idea to separate them?
![image](https://user-images.githubusercontent.com/53614600/87114670-bb890b80-c2a3-11ea-9dcf-f7767f489a92.png)

**Comment by compulim** [comment] 2020-07-10 17:15
Agree it should be allowed to hide the text box without the suggested actions.

This is dupe of #2427. @grimz11 could you vote on that bug?

**Closed by compulim** 2020-07-10 17:15 UTC
Labels: Bot Services, Enhancement, customer-reported

**Comment by grimz11** [comment] 2020-07-13 01:39
Yea, Okay2.
