### ISSUE TITLE
Up arrow to reproduce last line

### ISSUE THREAD

**Issue by aes421** [Microsoft/BotFramework-WebChat#1419] opened 2018-06-22 15:00 UTC
When testing bots I find that I constantly type the same sentences into the emulator while I tweak the code.

It would be useful if the emulator worked similar to command prompt where clicking the up arrow would auto populate the last submitted sentence.  This would greatly reduce the amount of typing and increase efficiency when developing bots.

**Comment by compulim** [comment] 2018-11-30 19:51
This is dupe of #1091. Please track over there. Will tag it appropriately.

**Closed by compulim** 2018-11-30 19:51 UTC

**Comment by compulim** [comment] 2018-11-30 19:59
@vishwac @mewa1024 I owe you guys on this one since 4.0. I will make it in even it's marked with lower priority.
