### ISSUE TITLE
Bot Framework Webchat mic not working on iOS 

### ISSUE THREAD

**Issue by shubhamchawla** [Microsoft/BotFramework-WebChat#996] opened 2018-05-30 07:31 UTC
I'm have a webchat conrol for a bot that that is up and running and working well in Chrome & Edge for windows.  But it is not working on Chrome & Safari on iOS (iPhone and iPad).

We need this working on an iPhone & iOS.

![chrome](https://user-images.githubusercontent.com/7473220/40705784-78bde078-6409-11e8-8d82-211d72978d0d.png)
![safari](https://user-images.githubusercontent.com/7473220/40705787-7936c39e-6409-11e8-8f8c-08edc4077c58.png)

**Comment by compulim** [comment] 2018-05-30 17:02
Dupe of #995. Closing this for now.

**Closed by compulim** 2018-05-30 17:02 UTC
Labels: investigating
