### ISSUE TITLE
using speech service mic is not working as expected

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2406] opened 2019-09-18 15:06 UTC
Hi All,

i am showing the code snippet that how i am initializing the bot as well as speech service(please review and let me know if it is wrong or i am doing it in wrong way). i am also facing issue in speech service and issues are described below:-
```javasctipt
(async function() {
const config = {method: "POST",headers: {Authorization:"Bearer  **DLConnection here**"}};
const res = await fetch("https://directline.botframework.com/v3/directline/tokens/generate",config);
const subscriptionKey = "**Speech subscription**";
const { token } = await res.json();
window.WebChat.renderWebChat({
	directLine:window.WebChat.createDirectLine({ token }),
	webSpeechPonyfillFactory: await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
		region: "**Specify location**",
		subscriptionKey
	}),
	userID: "**passing user ID**",
	username: "**passing user Name**",
	locale: "en-US"},
	document.getElementById("webchat"));
})().catch(err => console.error(err));
```
**issues facing:-**
1. whatever customization i did got vanished like:- added header is removed.
2. speech service is working but after clicking on mic , browser ask to allow and i allowed it then said "hi" and bot responded.
3. again automatically after the speech message of bot got over it is not stopping the listening and again asked for allowing mic to say somthing.
4. if i block or directly close the poup of browser then again clicking on mic is just disappeared the webchat and error came as:-**" Speech recognition is not supported" and "| AudioSourceErrorEvent | metadata: {} | audioSourceId: E1A095CF21D94DAAB7970E8D4AAB5896 | error: Error occurred during microphone initialization: NotAllowedError: Permission denied"**

**Comment by tdurnford** [comment] 2019-09-18 19:03
@Bradrajkumar What browser are you using and what bundle and version of Web Chat are you using?

**Comment by Bradrajkumar** [comment] 2019-09-19 06:11
right now i am using only chrome and i am having webchat package downlaoded from the link:- https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js" last month and using it locally. as i wanted this to be on IE as well as chrome.

**Comment by corinagum** [comment] 2019-09-19 22:00
@Bradrajkumar it seems to me that you are experiencing the expected behavior of the speech service when you do not accept the permissions request to access the microphone. To be able to speak to the bot, you will have to give permission for the browser to access the microphone. I am closing this issue as question answered.

**Closed by corinagum** 2019-09-19 22:00 UTC
Labels: Bot Services, Bug, Pending, customer-replied-to, customer-reported

**Comment by Bradrajkumar** [comment] 2019-09-23 12:51
If it is the expected behaviour then it should also work on **safari browser** in **iphone** as well as on **pc**.
mic option is coming and onclick of mic button it is activating as well as listening is also happening text but the response which is having text is not doing TTS functonality there.

please suggest me for this option also.

here is my final code which i have written working on chrome :- 

async function(){
	const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', {method: "POST",headers: {Authorization:"Bearer + **DirectlineConnection**}});
	const {token} = await res.json();
	const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
        region: 'specific region',
        subscriptionKey: "**subscription key**"
	});
	const store = window.WebChat.createStore();
	window.WebChat.renderWebChat({
		directLine: window.WebChat.createDirectLine({token}),
		webSpeechPonyfillFactory,
		store,
		userID: "**user ID**",
		username: "**username**",
		locale: "en-US"
	},document.getElementById('webchat'));
document.querySelector('#webchat > *').focus();
})().catch(err =>console.error(err));

**Comment by Bradrajkumar** [comment] 2019-09-25 10:28
#2425 please follow the new bug opened for safari on iOS.

**Comment by Bradrajkumar** [comment] 2019-11-20 10:34
> @Bradrajkumar it seems to me that you are experiencing the expected behavior of the speech service when you do not accept the permissions request to access the microphone. To be able to speak to the bot, you will have to give permission for the browser to access the microphone. I am closing this issue as question answered.

not accepting to use microphone or speech option should not vanish the bot completely, atleast it should be available for chatting.
i am attaching 3 steps of testing and experienced this, please look into this.
step 1:- asking to allow and i clicked on "block".
![Screenshot (435)](https://user-images.githubusercontent.com/34365788/69231390-00462200-0baf-11ea-88d3-a89239a46c1b.png)
step 2:- its blocked but i clicked on mic as it is still showing enabled.
![Screenshot (436)](https://user-images.githubusercontent.com/34365788/69231426-0d631100-0baf-11ea-931a-1829a17837c6.png)
step 3:- clicking on mic will clear the complete webchat.
![Screenshot (437)](https://user-images.githubusercontent.com/34365788/69231449-19e76980-0baf-11ea-91b0-6e5daafebcf1.png)

**Comment by compulim** [comment] 2019-11-20 19:17
@Bradrajkumar the bug you mentioned just here is legit. Since this thread is closed and the original bug is different than the latest one, I just opened a new bug (https://github.com/microsoft/BotFramework-WebChat/issues/2619). Please track it over there.
