### ISSUE TITLE
HeroCard render in IE 11 have a lot of space at bottom

### ISSUE THREAD

**Issue by den19980107** [microsoft/BotFramework-WebChat#3179] opened 2020-05-28 07:39 UTC
![webchat issue](https://user-images.githubusercontent.com/23033004/83112855-59ac8200-a0f9-11ea-9cad-072f7e641754.PNG)

**Comment by compulim** [comment] 2020-05-29 18:30
There is a bug in IE11 that an oversized image will be taking up unnecessary space.

Can you make sure the image is properly scaled?

**Comment by den19980107** [comment] 2020-06-01 02:00
this is the sample from [https://microsoft.github.io/BotFramework-WebChat/01.getting-started/c.es5-bundle/](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/c.es5-bundle/)

when only show image, no space at bottom
- **only show image**
![截圖 2020-06-01 上午9 36 24](https://user-images.githubusercontent.com/23033004/83368866-ea7ea880-a3ec-11ea-9204-2037b15f8d1b.png)

but when show the hero card with image, the space is showing up
- **show hero card and image**
![hero card 空白](https://user-images.githubusercontent.com/23033004/83368868-ece10280-a3ec-11ea-81d2-34bc6b34bf14.gif)

i think the image is scaled properly, the problem may be something else?

thanks for reply 👍

**Comment by a-b-r-o-w-n** [comment] 2020-06-11 18:06
@compulim do we need to investigate further?

**Comment by corinagum** [comment] 2020-06-23 19:27
@den19980107, are you still running into this problem? This is a duplicate of the issue https://github.com/microsoft/BotFramework-WebChat/issues/1944 

This is not a Web Chat issue, but an Adaptive Cards one. The temporary fix on the bot's side is to adjust the height of your image to one that fits inside the adaptive card. 

The Adaptive Cards bug I filed is here: 
https://github.com/microsoft/AdaptiveCards/issues/3056
I recommend leaving a comment saying that you are also running into this on your bot. :)

**Comment by corinagum** [comment] 2020-06-23 19:36
The fix for Web Chat samples is to fix the size of the image of the herocard on Mock Bot, but priority would be P2 or P3.

**Comment by den19980107** [comment] 2020-06-24 01:25
@corinagum yes, i’m stiil  running in this issue,i knew that fix the size of the image will fix this issue ,
 but in my case ,my web chat width is dynamic, so fix the image size is not the best way to fix this issue.

thank for reply 👍

**Closed** 2020-06-24 16:37 UTC
Labels: Bot Services, Duplicate, customer-replied-to, customer-reported
