### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by WHJmaxne** [microsoft/BotFramework-WebChat#2636] opened 2019-11-26 03:22 UTC
![image](https://user-images.githubusercontent.com/24425190/69596784-bb9f0880-103e-11ea-9b4f-72eec3c2d75b.png)
![image](https://user-images.githubusercontent.com/24425190/69596818-de312180-103e-11ea-906f-7026fbb40825.png)

**Comment by corinagum** [comment] 2019-11-26 18:14
Please fill out our bug report form and include the requested information such as reproduction steps and Web Chat version so that we can help you with this bug.

**Comment by compulim** [comment] 2019-11-27 23:21
Since Chrome network tab do not report the actual response of 400 on WSS, can you use Fiddler or other debugging proxy to troubleshoot the problem?

I guess the problem is the language set to use for speech recognition is `zh`, instead of [supported languages](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support), e.g. `zh-CN`, `zh-HK`, and `zh-TW`.

**Comment by WHJmaxne** [comment] 2019-11-28 07:14
![image](https://user-images.githubusercontent.com/24425190/69784626-3019a900-11f1-11ea-9b36-f302ed8ede3b.png)
This is my code,Using subscriptionkey or authorizationtoken will get the same error,I set the language to zh-CN, but it is still zh at the time of request. How can I set the language? Thanks

**Comment by WHJmaxne** [comment] 2019-11-28 07:28
When I use Firefox, everything is OK

**Comment by nt-7** [comment] 2019-11-29 11:47
Hi @WHJmaxne,
Could you try to add locale property as below when calling renderWebChat?

_locale: 'zh-CN'_

```
renderWebChat({
    directLine: window.WebChat.createDirectLine({ secret }),
    language: 'zh-CN',
    webSpeechPonyfillFactory: window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
         subscriptionKey: 'XXX',
         region: 'XXX'
    }),
    locale: 'zh-CN'
}, document.getElementById('webchat'));
```

**Comment by WHJmaxne** [comment] 2019-11-30 03:39
> Hi @WHJmaxne,
> Could you try to add locale property as below when calling renderWebChat?
> 
> _locale: 'zh-CN'_
> 
> ```
> renderWebChat({
>     directLine: window.WebChat.createDirectLine({ secret }),
>     language: 'zh-CN',
>     webSpeechPonyfillFactory: window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
>          subscriptionKey: 'XXX',
>          region: 'XXX'
>     }),
>     locale: 'zh-CN'
> }, document.getElementById('webchat'));
> ```

Add locale: 'zh CN' to get the same error

**Comment by corinagum** [comment] 2019-12-02 17:53
@WHJmaxne thank you for filing this issue. Based on the information above I was able to reproduce on Mock Bot. I am adding the Investigate tag so our team can figure out what is causing the problem.

**Comment by corinagum** [comment] 2020-01-06 20:34
@WHJmaxne, thank you for your patience. 

I did some investigation and found out that this is due to the Chrome language settings. The default 'Chinese' setting (no demarcation for Traditional, Simplified, or Hong Kong) sets the language as `zh`, which is not a supported language in Cognitive Services. 

![image](https://user-images.githubusercontent.com/14900841/71846838-5a784500-3080-11ea-98f8-606f558161c6.png)

I tested this out by changing the language of my Chrome browser to Chinese (Traditional, `zh-TW`) and I got speech to work on Web Chat:

![image](https://user-images.githubusercontent.com/14900841/71846916-88f62000-3080-11ea-8e52-5b905a9c5f71.png)


In order for speech to work on the browser, you will have to change the display language in Chrome from `zh` to `zh-xx`, 

Please try this out and let us know your updates. For now, I will close this as resolved.

**Closed by corinagum** 2020-01-06 20:34 UTC
Labels: Bot Services, Bug, P0, customer-replied-to, customer-reported
