### ISSUE TITLE
BotFramework-WebChat only for showing chat history

### ISSUE THREAD

**Issue by yogimogi** [microsoft/BotFramework-WebChat#4037] opened 2021-08-23 04:46 UTC
Use case is this: We keep all conversations in a data store and then want to use webchat for showing historical chat data in reports. We were able to get this to work by feeding webchat a list of Activity objects.

Just that, it still needs a valid **domain** URL pointing to Azure Channel's Registration Service. If you don't provide a valid value, it shows "connection error" message. Is there a way to use tell webchat to not worry about domain URL?

**Comment by iMicknl** [comment] 2021-08-23 10:54
Possible duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/3971. I had a similar request for use with https://github.com/iMicknl/powerbi-botframework-chat-transcripts.

**Comment by yogimogi** [comment] 2021-08-23 10:57
duplicate of #3971. Closed.

**Closed** 2021-08-23 10:57 UTC
Labels: customer-reported, Bot Services, feature-request
