### ISSUE TITLE
Different UserId for ConversationUpdate and Message

### ISSUE THREAD

**Issue by punitganshani** [Microsoft/BotFramework-WebChat#619] opened 2017-08-04 13:26 UTC
The webchat is hosted using standard code to define the user id as below,

```
var user = {
    id: params["userid"] || "myuser",
    name: params["username"] || "You"
};
```

When the conversationUpdate event is triggered, the `activity.From.Id` is something cryptic (like `Kq3YtJ7KkL7upmnPpzke`) instead of `myuser` until the user sends a message to the bot. 

Once the user sends a message to the bot, `activity.From.Id` gets assigned to `myuser`. Is this because `ConversationUpdate` is a system message. If so, in the emulator, for both system message and normal activities, we get `default-user` whereas for WebChat, the behavior is different.

**Comment by billba** [comment] 2017-08-04 14:39
Duplicate of https://github.com/Microsoft/BotFramework-WebChat/issues/536 - see there for a workaround using backchannel.

@danmarshall this is probably our most frequently asked question. It would be great to update the docs to talk about how to get around this specific shortcoming of Direct Line. @dandriscoll FYI.

**Closed by billba** 2017-08-04 14:39 UTC
