### ISSUE TITLE
Internet explorer not rendering Buttons in card Properly (.ac-pushbutton)

### ISSUE THREAD

**Issue by keshavnagpal** [Microsoft/BotFramework-WebChat#1836] opened 2019-03-25 12:39 UTC
I have tried this with 
master/webchat-es5.js and
latest/webchat-es5.js
but the button doesn't adapt to the text size inside it

in chrome
![image](https://user-images.githubusercontent.com/10372931/54920319-f3dace00-4f28-11e9-9f44-45ab11c47b8e.png)

![image](https://user-images.githubusercontent.com/10372931/54920378-1967d780-4f29-11e9-9849-8779065370bd.png)

in IE
![image](https://user-images.githubusercontent.com/10372931/54920357-08b76180-4f29-11e9-9258-bc6d20757296.png)

![image](https://user-images.githubusercontent.com/10372931/54920395-24bb0300-4f29-11e9-991c-53e7a2326a6c.png)

**UPDATE** :

Looks like removing flex-basis property fixes the issue
$(".ac-pushButton").css("flex-basis", "");

**Comment by corinagum** [comment] 2019-03-25 16:18
Hi @keshavnagpal, this appears to be a dupe of https://github.com/Microsoft/BotFramework-WebChat/issues/1493

Please use HTML5 and it should fix this problem.

**Closed by corinagum** 2019-03-25 16:18 UTC
Labels: Duplicate
