### ISSUE TITLE
 The brand needs the Avatar of the Bot to be a square instead of a circle

### ISSUE THREAD

**Issue by eduardmartos** [microsoft/BotFramework-WebChat#2882] opened 2020-02-05 09:00 UTC
**Describe the suggestion or request in detail**

The brand needs the Avatar of the Bot to be a square instead of a circle

**Describe alternatives you have considered**

Currently we are changing this style with jQuery command:

 ```
jQuery('#webchat').find('div').filter('.avatar').not('.from-user').css('border-radius', '0%')
 ```
But sometimes webchat is not rendering as we like and happens this:

![image](https://user-images.githubusercontent.com/54709623/73826050-641ad700-47fd-11ea-9311-255ceb2ec9c3.png)

and of course it is not efficient to do so

**Additional context**

I would like to use new styleOptions like:
**botAvatarShapeAsCircle** _(boolean)_
**userAvatarShapeAsCircle** _(boolean)_

```
const styleOptions = {
	...
	botAvatarImage: baseUrl.concat('/img/avatar_bot_squ.png'),
	botAvatarInitials: 'BOT',
	botAvatarBackgroundColor: 'white',
	botAvatarShapeAsCircle: false,
	userAvatarImage: webchatItem.userAvatar,
	userAvatarInitials: 'USER',
	userAvatarBackgroundColor: 'white',
	userAvatarShapeAsCircle: true,
	...
}
```
With an implementation similar to this on createAvatarStyle... :
```
export default function createAvatarStyle({
  accent,
  avatarSize,
  botAvatarBackgroundColor,
  botShapeAsCircle,
  primaryFont,
  userAvatarBackgroundColor
}) {
  var borderRadiusValue = '50%'
  if !botShapeAsCircle borderRadiusValue = 'inherit'
  
  return {
    alignItems: 'center',
    borderRadius: borderRadiusValue,
	...
```

**Comment by tdurnford** [comment] 2020-02-05 18:19
@eduardmartos You can currently modify the style set to change the avatars border radius. Take a look at the code snippet below. 

### Screenshot
![image](https://user-images.githubusercontent.com/17039790/73870418-e658ca80-4800-11ea-8a35-349a41cece20.png)

### Web Chat v4.7.1

```javascript
const styleOptions = {
  botAvatarImage:
    'https://docs.microsoft.com/en-us/azure/bot-service/v4sdk/media/logo_bot.svg?view=azure-bot-service-4.0',
  botAvatarInitials: 'BF',
  userAvatarImage: 'https://github.com/compulim.png?size=64',
  userAvatarInitials: 'WC'
};

const styleSet = window.WebChat.createStyleSet(styleOptions);

styleSet.avatar = {
  ...styleSet.avatar,
  borderRadius: 0
};

window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token }),
    styleSet
  },
  document.getElementById('webchat')
);
```

@corinagum @compulim  Should we consider adding `userAvatarBorderRadius` and `botAvatarBorderRadius` to the default style options?

**Comment by corinagum** [comment] 2020-02-05 18:35
@tdurnford my vote is yes :)

**Comment by eduardmartos** [comment] 2020-02-05 18:44
Ok. If I understand your code...

With this:

const styleSet = window.WebChat.createStyleSet(styleOptions);

styleSet.avatar = {
  ...styleSet.avatar,
  borderRadius: 0
};

you can override all the values you need of every styleSet?
And the process is always the same?

styleSet.[ClassName] = {
[“ThreeDots”]styleSet.[ClassName],
cssAttributeToOverride1: newCssAttributeValue1,
cssAttributeToOverride2: newCssAttributeValue2,
“and so on...”
};

I assume that with this override that you are proposing we change user and bot avatars at same time... So if I want user to be a circle or another geometry I can use photoshop to create it as png image with transparent background.

That sounds nice!
But for other more basic implementations it could be nice to have the two additional styles that your are proposing:

botAvatarBorderRadius
userAvatarBorderRadius

**Comment by tdurnford** [comment] 2020-02-05 18:51
@eduardmartos If you're overriding the style set, you can add the style depending on if it's from the user or not. Adding the style options is a better option though. 
### Screenshot
![image](https://user-images.githubusercontent.com/17039790/73872929-7ac52c00-4805-11ea-8bc1-c4f6ffc256f8.png)

### Style Set
```javascript
styleSet.avatar = {
  ...styleSet.avatar,
  '&:not(.from-user)': {
    borderRadius: 0
  },

  '&.from-user': {
    borderRadius: '50%'
  }
};
```

**Comment by corinagum** [comment] 2020-02-05 18:55
should we close this as duplicate in favor of #1977?

**Comment by tdurnford** [comment] 2020-02-05 18:56
Closing as dupe of #1977

**Closed by tdurnford** 2020-02-05 18:56 UTC
Labels: Bot Services, Enhancement, Pending, customer-replied-to, customer-reported
