### ISSUE TITLE
Clicking on microphone after blocking microphone will throw JavaScript error - related to #3666

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2619] opened 2019-11-20 19:15 UTC
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/69269715-7a15e580-0b86-11ea-9bf3-faee5ca56e9f.png)

## Version

`4.6.0`

## Describe the bug

After the microphone access is blocked in the browser (Chrome), clicking on the microphone button again will throw JavaScript error saying "Speech recognition is not supported".

Few things to do:

- [ ] Investigates why it is causing an uncaught exception (i.e. clearing out the screen)
- [ ] After the first block, investigates if we could disable microphone button for the session (turn it into envelope button)
- [ ] Also, investigates why the uncaught exception cannot be contained within the connectivity status

## To Reproduce

1. Open Chrome in incognito mode.
1. Load Web Chat 4.6.
1. Click on microphone button.
1. When the browser asked for microphone access, click "Deny".
1. Click the microphone button again.

## Expected behavior

There are two expected behaviors, either one will work:

1. After step 4, Web Chat switch off the microphone button by turning it into an envelope button.
1. After step 5, Web Chat do nothing.

## Additional context

[Bug]

**Comment by Bradrajkumar** [comment] 2020-02-13 09:13
hi Team,

still onclick on block button in popup and again clicking on mic button is vanishing the webchat.
here is the screnshot.
![Screenshot (18)](https://user-images.githubusercontent.com/34365788/74418931-2f4af780-4e6f-11ea-9aa7-4f4f62013374.png)
![Screenshot (19)](https://user-images.githubusercontent.com/34365788/74418939-3114bb00-4e6f-11ea-975f-3fbf4450f3c0.png)

**Comment by corinagum** [comment] 2021-01-20 00:17
possibly fixed by #3666

**Comment by cwhitten** [comment] 2021-01-21 00:25
closing as a dupe of https://github.com/microsoft/BotFramework-WebChat/issues/3411

**Closed by cwhitten** 2021-01-21 00:25 UTC
Labels: Area: Speech, Bug, P1, backlog, front-burner, needs-scheduling
