### ISSUE TITLE
Chat history Persistence in WebChat window

### ISSUE THREAD

**Issue by BhargavJanardhan** [Microsoft/BotFramework-WebChat#843] opened 2018-01-17 12:09 UTC
Hello Guys,

I have a requirement of maintaining chat history and loading them back in a window after a (page refresh)/(close and opening the window). 

**ISSUE :** Buttons/carousel/Adaptive cards/Hero Cards  events/ properties are not loading(ie; when i click on button or any event, actions are not happening).
**Images**: Bot chat window HTML controls
![image](https://user-images.githubusercontent.com/27334482/35041430-c3765de2-fbaa-11e7-8fb6-fb2c748d8d7f.png)
Bot :
![image](https://user-images.githubusercontent.com/27334482/35041459-d9386c60-fbaa-11e7-8c90-9422428e4b4c.png)

**DESCRIPTION:** 
In order to achieve the requirement i had 2 options.
1. **BotFramework _ Directline JS** : 
https://github.com/Microsoft/BotFramework-DirectLineJS
I guess using this we can only get conversation history and where we couldn't load back the conversation history in chat window. 
Though we can get the conversation history we have to send all the messages to bot again.

So i had opted 2nd one.

2. **Store the html controls and Load it in the bot div**: When sending or receiving  message action is happening from bot am storing the html controls(i.e;  controls under **wc-message-groups** class in local storage) and binding back to the div on page load if data exists.

This works for me to show conversation history in a chat window. But I am not able to get the events/actions for buttons.

Can we do this with Directline JS or is there any option to load properties/events to controls?
Please help me with this issue.

Thanks in Advance
-

**Comment by billba** [comment] 2018-01-22 15:56
Injecting directly into HTML is a one-way trip. React has no idea it's there and so will not, well, react to it. So that is not the right solution.

We are debating various solutions for injecting history into Web Chat [here](https://github.com/Microsoft/BotFramework-WebChat/pull/615) but right now do not have a working solution.

Closing as duplicate of #615 and #365.

**Closed by billba** 2018-01-22 15:56 UTC

**Comment by pratyushdhanuka** [comment] 2018-03-08 07:41
I have implemented the 2nd option for a long time now, but eagerly waiting for the implementation of Option #1
@BhargavJanardhan, @billba  any suggestions on where should we use it, I used it in the
botchat.js file inside
`function p(t)`
where we validate the type of action, else throw 
`error("Actions may not have an undefined "type" property. Have you misspelled a constant?")`
saving conversation in session
```
if (t && (t.type == "Send_Message_Succeed" || t.type == "Receive_Message")) {
      saveConversation();
}
```
still understanding the flow in botchat.js so would be nice if you guys can point to a better location for my code

**Comment by BhargavJanardhan** [comment] 2018-03-08 13:48
@pratyushdhanuka When some action is happening in the chat window(i.e; when we send a message or when we get a message) we must store the data. Below are the steps.
**Storing conversation from chat window to local storage.**
1. We must stringify the html(**contents as I have marked in the screenshot**) and store in local storage.
2. Save the html in local storage whenever you send or receive a message.
**Retrieve conversation and appending in Chat window**
1.  After loading the Bot window get the conversation stored in local storage.
2. Parse the data to html and append to the class **wc-message-groups**.
