### ISSUE TITLE
Bot avatar image is not coming if latest webchat.js is used

### ISSUE THREAD

**Issue by Monomoy88** [microsoft/BotFramework-WebChat#3602] opened 2020-11-12 09:53 UTC
Bot avatar image used to appear till the version 4.11.0 is released.
Here is my code
 ```
const styleSet = window.WebChat.createStyleSet({
                botAvatarImage: <<some image path>>,
                botAvatarInitials: 'EO',
                userAvatarImage: <<some image path>>,
                userAvatarInitials: 'U',
                bubbleBackground: 'rgba(220,220,220, .3)',
                bubbleFromUserBackground: 'rgba(255, 255, 200,.3)',
            });
```
In my html I have referred below uri:
https://cdn.botframework.com/botframework-webchat/latest/webchat.js

If I change it to https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js then avatar image is coming but when I changed the version to 4.11.0 or latest then images are not coming.

**Comment by stevkan** [comment] 2020-11-12 23:46
@Monomoy88, it does appear that some regression was introduced with 4.11.0 as I am able to repro the issue when using `createStyle()`.

That being said, the recommended (and supported) method for changing Web Chat's style is to use `styleOptions` (see below). You can read more about why in this doc section, [Overriding `createStyleSet`](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization/b.idiosyncratic-manual-styles#overriding-createstyleset).

```js
const styleOptions = {
    botAvatarImage: <<some image path>>,
    botAvatarInitials: 'EO',
    userAvatarImage: <<some image path>>,
    userAvatarInitials: 'U',
    bubbleBackground: 'rgba(220,220,220, .3)',
    bubbleFromUserBackground: 'rgba(255, 255, 200,.3)'
};

window.WebChat.renderWebChat(
    {
        directLine: directLine,
        styleOptions: styleOptions
    },
    document.getElementById( 'webchat' )
);
```

**Comment by stevkan** [comment] 2020-11-12 23:59
@corinagum - needing triage

**Comment by corinagum** [comment] 2020-11-13 18:52
As @stevkan pointed out, I also confirmed that this is some kind of behavioral regression from 4.10.1. However, we don't guarantee lack of breaking changes in `createStyleSet`, and I strongly recommend using `styleOptions` as shown above. 

It looks like the regression happened in PR https://github.com/microsoft/BotFramework-WebChat/pull/3543 My natural assumption is that the break was unintentional, but since this is a not officially supported method, I can't be entirely sure. @compulim is unavailable for the next few weeks and I won't be able to confirm without speaking with him. 

This issue is resolved with the recommended code provided. However, I will add the investigation label and assign to compulim to confirm whether this behavior is breaking or not. From there we can see if any fixes need to be made.

**Comment by corinagum** [comment] 2020-11-30 20:48
I confirmed with @compulim that this is an intended breaking change. Previously, avatar images were set with css (background-image), but now are set in HTML with <img>. Please use `styleOptions` as indicated above.

**Closed by corinagum** 2020-11-30 20:48 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported, needs-team-attention
