### ISSUE TITLE
Custom voice (or speech?) is getting picked up in text box but not displayed in the chat history

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2560] opened 2019-11-05 09:29 UTC
## Screenshots
![image](https://user-images.githubusercontent.com/11289456/68191099-c123a880-ffd4-11e9-83fa-6d48a304c379.png)

## Describe the bug
whatever the user says is being captured in the input text box but it's not being propagated to the chat window.

**Comment by corinagum** [comment] 2019-11-05 17:32
Please use our bug report template to provide the information we will need in order to help you.


What, if any, are your console errors?

**Comment by prashanthsridhar** [comment] 2019-11-06 14:29
Hi Corina,
**steps to reproduce:**
The snippet is as folows:
selectVoice: () => ({ voiceURI: 'sample' }),
            webSpeechPonyfillFactory: await this.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
                region: 'westus2',
                speechSynthesisDeploymentId: 'sample',
                subscriptionKey: 'sample'

**Console output**
![image](https://user-images.githubusercontent.com/11289456/68306518-b26dec00-00cf-11ea-8332-04ca9547aad7.png)

            })

**Comment by corinagum** [comment] 2019-11-06 18:21
@compulim assigning to you (since I don't have a custom voice to test with xD)

**Comment by prashanthsridhar** [comment] 2019-11-07 07:16
### Additional Information
botConnection:-
```
const botConnection = new this.WebChat.createDirectLine({
            token:"123123",

            webSocket: true,
            styleOptions:styleOptions
        });
```

verbatim code without keys:
```
this.WebChat.renderWebChat({
            
            styleOptions: {
                

                bubbleFromUserBackground: '#F16236',
                bubbleFromUserTextColor: 'White',


            },
            directLine: botConnection,
            language: 'en-GB',
            chatTitle: false,
            userID: "user",
            name: "user",
            sender: "user",    
            receiver: "user",

            selectVoice: () => ({ voiceURI: 'name' }),
            webSpeechPonyfillFactory: await this.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
                region: 'westus2',
                speechRecognitionEndpointId: '12123123123123213',
                speechSynthesisDeploymentId: '12312312312312312',
                subscriptionKey: '123123123123'
            })
            
        },

            this.botWindowElement.nativeElement
        );

```
### Description:
We are using custom speech and whatever we say is getting picked up and displayed in the text area, but it is not going to the chat window. If we type the text and hit enter it moves to the chat window .

**Comment by mountju** [comment] 2019-11-21 12:06
have the same issue

**Comment by prashanthsridhar** [comment] 2019-11-27 11:06
Hi @compulim, this is a major blocker for us. It will be really helpful if this is picked up ASAP.

**Comment by corinagum** [comment] 2019-12-06 21:37
@prashanthsridhar, sorry for the delay. I've managed to test both custom voice and custom speech and do not encounter any errors. Could you provide more detail about your Cognitive Services set up so that we can try to reproduce the problem? First it would be great if you could clarify which is causing you issues, since your bug reports custom voice originally, but you are using both in your example code. 

Do you have a deployed source that I could take a look at?

**Comment by prashanthsridhar** [comment] 2019-12-07 04:42
Hi @corinagum, we are using both.The issue that we faced was with custom speech

**Comment by prashanthsridhar** [comment] 2019-12-09 11:06
Hi @mountju , did you get a workaround or are you still facing the issue? Are you using it in an angular app as well?

**Comment by mountju** [comment] 2019-12-09 12:54
> Hi @mountju , did you get a workaround or are you still facing the issue? Are you using it in an angular app as well?

hi @prashanthsridhar  
I'm using it in Angular App as well

**Comment by corinagum** [comment] 2019-12-09 18:06
@prashanthsridhar it would be great if you could check out the latest bits. Please check out our `Contributing.md` guidelines, which will tell you have to build the project. After you run `npm build`, you can take out the webchat file from `packages/bundle/dist/` and link that in your app to test latest bits.

Since you are both using Angular, we'll add that to the list of possible reasons that this bug is occurring. Please let me know the results of testing on latest bits, and we will go from there. :)

**Comment by prashanthsridhar** [comment] 2019-12-10 13:54
Hi @corinagum ,i compiled the js file from the repo  and used it in my app. The issue still exists.

**Comment by vishnuramero** [comment] 2019-12-11 09:57
I'm also facing the same issue, compiled the js file from the repo and used it in my app.

**Comment by corinagum** [comment] 2019-12-11 21:14
Thanks for reporting. @vishnuramero, are you also using an Angular App?

**Comment by vishnuramero** [comment] 2019-12-12 10:59
@corinagum  yes, the same issue, pure HTML file works but when I'm trying to integrate with angular speech to text is not working, it's recognizing the voice but not sending anything. is there any fix??

**Comment by manish-95** [comment] 2019-12-12 14:26
Hi, I am attempting the same in my angular App using the sample provided in [03.b.host-with-angular](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.b.host-with-angular). To this sample, I have tried to use my Azure Cognitive Service Speech subscription key to add Speech and voice capabilities following the instructions provided [here](https://github.com/microsoft/BotFramework-WebChat/blob/master/SPEECH.md#using-two-subscription-keys-for-speech-to-text-and-text-to-speech).

Although the speech to text service is activated and I am able to see the recognized text in my message window, the same is not sent to the Bot. Attaching a screenshot with the error that I see in the console window, with this setup.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/29098159/70720166-570bcb00-1d19-11ea-9bc7-b2b1e6751059.png)

**Comment by manish-95** [comment] 2019-12-12 14:46
**Update:** I have tried the same setup, but with Browser Speech instead of Cognitive Services, and I am able to see that the message picked up by STT is sent to the Bot successfully.

**Comment by vishnuramero** [comment] 2019-12-13 11:28
got it fixed, changes webchat.js file a bit.

created a new array and pushed the data from speech to the array.

![botchatCodeFix](https://user-images.githubusercontent.com/14331629/70797063-add0dd80-1dc9-11ea-9c97-ceacf5137b23.PNG)

**Comment by prashanthsridhar** [comment] 2020-01-02 10:23
@corinagum will this be added in a release or patch?

**Comment by corinagum** [comment] 2020-01-02 17:26
@prashanthsridhar at this time there's no plan for a patch. Unfortunately we still have to investigate the fix :/

**Comment by corinagum** [comment] 2020-01-02 23:21
Investigating this now! Hope to have updates soon.

**Comment by corinagum** [comment] 2020-01-08 18:07
Update: I have a repro of this problem and am hunting around looking for the source code. :) thanks for your patience!

**Comment by corinagum** [comment] 2020-01-09 19:04
I'm reassigning this to @compulim. I believe the fix is going to be in his package: https://github.com/compulim/web-speech-cognitive-services

**Comment by compulim** [comment] 2020-01-21 18:35
This is still scheduled for R8. Please stay tuned.

**Comment by compulim** [comment] 2020-02-27 23:13
Working on this one now. Repro on 4.7.1 and latest Angular@8.2.14.

**Comment by compulim** [comment] 2020-02-28 00:03
This bug is same as the one mentioned in our FAQs (#1961), i.e. speech will fail on Web Chat 4.6 when running under Angular, due to an unresolved bug in Angular that opened since 2016.

I have create a new bug with workaround steps, along with background and "how to fix".

Please follow the workaround steps in #2957.

**Closed** 2020-02-28 19:30 UTC
Labels: Bot Services, Bug, P0, R8, customer-replied-to, customer-reported
