### ISSUE TITLE
AdaptiveCard - Submit action - Additional properties not sent back to bot

### ISSUE THREAD

**Issue by baki32** [Microsoft/BotFramework-WebChat#942] opened 2018-04-16 14:33 UTC
Hi,
I need to pass multiple properties on the background from AdaptiveCard.Submit Action. I'm using BotBuilder C# SDK.

I used DataJson property however that one causes nothing to be rendered on the screen when using WebChat. I've found out that there's one more collection Available - AdditionalProperties, if I analyze incoming message in Fiddler / Emulator JSON sent to webchat contains custom properties however once it is selected by user post request doesn't contain it. I've tried to manually add it via postman and it was parsed in **Properties** property

Code that is used to render test adaptive card:
```csharp
var reply = (context.Activity as Activity).CreateReply();
                var msg = new AdaptiveCard
                {
                    Body =
                    {
                        new AdaptiveTextBlock
                        {
                            Text = "Test Title"
                        },
                        new AdaptiveContainer
                        {
                            Style = AdaptiveContainerStyle.Emphasis,
                            Items = new List<AdaptiveElement>
                            {
                                new AdaptiveTextBlock()
                                {
                                    Text = "Item 1"
                                }
                            },
                            SelectAction = new AdaptiveSubmitAction
                            {
                                Data = "Item 1"
                            }
                        },
                        new AdaptiveContainer
                        {
                            Style = AdaptiveContainerStyle.Emphasis,
                            Items = new List<AdaptiveElement>
                            {
                                new AdaptiveTextBlock()
                                {
                                    Text = "Item2 2"
                                }
                            },
                            SelectAction = new AdaptiveSubmitAction
                            {                                
                                Data = "Item 2 - I need this to be shown in webchat after user clicks",                                
                                AdditionalProperties = new Dictionary<string,object>{ { "BackroudProp","Value"} }
                            }
                        }
                    }
                };

                var att = new Attachment
                {
                    ContentType = AdaptiveCard.ContentType,
                    Content = msg
                };

                reply.Attachments.Add(att);
                var clnt = new ConnectorClient(new Uri(context.Activity.ServiceUrl));
                await clnt.Conversations.ReplyToActivityAsync(reply);
```

JSON sent to browser:
```javascript
{
  "type": "message",
  "timestamp": "2018-04-16T14:29:36.3411205+00:00",
  "serviceUrl": "https://directline.botframework.com/",
  "channelId": "directline",
  "from": {
    "id": "ZidanBot@_dYNoVGXoHI",
    "name": "ZidanBot"
  },
  "conversation": {
    "id": "5JAk9pVwUU3GOrw2xAuwQY"
  },
  "recipient": {
    "id": "userid"
  },
  "locale": "en-US",
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "TextBlock",
            "text": "Test Title"
          },
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "text": "Item 1"
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "data": "Item 1"
            },
            "style": "emphasis"
          },
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "text": "Item2 2"
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "data": "Item 2 - I need this to be shown in webchat after user clicks",
              "BackroudProp": "Value"
            },
            "style": "emphasis"
          }
        ],
        "actions": []
      }
    }
  ],
  "entities": [],
  "replyToId": "5JAk9pVwUU3GOrw2xAuwQY|0000051"
}
```

But when I select the action only this gets sent back:

```javascript
{
   "type":"message",
   "text":"Item 2 - I need this to be shown in webchat after user clicks",
   "from":
    {
      "id":"userid"
   },
   "locale":"en-US",
   "textFormat":"plain",
   "timestamp":"2018-04-16T14:32:09.317Z",
   "channelData":
   {
      "clientActivityId":"1523888963745.9576302900454852.2"
   }
}
```

**Comment by compulim** [comment] 2018-05-01 18:45
Do you mean sending both text and data when the user click on the submit button? We currently do not support that.

According to Adaptive Cards schema [here](https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema#actionsubmit). `Action.Submit` only support `type`, `title`, and `data`.

**Comment by baki32** [comment] 2018-05-02 04:31
Ok, so what is the best practice then to send more data back to the bot while maintaining consistent user experience?

**Comment by baki32** [comment] 2018-05-03 11:29
Thanks for the response, I was already looking into the code of the webchat. But when I was debugging it there was listener subscribed to sendmessage action that also generated POST request down to server which is something that we don't need as we just need the message appear on the screen and data shall be sent over backchannel. 

I might be thinking wrong as I'm not superskilled in React and especially in Redux :)

**Comment by compulim** [comment] 2018-05-30 16:40
Yes, currently it is a limitation. The send box is directly connected to send message (a.k.a. POST) so the user cannot actually send one thing, and POST another thing.

**Comment by compulim** [comment] 2018-05-30 16:44
Closing this by design.

**Closed by compulim** 2018-05-30 16:44 UTC
Labels: enhancement

**Comment by billba** [comment] 2018-06-06 06:27
Understood. In that case, the Web Chat repo may not be the best place to discuss this.
