### ISSUE TITLE
There is no initial greeting message

### ISSUE THREAD

**Issue by axnserv** [Microsoft/BotFramework-WebChat#440] opened 2017-05-01 22:01 UTC
Web Chat control used to have an initial greeting. It was something like "to start say “hi” " but its been removed now. There should be a default or a parameter to set it to something the developer wants.

**Comment by billba** [comment] 2017-05-01 22:02
Duplicate of #298. Just have your bot send the message.

**Closed by billba** 2017-05-01 22:02 UTC
