### ISSUE TITLE
When I do ask a specific question in IE Edge - it crashed

### ISSUE THREAD

**Issue by adn-aceres** [microsoft/BotFramework-WebChat#2242] opened 2019-07-31 09:40 UTC
## Screenshots

![Screenshot 2019-07-22 at 13 17 08](https://user-images.githubusercontent.com/53514449/62201256-56385500-b387-11e9-9cb8-24b6ed855b80.png)
![Screenshot 2019-07-22 at 12 06 45](https://user-images.githubusercontent.com/53514449/62201270-59cbdc00-b387-11e9-8652-1544bb282c22.png)

## Version

frame-markup:

```
<script>
                window.WebChat.renderWebChat(
                    {
                        directLine: window.WebChat.createDirectLine({
                            token: "secret"
                        }),
                        userID: "You",
                        username: "Web Chat User",
                        locale: "en-US",
                        styleOptions: {
                            rootHeight: "100%",
                            rootWidth: "100%",
                            backgroundColor: "rgb(245, 245, 245)",
                            bubbleBorderRadius: 8,
                            bubbleImageHeight: 240,
                            bubbleMaxWidth: 480,
                            bubbleMinHeight: 40,
                            bubbleMinWidth: 250,
                            messageActivityWordBreak: "break-word",
                            botAvatarInitials: " ",
                            avatarSize: 30,
                            fontSizeSmall: "80%",
                            bubbleBackground: "#0093D5",
                            bubbleTextColor: "#FFFFFF",
                            bubbleFromUserBackground: "#FFFFFF",
                            bubbleFromUserTextColor: "#000000",
                            bubbleFromUserBorderRadius: 8,
                            // Send box
                            hideSendBox: false,
                            hideUploadButton: true,
                            microphoneButtonColorOnDictate: "#F33",
                            sendBoxBackground: "White",
                            sendBoxButtonColor: "#767676",
                            sendBoxButtonColorOnDisabled: "#CCC",
                            sendBoxButtonColorOnFocus: "#333",
                            sendBoxButtonColorOnHover: "#333",
                            sendBoxHeight: 40,
                            sendBoxMaxHeight: 200,
                            sendBoxTextColor: "Black",
                            sendBoxBorderBottom: "",
                            sendBoxBorderLeft: "",
                            sendBoxBorderRight: "",
                            sendBoxBorderTop: "solid 1px #E6E6E6",
                            sendBoxPlaceholderColor: "#767676",
                            sendBoxTextWrap: false,
                            // Connectivity UI
                            connectivityIconPadding: 10 * 1.2,
                            connectivityMarginLeftRight: 10 * 1.4,
                            connectivityMarginTopBottom: 10 * 0.8,
                            connectivityTextSize: 12,
                            failedConnectivity: "#C50F1F",
                            slowConnectivity: "#EAA300",
                            notificationText: "#5E5E5E",

                            typingAnimationBackgroundImage: null,
                            typingAnimationHeight: 20,
                            typingAnimationWidth: 64,
                            // Suggested actions
                            suggestedActionBackground: "#FFFFFF",
                            suggestedActionBorder: "solid 2px #0063B1",
                            suggestedActionBorderRadius: 0,
                            suggestedActionImageHeight: 20,
                            suggestedActionTextColor: "#0093D5",
                            suggestedActionDisabledBackground: "#FFFFFF",
                            suggestedActionDisabledBorder: "solid 2px #E6E6E6",
                            suggestedActionDisabledTextColor: "#767676",
                            suggestedActionHeight: 40
                        }
                    },
                    document.getElementById("webchat")
                );
            </script>

```
I use this / Version:
`https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js`

## Describe the bug

The webchat crashed after inserting this text "How are zou_" or "how are zou".

## To Reproduce

1. Open Chat with IE Edge
2. Insert a question like "How are zou_" or "how are zou"
3. The webchat crashes
4. See error in the console (screenshot attached)

## Expected behavior

It should not be crashed then with IE Edge and IE11.

## Additional context

Is there a special setting in the backend of BotFramework needed?

[Bug]

**Comment by corinagum** [comment] 2019-07-31 16:24
Duplicate of #2187 
The fix has been merged on https://github.com/microsoft/BotFramework-WebChat/pull/2195 We are optimistic that we will release a patch today. :)

**Closed by corinagum** 2019-07-31 16:24 UTC
Labels: Bug, Duplicate
