### ISSUE TITLE
I am using WebChat in My web application, I want to open urls in same tab where chat window open

### ISSUE THREAD

**Issue by RohitMane** [Microsoft/BotFramework-WebChat#982] opened 2018-05-17 10:48 UTC
I am using WebChat in My web application, I want to open urls in same tab where chat window open.
Hey @danmarshall Can you help me on this ?
If you want more information then please let me know.
Thanks in Advance. :)

**Comment by EricDahlvang** [comment] 2018-05-17 16:09
Hi @RohitMane 

I'm no @danmarshall , but I know you can fork this repository and modify this line to enable opening urls however you prefer: https://github.com/Microsoft/BotFramework-WebChat/blob/617de0a0145aef1f2843c72d7ec4e6818c0bf7fb/src/Chat.tsx#L326

Does this answer your question?

**Comment by danmarshall** [comment] 2018-05-22 00:30
@RohitMane can you try commenting out [lines 31 to 51 in src/FormattedText.tsx](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/FormattedText.tsx#L31) ?

**Comment by compulim** [comment] 2018-06-14 08:47
Dupe of #984.

**Closed by compulim** 2018-06-14 08:47 UTC
