### ISSUE TITLE
Speech: Hitting on the mic icon doesn't stop speech

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-WebChat#1735] opened 2019-02-15 05:59 UTC
Hitting on the mic while webchat is speaking doesn't stop the speech and webchat ends up listening to itself.

In v3 a user was able to stop the speech by starting to type something in the chat textbox. It would be good if that was possible today and if hitting on the mic would also stop speech.

Thanks

**Comment by compulim** [comment] 2019-02-15 11:12
This is a known issue on Speech Services. The problem is the Speech Services SDK has no official API for stopping the microphone (nor event for detecting if any sound was heard).

There is an unofficial API for this feature and we will implement it as a workaround in 4.4

**Comment by gabog** [comment] 2019-02-15 12:28
How about pressing the space bar or some other mechanism to stop speech while the prompt is being read?

**Comment by compulim** [comment] 2019-07-26 17:39
Working on this, this consists of two issues:
- Cognitive Services do not send enough event to let us know when we can stop/abort
- Cognitive Services has no way to stop/abort, so currently, we fake the abort by ignoring the result. We cannot restart the microphone before the recognition engine is fully stopped.

**Comment by compulim** [comment] 2019-08-06 02:47
Should be fixed.

**Closed by compulim** 2019-08-06 02:47 UTC
Labels: 4.6, Approved, Enhancement, P2, Parity, Speech, Triaged

**Comment by omroczkowski** [comment] 2020-01-02 10:49
It worked for me 2 weeks ago. Doesn't work anymore. Tested on 06.c.cognitive-services-speech-services-js and my bots.
