### ISSUE TITLE
Typing activity is preventing retryprompt activity from showing up

### ISSUE THREAD

**Issue by MukulSingh10** [microsoft/BotFramework-WebChat#3951] opened 2021-06-17 05:19 UTC
I have a simple question answering bot based on V4 template, I have a prompt that asks for password, if the password is wrong it retries by asking again.

It works fine until I add the typing activity to give the user some feedback while waiting, in that case, the retry Prompt doesn't show the text anymore (But it's still working, if you type the right password it will go on as expected)

At this moment I'm not sure if I'm doing something wrong or I just hit a bug.

I've tried creating the prompt in different ways and creating the typing activity inside a dialog but there's been no luck.

**Comment by v-kydela** [comment] 2021-06-17 19:13
Thank you for the report, @MukulSingh10 

What you're describing is expected behavior. You can read about it here: https://github.com/microsoft/botbuilder-dotnet/issues/1589

The problem is caused by the `Responded` property of the turn context, which gets set when the typing activity is sent. You can work around the problem by sending the typing activity directly through the adapter or the connector client and bypassing the turn context, or you can work around the problem in the prompt itself by using a custom validator instead of relying on the retry prompt.

This isn't a Web Chat issue so I'll go ahead and close it.

**Closed by v-kydela** 2021-06-17 19:13 UTC
Labels: Area: Migration Support, Bot Services, Bug, customer-reported
