### ISSUE TITLE
MockBot URL's are broken and interlinking of samples are broken

### ISSUE THREAD

**Issue by ashokduddukuri** [microsoft/BotFramework-WebChat#2948] opened 2020-02-26 13:31 UTC
References to Mockbot is broke in several samples.
Interlinking of samples are also broken. 

This is one of the sample, the links are broken:
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/e.piping-to-redux

**Comment by corinagum** [comment] 2020-02-26 17:55
Yep - I found the same this morning. Investigating the cause.

**Comment by corinagum** [comment] 2020-02-26 17:59
@ashokduddukuri I'm not finding a repro of the interlinking samples being broken. The link you provided works for me. Could you send another interlinking sample that's not working?

**Comment by corinagum** [comment] 2020-02-26 19:02
for the github pages samples, I am rerunning the CD as it failed this morning ~3am PST

**Comment by compulim** [comment] 2020-02-26 22:21
Thanks for reporting. Instead of re-run, I re-created a new CD and it should be fixed.

I am expecting it may fail again next week. Please keep the log by re-creating a new CD, so we can look at the log. Re-run will overwrite the log.

**Closed by compulim** 2020-02-26 22:21 UTC
Labels: Bot Services, Bug, customer-replied-to, customer-reported

**Comment by ashokduddukuri** [comment] 2020-02-27 06:49
@corinagum 

- proceed to the link for overview section - https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/e.piping-to-redux#overview
- All the links referring to other sample are broken, you can validate it by clicking on `06.recomposing-ui/a.minimizable-web-chat`

**Comment by corinagum** [comment] 2020-02-27 17:09
@ashokduddukuri, thanks for the extra info. I'll get a quick fix out today.
