### ISSUE TITLE
Display a message when a new window with bot conversation is displayed

### ISSUE THREAD

**Issue by pikskip** [Microsoft/BotFramework-WebChat#1038] opened 2018-07-11 13:00 UTC
Hi , i can't displayed a message when my  converdation window is launched

Description ; 
In my main page, i have an input field used to start a conversation. 
When user click on the button, a popup is display. 

I would like to display input field content in popup. For the moment, the input message is taking into account by bot but the message is not displayed.

```
      botConnection.postActivity({
          from: { id: 'userid', name: 'myUserName' }, 
          type: 'message',
          text: 'a message for you, Rudy'
          }).subscribe(
               function (id) {
                      //callmemaybe(id, firstMessage);
                  console.log("Posted activity, assigned ID ", id)},
               function(error){console.log("Error posting activity", error)}
          );
```

I tried the following solution but this solution remove some event in the automatic first answer.
 ```
       botConnection.postActivity({
            from: { id: 'userid', name: 'myUserName' }, 
            name: 'callmebaby',
            type: 'message',
            text: firstMessage
            }).subscribe(
                 function (id) {
                        callmebaby(id, firstMessage);
                    console.log("Posted activity, assigned ID ", id)},
                 function(error){console.log("Error posting activity", error)}
            );
      function callmemaybe (id, content) {
          var el = '<div class="wc-message-wrapper list" data-activity-id="' + id + '"><div class="wc-message wc-message-from-me"><div class="wc-message-content"><svg class="wc-message-callout"><path class="point-left" d="m0,6 l6 6 v-12 z"></path><path class="point-right" d="m6,6 l-6 6 v-12 z"></path></svg><div><span class="format-plain"><span><!-- react-text: 101 -->' + content + '<!-- /react-text --><br></span></span><!-- react-empty: 103 --></div></div></div><div class="wc-message-from wc-message-from-me"><span><!-- react-text: 119 -->userid<!-- /react-text --></span></div></div>';
         var textGroup = document.querySelector('.wc-message-group-content')
         textGroup.innerHTML = el + textGroup.innerHTML;
      }
```
do you have some advice or solution ?

**Comment by telkomops** [comment] 2018-08-29 19:08
postActivity from the client and implement the message on the server side. 
Send the postActivity with type:"event"
On the server trap the event and response back with appropriate content you want to display on the start up message via Hero or Adaptive Card.

**Comment by compulim** [comment] 2018-11-27 21:33
This is duplicate of #1371. We will create a new sample showing how this can be done.

**Closed by compulim** 2018-11-27 21:33 UTC
Labels: 4.2, Sample, Triaged
