### ISSUE TITLE
How do I change the voice font to be used with WebChat?

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-WebChat#1729] opened 2019-02-14 05:28 UTC
In the previous version of webchat (v3), we were able to set the voice font the synthetizer would use ("Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)", "Microsoft Server Speech Text to Speech Voice (en-US, Guy24kRUS)", etc.)

I don't seem to see that parameter in the current call to window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory in the new webchat.

How do I change the voice font?

**Comment by corinagum** [comment] 2019-02-14 17:14
Hi @gabog, as far as I can tell this is a duplicate of your filed issue #1396. This feature is currently slated for our 4.4 release.

**Closed by corinagum** 2019-02-14 17:14 UTC

**Comment by gabog** [comment] 2019-02-14 17:37
Hi @corinagum, #1396 is about the emulator, my request here was about webchat and JS, are these the same thing?

**Comment by corinagum** [comment] 2019-02-14 17:39
@gabog, the changes will need to be made on Web Chat before they can be made on emulator. Thanks for asking. :)

**Comment by gabog** [comment] 2019-02-14 17:40
ah, ok, thanks sorry for the noise, I see that both webchat and emulator are mentioned in the thread. Our main priority is emulator. 

Thanks
