### ISSUE TITLE
Standard setup for a robust webchat

### ISSUE THREAD

**Issue by scch1002** [microsoft/BotFramework-WebChat#2896] opened 2020-02-10 21:41 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

Specific situation:
If a conversation lasts longer than 15 minutes then the directline token is automatically updated. There does not exist a way in which to retrieve this updated directline token. The updated token is needed in the case of a page refresh so that the webchat state can be restored. Custom code can be used to attempt to reconnect to the conversation but this should not be necessary.

In general:
The setup for my situation is not anything special. I am sure the majority of situations are the same as mine. The documentation on how to properly setup a robust webchat using the React webchat component is non-existent.

Robust meaning the ability to handle page refreshes and conversation re connections.

**Describe the request in detail**
There should be a standard single cohesive sample detailing the handling of page refreshes and conversation re-connections. This being the most common robust use case for setting up a webchat.

Better yet, it would be great if this logic could be implemented in the webchat. That would make sense because the webchat already handles token refreshes, instead of leaving the process entirely manual.

**Describe alternatives you have considered**
The alternative that I think exists in this situation would be to investigate the possibility of writing a custom directline event that would catch the webchat token refresh event.

**Comment by tdurnford** [comment] 2020-02-12 17:25
This is a duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/2343. The Web Chat development team is working on putting together a sample that should handle the scenarios you mentioned above. 

Web Chat takes a dependency on [Direct Line JS](https://github.com/microsoft/BotFramework-DirectLineJS) which handles all of the token refresh logic and would have to be responsible for emitting a token refresh event that Web Chat could consume.

**Closed by tdurnford** 2020-02-12 17:25 UTC
Labels: Bot Services, Enhancement, Pending, customer-reported

**Comment by scch1002** [comment] 2020-02-12 17:46
The issue you have linked does not cover my above problem. From what I can tell there are no samples detailing how directline should be properly integrated into the webchat. Currently the webchat does not handle fundamental use cases. Neither are there cohesive samples demonstrating how your product should be used in a really world scenario. There are basic scenarios that need to be addressed.

**Comment by scch1002** [comment] 2020-02-12 17:53
I am really looking for a demonstration of how this product was designed to be setup in a really world scenario. That includes restoring the chat histories of webchats after a page refresh. Particularly a page refresh after the initial token has expired and been replace by a new token.

**Comment by jiruss** [comment] 2020-02-12 18:54
This looks like it is still on the Bot PG radar being tracked with a number of similar issues https://github.com/microsoft/BotFramework-DirectLineJS/issues/124.

**Comment by scch1002** [comment] 2020-02-12 19:19
It seems like there is more work that could be done to make the directline connectivity logic more complete and stable.
