### ISSUE TITLE
Unable to send Attachment in Webchat , same code is working fine in emulator

### ISSUE THREAD

**Issue by saravana13** [Microsoft/BotFramework-WebChat#1925] opened 2019-04-24 20:22 UTC
```   
var response = MessageFactory.Attachment(new Attachment
     {
          Name = @"application.png",
          ContentType = "image/png",
          ContentUrl =  "base64sting"
     });

await dc.Context.SendActivityAsync(response);
```

Above code throwing the below exception in webchat , in emulator i it is woring fine

```
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\Conversations.cs:line 1121
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\ConversationsExtensions.cs:line 241
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 316
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 267
```

**Comment by tdurnford** [comment] 2019-04-24 22:35
This appears to be a duplicate of this [question](https://stackoverflow.com/questions/55839371/unable-to-send-attachment-in-webchat-using-directline-same-code-is-working-fine) on StackOverflow.

**Comment by corinagum** [comment] 2019-04-25 19:16
What version of Web Chat are you using?

**Comment by corinagum** [comment] 2019-05-01 16:10
Closing due to inactivity.

**Closed by corinagum** 2019-05-01 16:10 UTC
Labels: Pending
