### ISSUE TITLE
Only creating ImBack SuggestedAction

### ISSUE THREAD

**Issue by bwamie** [Microsoft/BotFramework-WebChat#1719] opened 2018-12-07 21:10 UTC
## Versions
SDK Version 4.2.*

## Describe the bug
This function should allow creating different types of ActionTypes.  Therefore developer can not create another type of action type such as MessageBack. Given the fact that MessageBack is being supported in C# SDK and channels, we need to provide an option to pass the SuggestedAction actionType.

[bug]

**Comment by compulim** [comment] 2019-02-12 22:25
@bwamie this is a dupe of #1402. Resolved in PR #1581 and released as dev build on and after 4.2.1-master.77b466e.

You should see it in 4.3 soon. 😉

**Closed by compulim** 2019-02-12 22:25 UTC
Labels: 4.3, Duplicate

**Comment by bwamie** [comment] 2019-02-13 01:37
Thanks @compulim  :)
