### ISSUE TITLE
Video card (autostart) is not playing the video automatically

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-WebChat#3374] opened 2020-08-01 12:40 UTC
## Version
4.9.0

## Describe the bug

1. Video card -> autostart is not playing the video automatically
2.  Image -> Thumbnail placeholder is not displaying.

## Steps to reproduce

Try the Video Card sample with autostart and Image. ( I have tried the sample with Python)

## Expected behavior
Video should play automatically and image should be display.

**Comment by compulim** [comment] 2020-08-05 19:08
@rvinothrajendran for video card, which of the following are you playing? MP4, YouTube, or Vimeo?

**Comment by rvinothrajendran** [comment] 2020-08-06 04:01
@compulim You tube video.

**Comment by compulim** [comment] 2020-08-10 19:01
I think it's a bug on our side. Will triage in our next release.

I tried this IFRAME and it can auto-play.

```html
<iframe id="ytplayer" type="text/html" width="720" height="405"
src="https://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1"
frameborder="0" allowfullscreen>
```

**Comment by cwhitten** [comment] 2020-11-09 19:34
If there are multiple video cards in the conversation history we wouldn't want to auto-play all of them

**Comment by compulim** [comment] 2021-01-20 00:13
Sounds like browser imposed restrictions on autoplay to prevent annoying ads.

- If the video is muted, it can be autoplayed
  - Muted means, either have a `muted` attribute, or does not have any audio tracks (a silent audio track does not count)
- In Chrome, if the user has played a video with audio, for at least 7 seconds, video will autoplay with audio

Details at https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide.

**Comment by compulim** [comment] 2021-01-21 00:20
I looked at our code and we do translate `autostart` to HTML's `autoPlay`, https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/bundle/src/adaptiveCards/Attachment/VideoCardContent.js#L21. So I believe it is working as intended.

Web page author should obey to the auto play restrictions as mentioned above.

Closing as no repro.

**Closed by compulim** 2021-01-21 00:20 UTC
Labels: Bot Services, Bug, Community: Help wanted, P1, backlog, customer-replied-to, customer-reported, front-burner, needs-scheduling, needs-team-attention
