### ISSUE TITLE
Suggested actions navigation arrows should indicate focus visually

### ISSUE THREAD

**Issue by ljubomirsinadinovski** [microsoft/BotFramework-WebChat#1673] opened 2019-01-31 09:18 UTC
After clicking on the horizontal navigation arrow in the quick answer area, if you don't click anything else and move the cursor away we get this behavior:

1. The CLICKED arrow doesn't disappear (still visible)
2. The other arrow disappears (becomes invisible)

For better understanding I am including this screenshot: 
![screenshot at jan 31 10-17-19](https://user-images.githubusercontent.com/24614182/52044047-6c349c80-2541-11e9-8d37-97bbb5956c64.png)

And forgot to add that the change in styleSet doesn't affect these arrows

ANOTHER BUG:
Another bug (that is included in version: `"botframework-webchat": "^4.2.1-master.0dffd85",`) is that the actions have quotes around them (you can notice them on the picture above) , while I am receiving them without quotes from directLine (checked in the json that I received).

BTW: I know that 4.2.1 is not official yet, but 4.2.0 is too broken for my implementation, sry.

**Comment by corinagum** [comment] 2019-01-31 17:57
Confirmed repro of this bug on MockBot: 
![image](https://user-images.githubusercontent.com/14900841/52074188-304c0800-253e-11e9-91dc-75c8b6662512.png)
Related to your second comment, we already have https://github.com/Microsoft/BotFramework-WebChat/issues/1586 open for tracking this issue.

Your last bug has been resolved and can be utilized in the latest bits. https://github.com/Microsoft/BotFramework-WebChat/issues/1602 Otherwise the fix will be released with 4.3

**Comment by compulim** [comment] 2019-02-15 02:24
If the button is focused, it won't slide away, for accessibility reason. That's why the button is still there.

Maybe we use a non-keyboard gesture to click on it, we should blur the focus. Need to investigate a good and reliable solution to differentiate between keyboard focus and mouse click focus.

**Comment by corinagum** [comment] 2019-05-13 21:27
Provide better focus indication on this element

**Comment by DesignPolice** [comment] 2019-05-20 21:36
@compulim @corinagum @tdurnford 

Hello, @tdurnford tagged me on this, I'm not clear from this thread if we have figured out a fix for this or not? @compulim last comment seems to imply we need to research a better solution for Accessibility or do I just need some heavier focus lines to make it more obvious?? @corinagum looks like you "tapped" out on this one?

**Comment by corinagum** [comment] 2019-05-21 16:34
Yeah, @tdurnford is taking over this one. Right now there is no focus indication on the flippers, so he tagged you I guess to get your input. We discussed the possibility of adding distinction between a keyboard and mouse event, but @cwhitten is satisfied with us having focus indication to improve the UX. This will sufficiently indicate why the button doesn't immediately disappear.

**Comment by DesignPolice** [comment] 2019-05-21 17:01
Thanks @corinagum - @compulim do we have any Focus traits in WebChat currently? My MockBot isn't working to verify.

**Comment by corinagum** [comment] 2019-05-21 17:04
You can look at our sample bots to hunt around for focus indicators. [Click the 'Try out MockBot' link on the sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.a.getting-started-full-bundle).

**Comment by DesignPolice** [comment] 2019-05-21 18:45
Ah thanks that helped. I will pin that link.

looks like we have a couple of different focus options - They all seem a little bit different.

I would recommend we just align to the Fluent Web version that now being used on most everything and is available in Figma - with the CSS and redlines etc. Might make everything easier. 

@tdurnford  @corinagum - I will text you a link, but I have attached a screen grab of their buttons.

![Screen Shot 2019-05-21 at 11 33 08 AM](https://user-images.githubusercontent.com/45223620/58122162-d68b4e80-7bbd-11e9-819f-4feac6089abd.png)

**Comment by corinagum** [comment] 2019-07-08 18:08
the design specs above do not factor in the shape of the focus indicator, which is a circle.

**Comment by tdurnford** [comment] 2019-11-21 17:54
Bumping the react-film dependency to the next version and adding the `flipperBlurFocusOnClick` to the suggested actions and attachment carousel film strip should resolve this issue.

**Comment by corinagum** [comment] 2019-11-21 17:55
react-film has been updated, now we need release and bump.

**Closed** 2020-01-15 18:07 UTC
Labels: Blocked, Bug, Design needed, P1, R8, Triaged
