### ISSUE TITLE
In WebChat, Is it possible to open button URL in same window?

### ISSUE THREAD

**Issue by PoojaGidd** [microsoft/BotFramework-WebChat#3493] opened 2020-09-23 06:27 UTC
## Describe the bug

In WebChat, Is is possible to persist the chat and the chat window while we redirect the users in the background (in the same website) upon clicking a button URL. The redirect url is also in the same website where the WebChat is hosted and the WebChat is available in all the pages of the website.

If this is not possible, Is there an alternate way for the same experience?

**Comment by tdurnford** [comment] 2020-09-23 20:50
@PoojaGidd Closing as duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/2892

**Closed by tdurnford** 2020-09-23 20:50 UTC
Labels: Bot Services, Bug, customer-reported, needs-scheduling, needs-team-attention
