### ISSUE TITLE
Delete upload button from chatbot

### ISSUE THREAD

**Issue by vmunnuru** [Microsoft/BotFramework-WebChat#1433] opened 2018-12-04 06:25 UTC
We are trying to delete upload button from the button, see below picture.

<img width="399" alt="upload-button" src="https://user-images.githubusercontent.com/25169611/49422461-f1a60580-f7b9-11e8-9eae-b21cd3621a07.png">

We have tried to create middleware, and custom component which extends actual component but no luck.

And also we are trying to understand how ReactWebChat component listens our changes with middleware.

It is well and good if we have a code sample for customisations

I am trying to implement in a React project and interacting with bot fromework with npm install botframework-webchat@master, as i don't want lose updates on master

**Comment by corinagum** [comment] 2018-12-04 23:43
This is a duplicate of #1383

**Closed by corinagum** 2018-12-04 23:43 UTC
