### ISSUE TITLE
Virtual Assistant: Sign into GitHub

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1472] opened 2018-12-11 22:57 UTC
Ability to "sign-in" using the built in website/ad signin capabilities (see linked accounts in the GitHub repo for an example. The UserId retrieved as part of this is set on the webChat. Example already done [here](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest)

### Note to implementor

- [ ] Add a button with a predefined link, navigate to linked account with Direct Line user ID

**Comment by corinagum** [comment] 2019-02-20 20:39
duplicate of https://github.com/Microsoft/BotFramework-WebChat/issues/1564

**Closed by corinagum** 2019-02-20 20:39 UTC
Labels: Duplicate, Virtual Assistant
