### ISSUE TITLE
Sample: Send the greeting message in ActivityTypes.Event type activity

### ISSUE THREAD

**Issue by huajunzhao** [Microsoft/BotFramework-WebChat#1039] opened 2018-07-11 14:32 UTC
We're using the botframework-Webchat in React app. I have added the following code to use the backchannel functionality, postLoadMessage method is called when the Webchat is loaded.

  postLoadMessage = () => {
    var botConnection = new DirectLine({
      secret: this.props.botDirectLineSecret
    });
    botConnection
      .postActivity({ type: "event", value: "Greetings", from: { id: this.state.username } })
      .subscribe(id => console.log("success"));
  };

in the MessageContorller.cs, we have the following logic:

If (activity.Type == ActivityTypes.Event)
            {
                var client = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials());
                var reply = activity.CreateReply();
                reply.Text = "Our greeting message";
               await client.Conversations.ReplyToActivityAsync(reply);
}

Is this correct? It seems it doesn't work since i didn't see the expected greetings message on the Webchat embedded in the web page.

Can you please review?

**Comment by EricDahlvang** [comment] 2018-07-11 16:58
Hi @huajunzhao 

I think we would need to see more of your code in order to determine what is going wrong.  Based on what you've shared, it looks like you might be creating the DirectLine object multiple times?  Also, are you providing the DirectLine object to BotChat.App when it is being constructed?  

The botConnection should be created just once.  An example of how to do this can be found here: https://github.com/Microsoft/BotBuilder/issues/4245#issuecomment-369311452


```js
 var user = {
            id: 'user-id',
            name: 'user name'
        };

        var botConnection = new BotChat.DirectLine({
            token: '[DirectLineSecretHere]',
            user: user
        });

        BotChat.App({
            user: user,
            botConnection: botConnection,
            bot: { id: 'bot-id', name: 'bot name' },
            resize: 'detect'
        }, document.getElementById("bot"));

        botConnection
            .postActivity({
                from: user,
                name: 'Greetings',
                type: 'event',
                value: ''
            })
            .subscribe(function (id) {
                console.log('"Greetings request event" sent');
            });
```

**Comment by chintan3100** [comment] 2018-07-27 08:57
How to display greeting msg to web chat? It's look like it post greeting call but greeting msg not visible to UI

**Comment by compulim** [comment] 2018-11-27 21:31
This is dupe of #1371. We will create a sample showing how this can be done.

**Closed by compulim** 2018-11-27 21:31 UTC
Labels: 4.2, Approved, Sample
