### ISSUE TITLE
Up arrow to bring up last sent messages

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#58] opened 2016-10-11 00:07 UTC

**Comment by danmarshall** [comment] 2016-10-11 00:24
haha I've wanted this behavior too! But I think it's because we're devs. I don't think chat clients actually have this behavior. (One time when I was finished chatting with someone, I typed "exit" LOL)

**Comment by kevkor** [comment] 2016-10-14 16:56
No, we don't need to support this.

**Comment by danmarshall** [comment] 2017-05-12 18:19
Might be nice to enable "dev mode" where this and other features light up.

**Comment by anth12** [comment] 2017-05-12 19:55
I would really like to have support for this, specifically for use within the emulator. But yeah, it should be disabled by default.

**Comment by edwin-huber** [comment] 2017-08-17 06:50
This would really have helped us this week.
Does anyone know why this has not been done?
Is there an architectural issue preventing it's implementation in the emulator?

**Comment by billba** [comment] 2017-08-17 17:27
@edwin-huber It hasn't been done because no one has done it, and that is mostly because no one has particularly made a strong case for it. As you can see above, a former member of the team was even flatly against it. I don't think anyone has even checked all the other chat clients to see if this feature exists anywhere else. If you are passionate about it, it would be great for you to do this footwork.

Offhand it's a pretty easy feature. We could probably just use the existing message history.

**Comment by dividor** [comment] 2018-02-03 00:52
We have a use-case where this would be useful. Our bot has the ability to interface with elastic search and query a range of internal data sources. We use LUIS to extract entities which map to labels used when querying elastic. So for example ..

search library for articles on my favorite subject
search release notes for articles on my favorite subject
search release notes for articles on my favorite subject about science
etc

So they are slightly modifying the previous query.

Up arrow repeat of the previous input would be a nice way of doing this, we'd love this feature.

**Comment by corinagum** [comment] 2019-03-20 20:29
Closing as a dupe of #1091

**Closed by corinagum** 2019-03-20 20:29 UTC
Labels: 4.4, Approved, Enhancement, P3, Triaged
