### ISSUE TITLE
Missing exported functions from older versions

### ISSUE THREAD

**Issue by hrazmsft** [microsoft/BotFramework-WebChat#3909] opened 2021-05-24 10:13 UTC
## Screenshots

![image](https://user-images.githubusercontent.com/66222191/119332611-80ac7e00-bc91-11eb-82fa-7aa3d7f08ccc.png)

## Version

NPM: botframework-webchat ^4.13.0

## Describe the bug

After upgrading the component to version 4.13.0, all the exported functions removed from the Typescript definition.

## Expected behavior

The exported functions from older versions will be exported in 4.13.0

## Additional context

[Bug]

**Comment by corinagum** [comment] 2021-05-24 18:26
Duplicate of #3856

**Closed by corinagum** 2021-05-24 18:26 UTC
Labels: Bug, Support
