### ISSUE TITLE
In the new version of the webchat, links in chat open in the iFrame

### ISSUE THREAD

**Issue by strangecyan** [Microsoft/BotFramework-WebChat#194] opened 2016-12-05 13:32 UTC
In the new preview webchat if you try to open an external link in webchat it opens it in that iFrame, where in the previous version it opened it in a new tab. I don't think that opening it in the iFrame make sense for a vast majority of cases due to the fact that it replaces the chat window.

**Comment by billba** [comment] 2016-12-05 14:41
Duplicate of #165

**Closed by billba** 2016-12-05 14:41 UTC
