### ISSUE TITLE
Hyperlinks are opening in Web Chat.

### ISSUE THREAD

**Issue by gauravrattan1980** [Microsoft/BotFramework-WebChat#454] opened 2017-05-10 00:51 UTC
Hi All,

I am using Web Chat Channel with Microsoft Bot Framework and its opening Hyperlinks posted inside chat in Web Chat Channel itself. 
Note: This functionality was working fine till yesterday and it was opening different browser window for hyperlinks posted inside chat. We are using this from last 1 month and it suddenly stops's working. 

Please help?

Thanks
Gaurav

**Comment by danmarshall** [comment] 2017-05-10 01:12
Hi @gauravrattan1980 - thank you for reporting this. We recently switched markdown libraries, I'm suspecting this may be the cause. Are your links sent in markdown?

**Comment by gauravrattan1980** [comment] 2017-05-10 01:17
Yes you are correct. We have used markdowns for out hyperlinks...

Thanks
Gaurav

**Comment by gauravrattan1980** [comment] 2017-05-10 01:22
Can u give me idea, how long it will take to fix this issue.

Thanks in advance....

**Comment by danmarshall** [comment] 2017-05-10 01:23
I will be working on this quite soon :) are you building your own WebChat? Or are you retrieving botchat.js off a CDN ?

**Comment by gauravrattan1980** [comment] 2017-05-10 01:25
For our demo purpose, I have just enabled Web Chat channel from Microsoft Bot framework. In future we are thinking to build our own WebChat.

Thanks
Gaurav

**Comment by danmarshall** [comment] 2017-05-10 01:58
Hi Guarav - We should be deploying this sometime soon. Meanwhile I have sent a PR containing the fix https://github.com/Microsoft/BotFramework-WebChat/pull/455

**Comment by gauravrattan1980** [comment] 2017-05-10 03:27
Thanks for your swift response...

**Comment by danmarshall** [comment] 2017-05-10 03:29
Hi Guarav, it may not be deployed until late tomorrow at the earliest, so can you please use a temporary workaround: shift-click the links. Sorry about the inconvenience.

**Comment by gauravrattan1980** [comment] 2017-05-12 07:16
Hi Dan,
Any idea when will above changes get deployed? Thanks...

**Comment by danmarshall** [comment] 2017-05-12 20:23
Hi @gauravrattan1980 - it should deploy on Monday. We did not want to deploy during //build

**Comment by gauravrattan1980** [comment] 2017-05-17 05:11
Any information on above issue??

**Comment by gauravrattan1980** [comment] 2017-05-18 03:05
Thx mate... It's working now...

**Comment by danmarshall** [comment] 2017-06-14 18:22
@GeekTrainer can we get a new npm package to close this issue?

**Comment by GeekTrainer** [comment] 2017-06-14 19:20
Just published.

**Closed** 2017-06-14 20:41 UTC

**Comment by bramhechatejas** [comment] 2017-07-26 04:39
Hi, the same problem arising now. Hyperlinks are opening in a chat window instead of opening it in another window. Please help!

**Comment by danmarshall** [comment] 2017-07-26 05:06
Hi @bramhechatejas thank you for reporting this. Can you please tell me how your WebChat is hosted? Is it an iframe of webchat.botframework.com or is it your own hosted WebChat page?

**Comment by bramhechatejas** [comment] 2017-07-26 05:20
@danmarshall I have hosted webchat using iframe

**Comment by danmarshall** [comment] 2017-07-26 05:35
@bramhechatejas are you using the "enable preview" option on the WebChat configuration page? If so, this may be the older WebChat control. Otherwise, can you provide a sample of the markdown with hyperlinks and can you tell me if it is on a card attachment or directly in the message?

**Comment by bramhechatejas** [comment] 2017-07-26 05:52
@danmarshall Hi, yes, I'm using enable preview option in WebChat configuration page. what I have done here is added embed code of Microsoft bot framework in my wordpress page. Updated the changes.

**Comment by danmarshall** [comment] 2017-07-26 08:27
@bramhechatejas can you copy your markdown with the links so that we can reproduce the error? Or perhaps share your link?

**Comment by bramhechatejas** [comment] 2017-07-26 08:46
@danmarshall 
<html>
<head>
</head>
<body>
    <iframe height="400px" src='https://webchat.botframework.com/embed/wp-hospitalbot?s=y04CQSzM2KU.cwA.MB4.qtul5Prya5KnfEbiQmtGiOK3A4QnrHspy5b5DdvUTEQ'></iframe>
</body>
</html>

**Comment by bramhechatejas** [comment] 2017-07-26 08:46
@danmarshall Please test & let me know

**Comment by danmarshall** [comment] 2017-07-28 18:37
Hi @bramhechatejas thank you for that link. I was able to reproduce your error. Your bot was sending an html bit inside the message:
```
...In case of any queries <a href='https://www.gslab.com/'>Visit GS Lab</a>
```
the `<a>` tag should **not** be supported, we will need to disable this functionality. You can use markdown to enable this:
```
...In case of any queries [Visit GS Lab](https://www.gslab.com)
```

**Comment by bramhechatejas** [comment] 2017-07-31 04:24
@danmarshall Hi, will you please let me know how to disable this functionality inorder to get links work properly?

**Comment by billba** [comment] 2017-07-31 04:29
@bramhechatejas the actual bug here is that HTML tags should be ignored in the text. The only way your bot should communicate links is via Markdown syntax. This bug is being fixed (see https://github.com/Microsoft/BotFramework-WebChat/pull/606) and once it's merged, if you don't change to Markdown syntax, your behavior will go from "links open in chat window" to "links don't work at all."

**Comment by bramhechatejas** [comment] 2017-07-31 04:38
@billba @danmarshall Thanks for your support, markdown worked for me.

**Comment by SwedhaBalasubramanian** [comment] 2019-02-09 03:19
Is there a way how to include the hyperlink in Workplace/Facebook?
