### ISSUE TITLE
Unable to Add Bot Icon in Custom Web-Chat.

### ISSUE THREAD

**Issue by Chitma** [Microsoft/BotFramework-WebChat#481] opened 2017-06-01 07:03 UTC
Hi Guys,

I have created my customized version of web-chat from the botchat.css and botchat.js provided in the description.
https://unpkg.com/botframework-webchat/botchat.css
https://unpkg.com/botframework-webchat/botchat.js

I just copied those two files and saved it my project. 
I have noticed that botchat.js is minified version. Can I get a developer version for it to add bot icon ?

Is there something I am missing out for adding bot icon.

Thanks,
Manish Chitre.

**Comment by billba** [comment] 2017-06-01 10:17
Closing as duplicate of #43 - please follow that issue for progress on this feature

**Closed by billba** 2017-06-01 10:17 UTC
