### ISSUE TITLE
Need a special method

### ISSUE THREAD

**Issue by saikatbh94** [Microsoft/BotFramework-WebChat#897] opened 2018-03-12 08:55 UTC
Hi, I am building a bot. I wanted to know whether there is any method by which I will get to know whether any user message is being told through speech or just plain text or message? As we know that whenever any user message is told through speech, the bot also by default replies with both text and speech, but not in the case of text inputs. So I have used the speechsynthesizer object to make the the bot reply in speech for both the cases of text and speech input of the user. But this raises a problem. The system default speech reply and my speechsynthesizer object speak reply is told together by the bot. So this creates echo whenever the user is giving input through speech, because of juxtaposing of both the default speech and the speech synthsizer speech.

**Comment by compulim** [comment] 2018-03-13 00:22
[This line](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Store.ts#L103) will decide whether Web Chat should speak the bot reply or not.

There is a feature ask on #859 to let the user control whether to speak a reply or not.

**Comment by compulim** [comment] 2018-03-13 00:23
Closing the issue as dupe of #859. Please let me know if yours are different issue.

**Closed by compulim** 2018-03-13 00:23 UTC
