### ISSUE TITLE
setImmediate

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotFramework-WebChat#2605] opened 2019-11-15 18:36 UTC
## Version

4.0

## Describe the bug

I have a Adaptive card where we are dispalying some content and two Submit button as following:

"actions": [
    {
      "type": "Action.Submit",
      "id": "yesid",
      "title": "Yes",
      "data": "Yes"
    },
    {
      "type": "Action.Submit",
      "id": "noid",
      "title": "No",
      "data": "No"
    }

We tested our end and when ever we are clicking on Yes butoon ,  webchat is sending "Yes" as the string to the server:

![image](https://user-images.githubusercontent.com/10174566/68966669-81f31580-0793-11ea-974e-e6a267f5f412.png)

But for some of the users when they click on yes button the webchat is sending some wierd message as following:

![image](https://user-images.githubusercontent.com/10174566/68966738-a6e78880-0793-11ea-8cd0-05440b1807d9.png)

Because of the above our entire functionality get broken. Please elaborate.

## Additional context

[Bug]

**Comment by axelsrz** [comment] 2019-11-15 19:23
@compulim could you take a look at this one?

**Comment by tdurnford** [comment] 2019-11-15 19:34
@vikramdadwal I'm not able to reproduce this issue. What version of Web Chat are you using - there isn't a v4.0?

**Comment by vikramdadwal** [comment] 2019-11-15 19:38
its 4.6.0

**Comment by ankitvarmait** [comment] 2019-11-15 19:42
You can try clear cache at client side (user's machine) then it will resolve this problem. 
It happens when we change/modify script used on BOT.

- Try steps below
1. Open BOT on chrome, F12 then disable cache
2. Reload then it should work

**Comment by tdurnford** [comment] 2019-11-15 19:49
@vikramdadwal can you try @ankitvarmait's recommendation? I'll continue to investigate this.

**Comment by benbrown** [comment] 2019-11-26 19:14
@vikramdadwal Any more info you can provide? Were you able to try the recommendation?

**Comment by corinagum** [comment] 2019-12-03 23:14
Closing due to inactivity.

**Comment by tdurnford** [comment] 2019-12-03 23:17
@corinagum we are still investigating this issue, so we are not ready to close it yet.

**Comment by cwhitten** [comment] 2020-01-02 22:48
Closing due to inactivity.

**Closed by cwhitten** 2020-01-02 22:48 UTC
Labels: Bot Services, Bug, Investigate, Pending, customer-replied-to, customer-reported
